### ISSUE TITLE
Still failing with fish shell?

### ISSUE THREAD

**Issue by thiagomajesk** [elixir-lsp/elixir-ls#1005]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.15.7 (compiled with Erlang/OTP 26)
* Elixir Language Server version: 0.17.1 (Homebrew)
* Operating system: Ubuntu 22.04.3 under WSL
* Editor or IDE name (e.g. Emacs/VSCode): Helix
* Editor Plugin/LSP Client name and version: N/A

### Current behavior

I installed elixir-ls on a fresh WSL install and it seems I'm still getting errors while using fish shell:

Output of running elixir-ls on my terminal:

```
running /home/linuxbrew/.linuxbrew/Cellar/elixir-ls/0.17.1/libexec/launch.sh
Preferred shell fish is not supported, continuing in POSIX shell
Looking for ASDF install
ASDF install found in /home/linuxbrew/.linuxbrew/opt/asdf/libexec/asdf.sh, sourcing
/home/linuxbrew/.linuxbrew/Cellar/elixir-ls/0.17.1/libexec/launch.sh: 99: Syntax error: redirection unexpected
```

### Expected behavior

It seems that support for fish shell was introduced on version 0.17 but for some reason, I'm getting this weird error.

**Comment by lukaszsamson** [comment]
Homebrew is not an official way of installing

**Comment by thiagomajesk** [comment]
Thanks for pointing that out @lukaszsamson. I thought the package was maintained by the elixir-ls team. 
I've created an issue on homebrew core. Gonna leave it here for posterity: https://github.com/Homebrew/homebrew-core/issues/151387.
