### ISSUE TITLE
Allow bypassing `asdf` and/or `rtx` or allow specifying your own elixir/erlang versions/binaries exactly

### ISSUE THREAD

**Issue by lytedev** [elixir-lsp/elixir-ls#1011]
### Current behavior

I have a NixOS machine I do development on and I _do_ use `rtx` for some tools and projects. However, on other projects, I use a Nix flake with `direnv` to automatically install everything I need to develop those applications, including Erlang, Elixir, and ElixirLS. However, when I start ElixirLS, it sees that I have `rtx` installed and tries to use that when I actually want it to go ahead and use whatever Elixir version is on the path, since that is how the Nix flake sets things up.

I think this could be relatively easily accomplished by having some environment variables that essentially just disable the `asdf` and/or `rtx` checks so that ElixirLS's startup script can be forced to _not_ try and be smart.

I'm happy to submit a PR, too, if this sounds desirable to others.

Thank you!

**Comment by lukaszsamson** [comment]
Have you tried this solution? https://github.com/elixir-lsp/elixir-ls/issues/960#issuecomment-1673233594

**Comment by lytedev** [comment]
I did not! That seems to work. Sorry to bother! :heart:
