### ISSUE TITLE
Unable to start LSP in Fish + Sublime Text due to space in path

### ISSUE THREAD

**Issue by dvcrn** [elixir-lsp/elixir-ls#1012]
### Environment

* Elixir & Erlang versions (elixir --version): 
* ❯ elixir --version
```
Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]
Elixir 1.15.7 (compiled with Erlang/OTP 26)
```

* Elixir Language Server version: v0.17.3
* Operating system:  macOS
* Editor or IDE name (e.g. Emacs/VSCode): Sublime Text
* Editor Plugin/LSP Client name and version: LSP-elixir

### Problem

Debug from server: 

```
LSP: starting ['/Users/david/Library/Caches/Sublime Text/Package Storage/LSP-elixir/server/0.17.3/language_server.sh'] in xxxx
```

Output when manually starting the lsp:
```
Running /Users/david/Library/Caches/Sublime Text/Package Storage/LSP-elixir/server/0.17.3/launch.sh
Preferred shell is fish, launching launch.fish
Looking for ASDF install
ASDF install found in /opt/homebrew/opt/asdf/libexec/asdf.fish, sourcing
Installing ElixirLS release v0.17.3
Running in /Users/david/Library/Caches/Sublime Text/Package Storage/LSP-elixir/server/0.17.3
Install complete
No file named /Users/david/Library/Caches/Sublime
```

> /Users/david/Library/Caches/Sublime

It looks like it doesn't properly escape the path so the space in between `Sublime Text` is messing with the startup. 

When I change the path of the LSP to be instead in `~/src/elixir-ls`, all is good.

**Comment by lukaszsamson** [comment]
Fixed in https://github.com/elixir-lsp/elixir-ls/pull/1010
