### ISSUE TITLE
ElixirLS crashes every time I create a new map after the new update.

### ISSUE THREAD

**Issue by Luiyo033** [elixir-lsp/elixir-ls#1014]
### Current behavior
I'm using VSCode and just recently updated the extension. Now, every time I create a map it crashes with this output:

  **[Error - 4:00:05 PM] Stopping server failed
  Error: Stopping the server timed out
	  at ...\.vscode\extensions\jakebecker.elixir-ls-0.17.4\out\extension.js:89:9067**
 
I tried creating the map with no atom keys, but it still crashes immediately after. 

### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 26 and Elixir 1.15.7
* Elixir Language Server version: v0.17.4
* Operating system: Windows
* Editor or IDE name (e.g. Emacs/VSCode): VSCode

**Comment by lukaszsamson** [comment]
@Luiyo033 Please post a small file that reproduces this crash and attach logs from VSCode output tab https://github.com/elixir-lsp/vscode-elixir-ls#check-elixirls-output

**Comment by lukaszsamson** [comment]
I believe this error is fixed in https://github.com/elixir-lsp/elixir_sense/commit/861f7d41512a95205c47276f37df844aad45a422. Please reopen and fill details if it still affecting you on 0.17.5
