### ISSUE TITLE
Wrong location of warnings/errors.

### ISSUE THREAD

**Issue by thomasdziedzic** [elixir-lsp/elixir-ls#1021]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.15.7 (compiled with Erlang/OTP 26)
* Elixir Language Server version: ElixirLS v0.17.6
* Operating system: WSL
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name and version: ElixirLS: Elixir support and debugger v0.17.6

### Current behavior

The warnings/errors in vscode don't appear in the correct location.

I didn't see any relevant logs in vscode.

I didn't see anything relevant in the developer tools.

```
[Trace - 6:46:53 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "diagnostics": [
        {
            "message": "variable \"this_is_an_unused_variable\" is unused (if the variable is not meant to be used, prefix it with an underscore)",
            "range": {
                "end": {
                    "character": 29,
                    "line": 1
                },
                "start": {
                    "character": 29,
                    "line": 1
                }
            },
            "severity": 2,
            "source": "Elixir"
        }
    ],
    "uri": "file:///home/tom/work/lang/lib/test.ex",
    "version": 81
}
```

To reproduce, the following elixir file will give a warning for "this_is_an_unused_variable" but will underline "this_is_a_test_function":
```
defmodule Test do
  def this_is_a_test_function(this_is_an_unused_variable) do
  end
end
```

<img width="364" alt="elixir-error" src="https://github.com/elixir-lsp/elixir-ls/assets/203340/1e3a01c1-47cc-48e4-a859-12750733e7e2">

### Expected behavior

It should underline the variable instead of the function.

**Comment by nmk** [comment]
Perhaps also related:

The warning positions are off by 2 for me in 1.15.7 (it seems it is not on the list of supported versions?).

<img width="166" alt="image" src="https://github.com/elixir-lsp/elixir-ls/assets/39269/e215c7b6-abef-44b2-806e-64b7f08bbc13">

```
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:diagnostics
           [(:message "variable \"foo\" is unused (if the variable is not meant to be used, prefix it with an underscore)" :range
                      (:end
                       (:character 1 :line 1)
                       :start
                       (:character 1 :line 1))
                      :severity 2 :source "Elixir")]
           :uri "file:///path/to/test.ex" :version 0))
```

I am using the current master of elixir-ls (commit 0e0ee05).

**Comment by lukaszsamson** [comment]
I can't reproduce this on v0.18-dev (my local branch, not pushed yet) and elixir 1.16-dev (b199896). There were many diagnostic related fixes in both ElixirLS and elixir
<img width="553" alt="Screenshot 2023-12-10 at 21 58 12" src="https://github.com/elixir-lsp/elixir-ls/assets/1078186/e9ea3df3-32ff-4e30-a248-d7bfa398aa91">
<img width="282" alt="Screenshot 2023-12-10 at 22 00 04" src="https://github.com/elixir-lsp/elixir-ls/assets/1078186/ab50fc94-298e-4299-bb91-6240f4577709">
