### ISSUE TITLE
Elixir LS immediately crashes with `badmatch` error

### ISSUE THREAD

**Issue by rpbaptist** [elixir-lsp/elixir-ls#1041]
### Environment

* Elixir & Erlang versions (elixir --version): 
   - `erlang 26.1.2`
   - `elixir 1.15.7-otp-26`
   - ```
     Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1 [jit:ns]
     
     Elixir 1.15.7 (compiled with Erlang/OTP 26)
     ```
* Elixir Language Server version: `0.17.10`
* Operating system: `Ubuntu 23.04`
* Editor or IDE name (e.g. Emacs/VSCode): Neovim/Sublime Text/None
* Editor Plugin/LSP Client name and version:

### Current behavior

When launching `launch.sh` or `language_server.sh` a crash immediately occurs. Both in Neovim, Sublime Text and directly from the command line:

```
❯ ~/.elixir-ls/language_server.sh
Running /home/richard/.elixir-ls/launch.sh
Preferred shell is zsh, relaunching
Looking for ASDF install
ASDF not found
Looking for rtx executable
rtx executable found in /usr/bin/rtx, activating
init terminating in do_boot ({{badmatch,{error,{elixir,{_}}}},[{elixir,start_cli,0,[{_},{_}]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
```

```
❯ ~/.elixir-ls/launch.sh
Preferred shell is zsh, relaunching
Looking for ASDF install
ASDF not found
Looking for rtx executable
rtx executable found in /usr/bin/rtx, activating
init terminating in do_boot ({{badmatch,{error,{elixir,{_}}}},[{elixir,start_cli,0,[{_},{_}]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
```

<!--
ElixirLS logs. If using Visual Studio Code, check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)
-->

<!--
If relevant include VSCode extension logs. Check the developer console by opening `Help > Toggle Developer Tools`.
-->

<!--
If relevant include Language Server Protocol/Debug Adapter Protocol messages trace. In VSCode turn on tracing in Settings > Extensions > ElixirLS > Elixir LS › Trace: Server.
-->

<!--
Reproduction steps. Describe how to reproduce the issue with an empty mix project or post a minimal repo with a project that reproduces the issue.
-->

### Expected behavior

I expect the LS to start.

<!--
A short description on how you expect the language server/debug adapter to behave.
-->

**Comment by lukaszsamson** [comment]
Most likely there's something wrong with either your elixir or OTP install. After rtx activate the launch script attempts to exec an install script via elixir command, and that fails. It looks like your elixir is built for other OTP version than the one that rtx activates

**Comment by rpbaptist** [comment]
Thanks for the hint. After some debugging of the launch script I found the following error:

```
=ERROR REPORT==== 21-Dec-2023::12:23:42.261095 ===
beam/beam_load.c(184): Error loading module 'Elixir.Kernel':
  This BEAM file was compiled for a later version of the runtime system than the current (Erlang/OTP 25).
  To fix this, please re-compile this module with an Erlang/OTP 25 compiler.
  (Use of opcode 182; this emulator supports only up to 180.)
```
  
I am using OTP 26 in my project along with Elixir 1.15.7. I cleaned all my deps and the build. I'm not sure where this OTP 25 complied BEAM file is coming from.

**Comment by lukaszsamson** [comment]
Closing as this is not ElixirLS issue
