### ISSUE TITLE
Undefined function error when installing elixirLS

### ISSUE THREAD

**Issue by baezanat** [elixir-lsp/elixir-ls#1046]
### Environment

* Elixir 1.16.0-otp-26, erlang 26.2.1
* Operating system: Ubuntu 22.04

### Current behavior
Cloned the elixir-ls git repo, ran `mix deps-get` and `mix compile && mix elixir_ls.release -o release`, got the following error:
```
(UndefinedFunctionError) function Mix.Dep.load_on_environment/1 is undefined or private
```

**Comment by lukaszsamson** [comment]
See the response in https://github.com/elixir-lsp/elixir-ls/issues/1044#issuecomment-1870657070

**Comment by baezanat** [comment]
Amazing, thank you @lukaszsamson!
