### ISSUE TITLE
Support envFile to load .env file in project root

### ISSUE THREAD

**Issue by tomwang57** [elixir-lsp/elixir-ls#1051]
Can you please add this option in debugger config which is common and important? Or is there any way to run the debug task as something like: *dotenv mix phx.server*?

> envFile - path to dotenv file with environment variables

**Comment by lukaszsamson** [comment]
BTW the supported way of passing env is via launch config

**Comment by lukaszsamson** [comment]
Closing due to OPs lack of interest
