### ISSUE TITLE
Server start fails in Neovim on Linux with "CaseClausError" in launch.exs

### ISSUE THREAD

**Issue by Odaeus** [elixir-lsp/elixir-ls#1067]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Elixir Language Server version: commit cb5315afca9e624ce1ba1040607d6a154727d8c1
* Operating system: Linux circe 6.5.0-21-generic #21-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 16:14:29 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
* Editor or IDE name (e.g. Emacs/VSCode): Neovim
* Editor Plugin/LSP Client name and version: NVIM 0.9.5

### Current behavior

After upgrading to the latest head of elixir-ls, it no longer starts due to an error.

Running the `launch.fish` script shows the error:

```
[I] @circe ~/s/elixir-ls (master)> ./release/launch.fish
Looking for ASDF install
ASDF install found in /home/andrew/.asdf/asdf.fish, sourcing
Installing ElixirLS release v0.20.0
Running in /home/andrew/src/elixir-ls
Could not find Hex, which is needed to build dependency true
Shall I install Hex? (if running non-interactively, use "mix local.hex --force")
* creating /home/andrew/.asdf/installs/elixir/1.14.0-otp-25/.mix/archives/hex-2.0.6
Install complete
Could not find Hex, which is needed to build dependency true
Shall I install Hex? (if running non-interactively, use "mix local.hex --force")
* creating /home/andrew/.asdf/installs/elixir/1.14.0-otp-25/.mix/archives/hex-2.0.6
** (CaseClauseError) no case clause matching: nil
    release/launch.exs:16: (file)
    (elixir 1.14.0) lib/code.ex:1245: Code.require_file/2
```

There seem to be two issues:
1. Hex is already installed at that path, so I'm not sure why it's attempting to install it again.
2. The `launch.exs` file is expecting the `ELS_MODE` environment variable to be set, but it isn't. I'm not sure where that should come from?

### Expected behavior

The server should start.

**Comment by lukaszsamson** [comment]
1. IIRC somebody already had that hex issue. Have you tried searching the closed issues?
2. Are you using language_server.sh? This script sets ELS_MODE env

**Comment by Odaeus** [comment]
Thanks for the quick reply @lukaszsamson!

No I was using "launch.fish" 😞 . I had the idea that from somewhere that this was the entry point script, particularly as I use the Fish shell - but I suppose in hindsight the neovim-lsp launch process doesn't care what shell Neovim is running in. Thank you for the tip!

As for hex, it is still installing on each start of the language server. I've searched through older tickets more thoroughly but I can't find one complaining about it always re-installing.

It's less important, so I can try to determine what's happening there. According to the LSP server logs that go back several months, this only started happening on 2024-01-30, so something on my system presumably changed at that point.
