### ISSUE TITLE
ElixirLS bootstrapping trying to download a version that don't exists

### ISSUE THREAD

**Issue by andrepaes** [elixir-lsp/elixir-ls#1082]
Hey, i've tried to use elixirLS with nvim 0.9.5 but something weird is happening as it seems the installer.exs is trying to fetch a version that does not exists a release and then it's failling, does anyone experienced something like this?
It's on elixir 1.13.4 and otp 24.3.4.1

![image](https://github.com/elixir-lsp/elixir-ls/assets/12038420/3dcd305c-83bd-45ec-ac6a-953c2dcb7b58)

**Comment by lukaszsamson** [comment]
Please check out a tagged release before running release scripts https://github.com/elixir-lsp/elixir-ls?tab=readme-ov-file#mixinstall-based-release. If you are interested in ElixirLS development or want to run latest master please head to https://github.com/elixir-lsp/elixir-ls/blob/master/DEVELOPMENT.md
