### ISSUE TITLE
Mabye There Is a Memory Leak

### ISSUE THREAD

**Issue by KeepZen** [elixir-lsp/elixir-ls#1089]
### Environment

* Elixir & Erlang versions (elixir --version):Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] Elixir 1.16.2 
* Elixir Language Server version: 0.21.0
* Operating system: Ubuntu
* Editor or IDE name (e.g. Emacs/VSCode): VSCode 

### Current behavior

There is a memory leak in Elixir Language Server.
![The Memory use status](https://github.com/elixir-lsp/elixir-ls/assets/43458238/987a61fb-96bf-45a9-8072-89a73ca117b3)

After I close the VSCode or disable the plug the memory will drop very sharp.

**Comment by lukaszsamson** [comment]
Can you check if your issue is actually the same as https://github.com/elixir-lsp/vscode-elixir-ls/issues/417? If this is something else please use those steps to diagnose memory usage https://github.com/elixir-lsp/vscode-elixir-ls/issues/417#issuecomment-2097509466

**Comment by lukaszsamson** [comment]
BTW v0.21.1 with fix for `use` problem has been released

**Comment by KeepZen** [comment]
I checked it is same as #417, may be it about the phoenix, I work on a phoenix too.

**Comment by lukaszsamson** [comment]
Closing this for now. The underlying issues were most likely fixed
