### ISSUE TITLE
Spark plugin is not being called as of `0.21`

### ISSUE THREAD

**Issue by zachdaniel** [elixir-lsp/elixir-ls#1091]
There is a note in the changelog about changes to plugins that could potentially break things, but I'm not having any luck tracking down why the Spark plugin isn't called anymore.  I'm more than happy to fix it, but as far as I can tell the plugin still meets the criteria for being a plugin. Does anyone have an idea of where I should be looking to track things down?

**Comment by zachdaniel** [comment]
Fixed in the plugin. To see what I had to change: https://github.com/ash-project/spark/commit/f083cb45734fffdc579db084275dfd308b387af4

Keep in mind its more complex as I'm retaining backwards compatibility for users that haven't upgraded elixir-ls

**Comment by lukaszsamson** [comment]
Oh, sorry about the breakage

**Comment by zachdaniel** [comment]
All good, it's good changes to bring things under elixir-ls, I'll adapt to future changes as necessary as well 👍
