### ISSUE TITLE
"Go to Definition" and Elixir debugging cannot enter modules bundled with Elixir

### ISSUE THREAD

**Issue by weaversam8** [elixir-lsp/elixir-ls#1098]
### Environment

* Elixir `1.17.0-rc.1` (via asdf)
* Erlang/OTP `25.2` (via asdf)
* Elixir Language Server version: `v0.21.3`
* Operating system: macOS Sonoma `14.4.1`
* Editor or IDE name (e.g. Emacs/VSCode): VSCode `1.89.0`
* Editor Plugin/LSP Client name and version: `jakebecker.elixir-ls` for VSCode, version `v0.21.3` 

### Current behavior

"Go to Definition" for modules built into Elixir does not work. Right clicking on a function such as `Keyword.get(...)`, or `OptionParser.parse!(...)` and selecting "Go to Definition" displays "No definition found for <function name>".

**ElixirLS logs (output window):**
None relevant.

**VSCode extension logs (developer tools):**
None relevant.

**VSCode LSP Protocol messages trace:**
```
[Trace - 10:50:03 AM] Sending request 'textDocument/definition - (10610)'.
Params: {
    "textDocument": {
        "uri": "file:///REDACTED.ex"
    },
    "position": {
        "line": 31,
        "character": 26
    }
}


[Trace - 10:50:03 AM] Received response 'textDocument/definition - (10610)' in 469ms.
No result returned.
```

#### Reproduction steps:

1. Run `mix new <project name>`
2. Open the new project in VS Code
3. Open `mix.exs`
4. Right click on `Mix.Project` and select "Go to Definition"

### Expected behavior

Other language servers (such as the [Python extension for VS Code][python-vscode]) support both "Go to Definition" and "step-into" debugging into functions in the standard library. It would be great to have that for Elixir too.

[python-vscode]: https://marketplace.visualstudio.com/items?itemName=ms-python.python

**Comment by lukaszsamson** [comment]
It does work if the source is available on your machine. How did you install elixir and OTP? Please diagnose if source files are available under paths returned by
```
Kernel.module_info(:compile)[:source] |> Path.join("..") |> Path.expand
```
and
```
:code.get_object_code(:lists) |> elem(2) |> Path.join("../../src") |> Path.expand
```

**Comment by weaversam8** [comment]
Ah, the output of that first command was `/home/runner/work/elixir/elixir/lib/elixir/lib`, which doesn't exist on my system. I installed Elixir using [asdf-elixir](https://github.com/asdf-vm/asdf-elixir), using a precompiled version, which may have been my mistake.

By running the following commands, I was able to build Elixir from source, at which point the source files on my system were listed when running that `Kernel.module_info...` command.

```sh
asdf shell erlang 25.2 # or your preferred erlang version
asdf install elixir ref:v1.17.0-rc.1 # or your preferred elixir version
asdf local elixir ref:v1.17.0-rc.1
```

"Go to Definition" works now, but **"step into" debugging still won't "step into" the standard library when I try to do that.** Is that on-topic for this repository, or should I open that on [vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls)?

(Thanks for the help with the first issue!)

**Comment by lukaszsamson** [comment]
> "step into" debugging still won't "step into" the standard library when I try to do that

That's not supported. Debug adapter is built on top of standard library. Some not critical modules may work but in general breaking in `Kernel`, `Enum` or any base OTP app will deadlock the VM
