### ISSUE TITLE
Non standard expandMacro request

### ISSUE THREAD

**Issue by rodrigues** [elixir-lsp/elixir-ls#11]
Comparing this fork with Jake's master, I've found this: https://github.com/JakeBecker/elixir-ls/commit/643bb3191d8fb7b8490a505ee3ebe71e2c5f4a4f

Is this still conformant to the language server protocol?

In the [specification](https://microsoft.github.io/language-server-protocol/specification), if you search for `interface ServerCapabilities`, the allowed keys seems to be a very strict set, I'm not sure if adding macro expansion is valid.

Maybe that's the case for a code action instead?

Thanks!

**Comment by axelson** [comment]
It's still intending to be conformant to the language server protocol. Do you know of a way to register a new custom capability from the server?

**Comment by rodrigues** [comment]
@axelson it seems to me that [code actions](
https://microsoft.github.io/language-server-protocol/specification#textDocument_codeAction) are the way to go
