### ISSUE TITLE
typespecs do not work for implemented behaviour functions

### ISSUE THREAD

**Issue by pauldemarco** [elixir-lsp/elixir-ls#1102]
### Environment

* Elixir & Erlang versions (elixir --version): 1.17.0 0.27
* Elixir Language Server version: v0.22.0
* Operating system: Ubuntu
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name and version:

### Current behavior

There is no autocomplete for function arguments that are keywords. This applies to Modules that implement a behaviour function and have their own typespec.

## Reproduction steps:
This is our goal -- notice how autocomplete works with GenServer's start_link options:
![image](https://github.com/elixir-lsp/elixir-ls/assets/16725750/741b6562-80c9-40e1-97ec-01a086aa51c8)

Let's try to recreate this awesomeness with our own Module:
1. Now, define a behaviour that has a @callback method with an options (keyword) argument.
1. Use the behaviour in a Module with `@behaviour MyBehaviour`.
1. Implement the function and add the typespec for the options.
1. Now in a calling function, try to use the method, and notice there is no autocomplete as it bypasses the Module's typespec and gives you the Behaviours definition.

**Comment by lukaszsamson** [comment]
The reason for what you observe is there are 2 separate mechanisms generating completions. One is used for remote functions and the other for local buffer completions. The remote one relies on compiled beams - it extracts info from EEP48 doc chunks and typespec chunks. The local one relies on AST analysis. Keyword argument completions are only implemented for remote typespec (as returned by Code.Typespec.fetch_specs internal elixir API). We would need something similar that extracts keyword lists from typespec AST in current buffer.
Side note: typespecs are going to be deprecated in elixir and replaced with typesystem. There is a plan for typesystem to handle keyword lists but it most likely will not land soon

**Comment by pauldemarco** [comment]
Thanks for the clarification. Looking forward to the typesystem!

**Comment by lukaszsamson** [comment]
Keyword list completions from the current buffer are already tracked in https://github.com/elixir-lsp/elixir-ls/issues/1070
