### ISSUE TITLE
 `elixir-ls` does not start because of "incomplete" installation

### ISSUE THREAD

**Issue by cassepipe** [elixir-lsp/elixir-ls#1104]
### Precheck
Seems related : 
- https://github.com/elixir-lsp/elixir-ls/issues/783
- 

### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 26 [erts-14.2.5.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.16.2 (compiled with Erlang/OTP 26)
```
* Elixir Language Server version:   `0.22.0` (latest version at the time of writing)
* Operating system: Fedora 40 (all packages up to date)
* Editor: LunarVim Release branch (Neovim distribution) 
* Editor Plugin/LSP Client name and version:
  `elixir-ls` package from `Mason` plugin that maintains its own registry [https://mason-registry.dev/registry/list#elixir-ls]
   (latest version at the time of writing)

## Description 

`elixir-ls` does not start because of "incomplete" installation. (link)[ https://github.com/elixir-lsp/elixir-ls/blob/master/guides/incomplete-installation.md] given in error message is a 404.
A bit of research in github issues and elixir foroum suggests the issue is erlang OTP version 26 :

## Steps
 
1. Install Lunarvim :
```
LV_BRANCH='release-1.4/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.4/neovim-0.9/utils/installer/install.sh)
```
2. Run `lvim`
3. Press `Escape`
4. Type `:LspInstall elxirls` then Enter
5. Press `Escape` again
6. Type `:LvimCacheReset`

You should see the following error and "LSP Inactive" in the status bar :
```
LSP[elixirls] Unable to start ElixirLS due to an incomplete erlang installation. See https://github.com/elixir-lsp/elixir-ls/blob/master/guides/incomplete-installation.md for guidance.
```

**Comment by cassepipe** [comment]
Installing the `erlang` package explicitly with 
```
sudo dnf install erlang
```
solves it

**Comment by lukaszsamson** [comment]
The link should not 404

**Comment by cassepipe** [comment]
It doesn't 404 anymore. Maybe opening the link from Lunarvim was corrupting the link  ?

**Comment by lukaszsamson** [comment]
I confirm the link is correct
