### ISSUE TITLE
ElixirLS breaks after ash dep update

### ISSUE THREAD

**Issue by ken-kost** [elixir-lsp/elixir-ls#1108]
### Environment

* Elixir & Erlang versions (elixir --version): 1.17
* Elixir Language Server version: 0.22
* Operating system:  Windows/WSL
* Editor or IDE name (e.g. Emacs/VSCode):  VSCode

### Current behavior
After I updated ash dep from 3.0 to 3.1 I got error in mix:
```
an exception was raised:
    ** (Mix.Error) Can't continue due to errors on dependencies
        (mix 1.17.1) lib/mix.ex:588: Mix.raise/2
        (mix 1.17.1) lib/mix/tasks/deps.loadpaths.ex:48: Mix.Tasks.Deps.Loadpaths.run/1
        (mix 1.17.1) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
        (mix 1.17.1) lib/mix/tasks/loadpaths.ex:37: Mix.Tasks.Loadpaths.run/1
        (mix 1.17.1) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
        (mix 1.17.1) lib/mix/tasks/compile.ex:153: Mix.Tasks.Compile.run/1
        (mix 1.17.1) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
        (language_server 0.22.0) lib/language_server/build.ex:442: ElixirLS.LanguageServer.Build.run_mix_compile/1
        (language_server 0.22.0) lib/language_server/build.ex:80: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3
        (stdlib 6.0) timer.erl:590: :timer.tc/2
        (language_server 0.22.0) lib/language_server/build.ex:20: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3
        (kernel 10.0) global.erl:699: :global.trans/4Elixir
```

**Comment by lukaszsamson** [comment]
Is it the right place to report? Probably ash support channels are better in this case. Do you have a small repo that reproduces it?

**Comment by ken-kost** [comment]
I don't but it should be easy to reproduce. Okay, I'll close the issue then, thanks for the feeback.

**Comment by zachdaniel** [comment]
To be clear, I'm pretty positive this has nothing to do with Ash at all. Deleting the `.elixir_ls` directory tends to fix this kind of issue, and it can happen on any dependency change.

**Comment by ken-kost** [comment]
yep, my bad

**Comment by lukaszsamson** [comment]
It's notoriously hard to reset mix and app controller state without restarting the os process. AFAIK it affects all elixir language servers to some extent. Do you happen to have a reliable repro? I fixed a few similar issues in the last years

**Comment by zachdaniel** [comment]
I don't have a reproduction unfortunately 😢 I think it is both transient and timing related. The only things I've noticed so far is that it seems to happen more with bigger dependencies/bigger upgrades, and it doesn't always happen.

**Comment by lukaszsamson** [comment]
Yep, switching branches in bigger projects with > 20 deps triggers various bugs in mix and hex. Just today I was able to trigger corrupted hex cache from the command line only
