### ISSUE TITLE
Code expanding/folding in heex files not working when the "Phoenix Framework" extension is installed

### ISSUE THREAD

**Issue by CharlesIrvineKC** [elixir-lsp/elixir-ls#1111]
If I have "Phoenix Framework" extension installed in vscode, I lose the ability to collapse and expand sections of code.

![no_folding](https://github.com/user-attachments/assets/2c849441-0bc6-465e-ab53-ff90472b2c67)

If I disable "Phoenix Framework" then collapsing and expanding works as expected.

![vscode_folding](https://github.com/user-attachments/assets/8b0d45e4-14fc-4629-9de4-1cc7e96b551b)

I

**Comment by lukaszsamson** [comment]
Please report it to the right repo https://github.com/phoenixframework/vscode-phoenix
