### ISSUE TITLE
Is it possible to suppress INFO messages using an app-specific environment variable?

### ISSUE THREAD

**Issue by florinpatrascu** [elixir-lsp/elixir-ls#1115]
Hi there,

Is there an environment variable we can use to set the logger level to error or something else? I'm trying to suppress these messages:

```
 ...[INFO] Language server with id 2 sent unhandled notification telemetry/event
```
and any other INFO messages, if possible. 

Thank you.

**Comment by lukaszsamson** [comment]
This log comes from your editor, not from ElixirLS

**Comment by florinpatrascu** [comment]
Not quite, I believe. In this instance, Zed does honor the `RUST_LOG` environment variable, and I can observe its influence in the logs. The errors mentioned above begin to occur when I use the elixir-ls server, so if I'm not mistaken I believe these logs belonged to this elixir-ls.

**Comment by lukaszsamson** [comment]
You are mistaken. The log is originating in the editor. It's complaining that it does not support [this LSP notification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#telemetry_event)

**Comment by florinpatrascu** [comment]
You're correct, and I apologize for the oversight. Additionally, I've discovered that the bootstrapping of the server extensions is not respecting the `RUST_LOG` environment variable. Sorry for any confusion caused.
