### ISSUE TITLE
Little troubleshoot for nvim users who want to debug.

### ISSUE THREAD

**Issue by bus710** [elixir-lsp/elixir-ls#1117]
### Goal

I just want to share my success story with others.

### Environment

* Elixir & Erlang versions (elixir --version): `OTP 1.17`
* Elixir Language Server version: `0.23.0`
* Operating system: `Debian Testing`
* Editor or IDE name (e.g. Emacs/VSCode): `AstroNvim v4` 
* Editor Plugin/LSP Client name and version: `nvim-dap`?

### Current behavior

- I was trying to set up the debugger within AstroNvim.
- The nvim-dap repo has a good example.
- Things didn't work for the first shot, but I was able to make it by:
  - Copy the VERSION file of elixir-ls in the scripts directory.
  - Run the launch.sh and wait until it ends.
  - Try debugging in nvim.    

### Expected behavior

Nothing expected, but the doc can tell that nvim users might want to do the steps I needed to do?

**Comment by lukaszsamson** [comment]
You should run release script instead of manually managing VERSION. You should also use debug_adapter.sh as executable. This is what VSCode does

**Comment by bus710** [comment]
@lukaszsamson 
Thanks for your comment!
I guess I overlooked this [part](https://github.com/elixir-lsp/elixir-ls#local-setup) if that is what the release script means. 

Hope this PR can be helpful for other nvim users. 
Let me close it.
