### ISSUE TITLE
Autocompleting local macros shouldn't require the current module

### ISSUE THREAD

**Issue by sabiwara** [elixir-lsp/elixir-ls#1129]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.17.3 (compiled with Erlang/OTP 27)
* Elixir Language Server version: v0.24.2
* Operating system: MacOS
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name and version:

### Current behavior

```elixir
defmodule Foo do
  defmacro foo(ast), do: ast

  def bar do
    fo<autocomplete>
  end
end
```

adds `require Foo` at the top of `Foo`.

### Expected behavior

No require for local `defmacro`s.

Will send a tentative PR.

**Comment by lukaszsamson** [comment]
Fixed in https://github.com/elixir-lsp/elixir-ls/pull/1130
