### ISSUE TITLE
How can I contribute to elixir-ls?

### ISSUE THREAD

**Issue by mazz-seven** [elixir-lsp/elixir-ls#113]
Hey, 
I want to try to contribute to the effort. What is the right setup and flow to work on the LS? 

I'm using VScode. 

Thanks 
Mazz

**Comment by axelson** [comment]
Hi @mazz-seven, the setup to contribute to ElixirLS when using VSCode is described in 
https://github.com/elixir-lsp/vscode-elixir-ls/#contributing

Please let me know if those instructions are working for you. Glad to have any contributors!

**Comment by mazz-seven** [comment]
They are helpful. Thank you.
Also, I'm trying to understand why sometimes I'm not getting auto complete for a module methods. What is the right way to debug such case?

**Comment by axelson** [comment]
The best way to debug the issue would be to go to the module settings and set `Elixir LS > Trace: Server` to either "messages" or "verbose" which will show you information about the messages sent back and forth between the client and server.

Once you know that it is an issue with the server and you know the scenario that reproduces it you can create a PR either directly in elixir-ls, or very possibly in https://github.com/elixir-lsp/elixir_sense/ that reproduces the issue (and ideally fixes it!)
