### ISSUE TITLE
Broken link on README.md

### ISSUE THREAD

**Issue by lbellomo** [elixir-lsp/elixir-ls#1132]
This link `http://erlang.2086793.n4.nabble.com/OTP-Versions-and-Maint-Branches-td4722416.html` in this line in the [readme](https://github.com/elixir-lsp/elixir-ls/blob/178506437f18f3cfbb55a5d42d54c061ba80dd13/README.md?plain=1#L104C1-L104C83)  on the "Supported Elixir and OTP versions" section is broken.

**Comment by lukaszsamson** [comment]
It should point to https://www.erlang.org/doc/system/misc.html. This policy is not very strict but it seems that bugs are in general only fixed on the latest release, and new features are introduced in the upcoming release. In practice, small improvements are regularly added to the latest release, and major bug and security fixes are backported to the supported previous releases.

**Comment by lbellomo** [comment]
Thanks! I will try to fix in a PR.
