### ISSUE TITLE
Go to definition not working on neovim

### ISSUE THREAD

**Issue by crisdegraciadev** [elixir-lsp/elixir-ls#1138]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit] - Elixir 1.17.1 (compiled with Erlang/OTP 27) 
* Elixir Language Server version: 0.24.1
* Operating system: MacOS 15
* Editor or IDE name (e.g. Emacs/VSCode): Neovim
* Editor Plugin/LSP Client name and version: ElixirLS 0.24.1

### Current behavior

With my current LSP configuration, I'm unable to make work "go to definition".

```bash
      lspconfig.elixirls.setup({
        capabilities = capabilities,
        cmd = { "/Users/cristian.degracia/elixir-ls-v0.24.1/language_server.sh" },
      })

      vim.keymap.set("n", "gd", vim.lsp.buf.definition, {})
``` 

It's working for others languages like javascript, but I have tried everithing and it seems to not be called for elixir LSP

Here are the LSP logs, but it doesn't look relevant

```bash
[START][2024-12-05 18:38:41] LSP logging initiated
[ERROR][2024-12-05 18:38:41] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/cristian.degracia/elixir-ls-v0.24.1/language_server.sh"	"stderr"	"Running /Users/cristian.degracia/elixir-ls-v0.24.1/launch.sh\nPreferred shell is zsh, relaunching\nLooking for ASDF install\nASDF install found in /opt/homebrew/opt/asdf/libexec/asdf.sh, sourcing\n"
[ERROR][2024-12-05 18:38:42] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/cristian.degracia/elixir-ls-v0.24.1/language_server.sh"	"stderr"	"Installing ElixirLS release v0.24.1\n"
[ERROR][2024-12-05 18:38:42] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/cristian.degracia/elixir-ls-v0.24.1/language_server.sh"	"stderr"	"Running in /Users/cristian.degracia/Projects/personal/learning_elixir\n"
[ERROR][2024-12-05 18:38:42] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/cristian.degracia/elixir-ls-v0.24.1/language_server.sh"	"stderr"	"Install complete\n"

```

### Expected behavior

When pressing my keymap (gd) just make it work

**Comment by lukaszsamson** [comment]
This does not look like ElixirLS problem. Please use forum/slack/discord for support on editor config. I'm going to close this.
