### ISSUE TITLE
asdf does not support sh

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#114]
David Sweeney in this [Elixir Forum post](https://elixirforum.com/t/emacs-elixir-setup-configuration-wiki/19196/157) recently discovered the issue that our `language_server.sh` is no longer sh compatible because `asdf` (added in https://github.com/elixir-lsp/elixir-ls/pull/78) is not currently sh compatible.

The error manifests itself with an error like:
`/home/my_home/.asdf/asdf.sh: 8: /home/my_home/.asdf/asdf.sh: Bad substitution`

I have raised an [issue on asdf](https://github.com/asdf-vm/asdf/issues/653) to determine if asdf is meant to support sh/dash, or only bash and other shells.

I see a few possible ways forward but would like to collect other's thoughts about them:

1. Change `language_server.sh` to run bash instead of sh (via `#!/usr/bin/env bash`)
2. Revert #78 
3. Wait for asdf to support sh

I'm currently leaning towards option 1 because bash is very widespread at this point and I'd imagine most systems will have it and for any that don't, the user will most likely understand how to fix the error.

**Comment by Trevoke** [comment]
I think it's fine to require `bash` on a system running `elixir-ls` --- `sh` compatibility is desirable, but not a need for us. As you said, `bash` is pretty much today's `sh`.

**Comment by axelson** [comment]
Agreed
