### ISSUE TITLE
elixir-ls installer using a not-yet existent function when used with an older elixir version

### ISSUE THREAD

**Issue by dice-dominik** [elixir-lsp/elixir-ls#1141]
### Environment

* Elixir & Erlang versions (elixir --version): 
Erlang/OTP 24 [erts-12.3.2.13] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1]

Elixir 1.13.4 (compiled with Erlang/OTP 24) - installed with ASDF

* Elixir Language Server version: 
v0.24.1
* Operating system:
Sonoma 14.6.1 
* Editor or IDE name (e.g. Emacs/VSCode): 
nvim
* Editor Plugin/LSP Client name and version:
elixirls installed with Mason

### Current behavior

It looks like elixir-ls installer is trying to use functions from elixir from the version not installed on my machine. Jumping to definitions doesn't work and the lsp logs are as follows:
```
[ERROR][2024-12-13 10:55:16] .../vim/lsp/rpc.lua:734	"rpc"	"elixir-ls"	"stderr"	"Running /Users/dominikstanaszek/.local/share/lvim/mason/packages/elixir-ls/launch.sh\n"
[ERROR][2024-12-13 10:55:16] .../vim/lsp/rpc.lua:734	"rpc"	"elixir-ls"	"stderr"	"Preferred shell is bash, relaunching\n"
[ERROR][2024-12-13 10:55:16] .../vim/lsp/rpc.lua:734	"rpc"	"elixir-ls"	"stderr"	"Looking for ASDF install\n"
[ERROR][2024-12-13 10:55:16] .../vim/lsp/rpc.lua:734	"rpc"	"elixir-ls"	"stderr"	"ASDF install found in /opt/homebrew/opt/asdf/libexec/asdf.sh, sourcing\n"
[ERROR][2024-12-13 10:55:16] .../vim/lsp/rpc.lua:734	"rpc"	"elixir-ls"	"stderr"	"Installing ElixirLS release v0.24.1\n"
[ERROR][2024-12-13 10:55:16] .../vim/lsp/rpc.lua:734	"rpc"	"elixir-ls"	"stderr"	"Running in /Users/<<HOME>>/<<PROJECT PATH>>\n"
[ERROR][2024-12-13 10:55:16] .../vim/lsp/rpc.lua:734	"rpc"	"elixir-ls"	"stderr"	'Could not find Hex, which is needed to build dependency true\nShall I install Hex? (if running non-interactively, use "mix local.hex --force")\n'
[ERROR][2024-12-13 10:55:18] .../vim/lsp/rpc.lua:734	"rpc"	"elixir-ls"	"stderr"	"* creating /Users/<<HOME>>/.asdf/installs/elixir/1.13.4-otp-24/.mix/archives/hex-2.1.1\n"
[ERROR][2024-12-13 10:55:18] .../vim/lsp/rpc.lua:734	"rpc"	"elixir-ls"	"stderr"	"Install complete\n"
[ERROR][2024-12-13 10:55:18] .../vim/lsp/rpc.lua:734	"rpc"	"elixir-ls"	"stderr"	"warning: Mix.Dep.Lock.read/1 is undefined or private. Did you mean:\n\n      * read/0\n\nInvalid call found at 2 locations:\n  /Users/<<HOME>>/.local/share/lvim/mason/packages/elixir-ls/installer.exs:356: ElixirLS.Mix.install/2\n  /Users/<<HOME>>/.local/share/lvim/mason/packages/elixir-ls/installer.exs:357: ElixirLS.Mix.install/2\n\n"
```

`Mix.Dep.Lock.read/1` has been added to elixir after the version I am using, I might be missing something but shouldn't the installer work in a backwards compatible manner? Are there different installer versions and in my case the wrong one has been chosen?

### Expected behavior

The installation should be successful

**Comment by lukaszsamson** [comment]
You right, `Mix.Dep.Lock.read/1` has been added in 1.14. It's strange that it was not noticed until now. The installer has been used for almost two years. Would you like to raise a PR? Elixir 1.13 is near EoL and support such an old version is not my top priority.

**Comment by lukaszsamson** [comment]
Note the code is only executed if there is something wrong with your mix install dir and lockfile MD5 diverges. https://github.com/elixir-lang/elixir/blob/7df646d960c3cc9a4590861a87245d9c44f7fbc4/lib/mix/lib/mix.ex#L768
Maybe you need to cleanup your mix install dir
