### ISSUE TITLE
metadata in completions can include some very ugly dumped values when function has non-standard metadata such as spark_opts

### ISSUE THREAD

**Issue by jsw800** [elixir-lsp/elixir-ls#1142]
### Environment

* Elixir & Erlang versions (elixir --version): 1.17.1
* Elixir Language Server version: v0.25.0
* Operating system: MacOS 15.1.1 (running vscode in a devcontainer based off of mcr.microsoft.com/vscode/devcontainers/base:bookworm)
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name and version: 

### Current behavior

When viewing docs for a function by hovering over an existing function call in the code editor, `@doc` metadata is being rendered before the other docs. This is probably sensible in most scenarios. However, some libraries (such as spark/ash) use doc metadata internally in a way that makes this pretty rough in terms of usability. Specifically, spark/ash attaches a `spark_opts` metadata value to docs that they use internally to support nice opt autocompletion. However, this ends up getting rendered into the doc autocompletion which makes for a pretty rough experience when viewing docs for functions defined by ash/spark (as this doc metadata is not really meant for users to see).

Interestingly, it seems like the behavior is somewhat inconsistent based on how you access the autocomplete - for example if you instead view the autocomplete by typing out the beginning of the function name and navigate to it via arrow keys, the displayed autocomplete shows the metadata _after_ the main docs block. I still don't really _want_ to see that gross `spark_opts` value, but this is an improvement over the hover autocomplete since the ugly metadata is at least pushed to the bottom of the view.

#### Repro steps

You can reproduce this by creating an ash project with a resource with a [code interface](https://hexdocs.pm/ash/code-interfaces.html), but the easier way to repro this is simply to define a function in a module with something like this:

```elixir
defmodule SomeModule do
  @doc "Some description"
  @doc spark_opts: [some: :big, ugly: :thing, that: :nobody, actually: :wants, to: :see]
  def thing() do
    nil
  end
end
```

Then write a call to that function, e.g.

```
SomeModule.thing()
```

and hover over `thing` with the mouse. Notice that the autocomplete shows `spark_opts: [some: :big, ugly: :thing, that: :nobody, actually: :wants, to: :see]` right at the top of the docs.

### Expected behavior

There's a lot of potential ways the experience could be improved here, each with their own pros and cons, here are some ideas:

- Make different autcomplete methods consistent by always putting doc metadata _after_ the main doc block. This would only partially solve the problem of dumping ugly `spark_opts` metadata into autocompletes, but would be a definite improvement from my perspective. As an argument against this though, it may be the case that doc metadata _does_ belong at the top, for example deprecation notices, etc. are nice to display loudly at the top of a doc, so this may not be the best approach.
- change the function head at https://github.com/elixir-lsp/elixir-ls/blob/master/apps/language_server/lib/language_server/markdown_utils.ex#L145 to _not_ render unknown metadata values. This might be undesirable if users _do_ expect those values to show up in autocompletes though.
- add a function head to the above function to specifically disable rendering for `spark_opts`. This seems viable as that atom is unlikely to be used for any purpose other than this, however I totally get that hard coding edge cases for specific libraries may be... suboptimal 😅 

Open to other potential solutions here as well!

cc @zachdaniel

**Comment by zachdaniel** [comment]
Another option would be to only render metadata that is a keyword list of atom keys to string values? `spark_opts` looks like `key: [...spec], other_key: [...other_spec]`.

Or putting docs metadata that would be longer than a certain length at the bottom?

**Comment by lukaszsamson** [comment]
The easiest fix would be to add a filter in https://github.com/elixir-lsp/elixir-ls/blob/6d7abda5b972ac019c7685763862694285d153b4/apps/language_server/lib/language_server/markdown_utils.ex#L59. Some metadata keys are already excluded from rendering in docs

**Comment by jsw800** [comment]
@lukaszsamson OK sweet! Just submitted a PR [here](https://github.com/elixir-lsp/elixir-ls/pull/1143)
