### ISSUE TITLE
ElixirLS won't start on new macbook.  Content-Length header missing

### ISSUE THREAD

**Issue by jeramyRR** [elixir-lsp/elixir-ls#1148]
Hi all,

I'm having problems getting ElixirLS to work on a new Macbook.  I keep getting client errors complaining about content-length headers missing and a whole bunch of gibberish.  Looks like telemetry data (which I have turned off in settings). 

The following logs in the `Current Behavior` settings are as far as I can get with the plugin.

### Environment

* Elixir & Erlang versions (elixir --version): happens with both Elixir 1.17.3-otp-27 and 1.18.0-otp-27
* Elixir Language Server version: 0.24 and 0.25
* Operating system: macOS
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name and version: jakebecker.elixir-ls

### Current behavior

Client ElixirLS - webapp: connection to server is erroring.
Header must provide a Content-Length property.
{"                     ..'\n                 ,xnmm.\n               .ommmmo\n               lmm\"\n     .;loddo":".  .olloddol;.\n   cKMMMMMMMMMMNWMMMMMMMMMM0:\n .KMMMMMMMMMMMMMMMMMMMMMMMWd.\n XMMMMMMMMMMMMMMMMMMMMMMMX.\n;MMMMMMMMMMMMMMMMMMMMMMMM:\n:MMMMMMMMMMMMMMMMMMMMMMMM:\n.MMMMMMMMMMMMMMMMMMMMMMMMX.\n kMMMMMMMMMMMMMMMMMMMMMMMMWd.\n 'XMMMMMMMMMMMMMMMMMMMMMMMMMMk\n  'XMMMMMMMMMMMMMMMMMMMMMMMMK.\n    kMMMMMMMMMMMMMMMMMMMMMMd\n     ;KMMMMMMMWXXWMMMMMMMk.\n       \"cooc*\"    \"*coo'\"\u001b[1G\u001b[16A\u001b[34Cjeramy@Jeramys-MacBook-Pro-2\n\u001b[34C----------------------------\n\u001b[34COS: macOS Sequoia 15.2 arm64\n\u001b[34CHost: MacBook Pro 

...
Shutting down server.
Error: Client is not running and can't be stopped. It's current state is: starting

**Comment by lukaszsamson** [comment]
The startup script must not output to stdout and read from stdin. If your shell config makes it write to stdout it will corrupt LSP messages and client will close the connection

**Comment by lukaszsamson** [comment]
You are comparing compiled languages that probably build a self contained binary. In a binary there is a full control over stdio. Contrary to those, elixir is not compiled and needs startup shell scripts. Even `elixir` and `erl` are shell scripts. If the shell script does not behave it breaks LSP communication.

It is still possible to use sockets for communication but that is not implemented in ElixirLS.

References:

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#baseProtocol

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#implementationConsiderations
