### ISSUE TITLE
Bug: function nil.text/0 is undefined exception

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#12]
Got this exception today, not sure how to reproduce yet. Also not sure about the input that caused this.

```
09:45:52.252 [error] Process #PID<0.5762.0> raised an exception
** (UndefinedFunctionError) function nil.text/0 is undefined
    nil.text()
    (language_server) lib/language_server/server.ex:345: anonymous fn/4 in ElixirLS.LanguageServer.Server.handle_request/2
    (language_server) lib/language_server/server.ex:419: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
```

**Comment by asummers** [comment]
Seems like that comes from https://github.com/elixir-lsp/elixir-ls/blob/master/apps/language_server/lib/language_server/server.ex#L345

My guess is you removed a file/function for that particular `uri` and it is not robust enough to deal with that.

**Comment by axelson** [comment]
Yeah, that does seem like it

**Comment by axelson** [comment]
More info: I think this happens when you rename a file.

**Comment by lukaszsamson** [comment]
@axelson I think we should add a simple `try` around `handle_request` to avoid crashing the process. It's not worth trying to fix this edge case

**Comment by axelson** [comment]
Possibly, although if we could reliably reproduce this in different editors (i.e. we're not handling valid LSP operations) than I think it would probably be worth a more proper fix. But some more investigation is needed first.
