### ISSUE TITLE
Feature: Navigate from defdelegate to the function delegated to

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#126]
May require changes to elixir_sense

**Comment by lukaszsamson** [comment]
It will require changes in elixir sense. I was planning to do this anyway though.

**Comment by axelson** [comment]
That sounds good, I created an issue in the elixir_sense repo as well: https://github.com/elixir-lsp/elixir_sense/issues/89

**Comment by wanton7** [comment]
I created issue #132 and is it really duplicate to this? I thought this was just about that you could navigate from `defdelegate` to function it points to by going over `defdelegate` and pressing F12? Or would this actually forward everything like *Peek Definition* to actually code instead?

**Comment by giddie** [comment]
It seems if I'm at the `defdelegate` site, I need to jump back to the call site and do go-to-implementation to jump through the delegation. Is there a way to jump directly from the delegation to the implementation without jumping back to the call site?

Also, it seems that listing references doesn't work from the function implementation (i.e. the target of the delegation). I'd expect that it would list the `defdelegate` call(s) as references. Should I be doing something differently, or is this not available yet?

**Comment by lukaszsamson** [comment]
> It seems if I'm at the defdelegate site, I need to jump back to the call site and do go-to-implementation to jump through the delegation. Is there a way to jump directly from the delegation to the implementation without jumping back to the call site?

You can use go to implementations on the defdelegate site, no need to jump back to call site (I've just verified it and it works for me)

> Also, it seems that listing references doesn't work from the function implementation (i.e. the target of the delegation). I'd expect that it would list the defdelegate call(s) as references. Should I be doing something differently, or is this not available yet?

That's a separate issue. Please fill it in elixir_sense repo

**Comment by giddie** [comment]
> You can use go to implementations on the defdelegate site, no need to jump back to call site (I've just verified it and it works for me)

Ah! OK, I've traced my issue here to an issue with alias resolution:

```elixir
# lib/test.ex
defmodule Test do
  alias __MODULE__, as: Self
  alias Self.Private

  defdelegate my_function(), to: Private
end

# lib/test/private.ex
defmodule Test.Private do
  def my_function() do
    IO.puts("Hello")
  end
end
```

It seems that the double-alias involving `__MODULE__` breaks resolution, which breaks jump-to-implementation as a side-effect. Where should I report this? Does it go to elixir_sense?

**Comment by lukaszsamson** [comment]
> Where should I report this? Does it go to elixir_sense?

Yes. If you would like to try adding support for it, the relevant code is in https://github.com/elixir-lsp/elixir_sense/blob/219b4d0fcb27c46dd4dad915ece01ec2b92d0249/lib/elixir_sense/core/metadata_builder.ex#L705
