### ISSUE TITLE
Extremely slow response times for Ecto call generating 700+ obs

### ISSUE THREAD

**Issue by ctataryn** [elixir-lsp/elixir-ls#145]
### Environment

* Elixir & Erlang versions (elixir --version): 

```
elixir --version
Erlang/OTP 22 [erts-10.5] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]
Elixir 1.9.4 (compiled with Erlang/OTP 20)
```

* Operating system: 
`Windows 10`

* Editor or IDE name (e.g. Emacs/VSCode): 

`VSCode`

* LSP Client name: 

`ElixirLS Fork: Elixir support and debugger`

### Problem

I have one api call that uses this function in my app:

```
  def list(org_id, app_id, cr_id, filters \\ %{}) do
    from(c in Change,
      join: cr in assoc(c, :change_request),
      where: cr.id == ^cr_id,
      where: cr.application_id == ^app_id,
      where: cr.organization_id == ^org_id
    )
    |> add_filters(filters)
    |> preload()
    |> Repo.all()
  end
```

It grabs some records using Ecto and returns in about a half second with 767 objects that are rendered into JSON and passed back in the response payload.

However, if I run my application via VSCode, I actually cannot get that function to return (I've waited 5mins, can't seem to figure out how to keep the connection open longer than that). Resource usage on `erl.exe` goes as high as 4GB and 50% CPU while it's chugging along.  I have removed all breakpoints and am still experiencing this problem.

If there is a way to provide you with any extra information that could help, please let me know.

**Comment by axelson** [comment]
> However, if I run my application via VSCode

How are you running the application exactly? Is that via the debugger?

**Comment by ctataryn** [comment]
@axelson I am using the following launch configuration with VSCode:

```
{
    "configurations": [
        {
            "type": "mix_task",
            "name": "Run API",
            "request": "launch",
            "task": "phx.server",
            "projectDir": "${workspaceRoot}"
        }
    ]
}
```

**Comment by axelson** [comment]
Hmm, maybe that's just overhead from the erlang interpreter interpreting all the files in your project. Does it complete if you reduce the number of objects rendered?

**Comment by ctataryn** [comment]
@axelson I'll try to put together a repo that demonstrates the issue, I'll post back here when I'm done.

**Comment by axelson** [comment]
That would be very helpful, thanks!

**Comment by ctataryn** [comment]
@axelson just an FYI I still have this on my radar. I spent a bunch of time creating a test project, I just need to get the data straightened out.

I was wondering, is there any way I can examine what the plugin is doing myself? Set breakpoints, step through code, make alterations?

**Comment by axelson** [comment]
@ctataryn in order to debug you'd generally make changes, then run `mix elixir_ls.release -o ~/.vscode-oss/extensions/elixir-lsp.elixir-ls-0.3.2/elixir-ls-release/` (you will have to update that path for your system). I don't use breakpoints since stopping a process in a multi-process system results in lots of errors. Instead I would add `require Logger; Logger.info("client capabilities: #{inspect(state.client_capabilities)}")` type log messages and then view the ElixirLS output (from `view -> output`.

**Comment by axelson** [comment]
Actually you should use `IO.puts` for debugging when debugging a live server (but if you're debugging in the tests you should use `Logger.info`).

**Comment by lukaszsamson** [comment]
@ctataryn ping

**Comment by ctataryn** [comment]
@lukaszsamson Thank you for the reminder. I don't think I'll have the time right now to further investigate this issue, if you'd like to close it, I can bookmark it and re-open when I have some more time in the future.
