### ISSUE TITLE
Find all references doesn't work with argument defaults.

### ISSUE THREAD

**Issue by hworld** [elixir-lsp/elixir-ls#150]
### Environment

* Elixir & Erlang versions (elixir --version): 
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.10.2 (compiled with Erlang/OTP 22)

* Operating system: Fedora 31
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* LSP Client name: ??
* If using VSCode, are you using "ElixirLS Fork: Elixir support and debugger" (note that it has "Fork" in the name)? Yes

### Reproduction

I have a function like so in one module:
```elixir
def check(resource, models, user, opts \\ [])
```

And in another I call it:
```elixir
Subscription.check("User", users, user)
```

Find all references in VSCode doesn't show the `Subscription.check/3` call as a reference. If it's changed to
```elixir
Subscription.check("User", users, user, [])
```
or similar, the reference is found.

**Comment by axelson** [comment]
This is probably a bug in https://github.com/elixir-lsp/elixir_sense/
Specifically you should look in https://github.com/elixir-lsp/elixir_sense/blob/master/lib/elixir_sense/providers/references.ex

Is is also possible that it is a bug in Elixir's `Xref.calls/0`, in which case we probably won't fix it directly and instead switch over to compiler tracing which should be more accurate (WIP PR is at https://github.com/elixir-lsp/elixir_sense/pull/80)

A test that reproduces the error (ideally in ElixirSense) would be very helpful in tracking this down.

**Comment by lukaszsamson** [comment]
It turned out to be an elixir_sense issue. I managed to reproduce and fix it there.

**Comment by hworld** [comment]
Thanks @lukaszsamson! I'm going to close this since you already committed it over there to master. I'm not sure how the issue process normally works over here, but feel free to open it back up if I did something wrong.
