### ISSUE TITLE
Use existing plt_file

### ISSUE THREAD

**Issue by ghost** [elixir-lsp/elixir-ls#156]
Hey, 

is it possible to "reuse" an existing plt file via config? Currently i am using a setup like this [(1)](https://github.com/jeremyjh/dialyxir#continuous-integration):

```
def project do
  [
    ...
    dialyzer: [
      plt_file: {:no_warn, "priv/plts/dialyzer.plt"}
    ]
  ]
end
```

**Comment by lukaszsamson** [comment]
No, dialyxir options are not supported

**Comment by lukaszsamson** [comment]
Tracked in https://github.com/elixir-lsp/elixir-ls/issues/539 and https://github.com/elixir-lsp/elixir-ls/issues/412
