### ISSUE TITLE
[question] vim and language server inside a container

### ISSUE THREAD

**Issue by miquecg** [elixir-lsp/elixir-ls#160]
Hi,

This is a question rather than an issue. I'm using a container as development environment with vim and elixir-ls inside. No init system, just `/usr/bin/zsh -l` as entrypoint. ALE is the LSP client but linting doesn't occur. However on the host (Debian), same setup works and I can check with `ALEInfo` that server has been properly initialized:

```
(executable check - success) /home/devel/elixir-ls/rel/language_server.sh
(started) ['zsh', '-c', '/home/devel/elixir-ls/rel/language_server.sh']
```

Probably this means the language server is not able to spawn its own instances when there is no init process. Is this correct?

**Comment by axelson** [comment]
I am not sure what would happen in that case, are you getting specific error messages?

**Comment by miquecg** [comment]
No errors whatsoever to my knowledge, just the absence of the `(started) ...` line when running inside the container.

**Comment by miquecg** [comment]
Oh, I've just remembered something. I checked executing the very same command (`zsh -c ...`) from container shell and server started fine. So the problem cannot be the lack of an init process.

Since this is just a question I will close the issue and open a new one with the exact problem when I test it again.

**Comment by sanjibukai** [comment]
Hello,
I had also some issue with this version when working with container.
And in my case I wasn't using the `bash` shell within the container while it's somehow a dependency for the launching script.
And since you mentioned `zsh`, your problem might be related.
Take [a look here](https://github.com/elixir-lsp/vscode-elixir-ls/issues/66).

**Comment by axelson** [comment]
@miquecg specifically it appears that if you do not have bash installed on the container then ElixirLS will fail to start. Another workaround is removing asdf from the the container.

**Comment by axelson** [comment]
@miquecg Are you able to test https://github.com/elixir-lsp/elixir-ls/pull/190 to see if if works for your setup? That would be very helpful if so!

**Comment by miquecg** [comment]
@axelson It works fine on my Debian box, running vim on a Zsh shell and using asdf to manage Erlang/Elixir installations. Bash is also installed on the system.

I don't have yet a fully configured image for development so I mostly give up on using containers by now.

**Comment by axelson** [comment]
Thanks for trying out the change!
