### ISSUE TITLE
Upgrade jason

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#169]
Upgrade version of jason used to the latest release. Shouldn't be any breaking changes.

**Comment by lukaszsamson** [comment]
Yep, the changes look harmless.
BTW we should consider adding `strings: :copy` option to `Jason.decode!(body)` in `PacketStream`. In my experience this option drastically reduces memory usage and GC pressure when JSON parse results are passed between processes.

**Comment by axelson** [comment]
I think adding `strings: :copy` could be a good improvement, although we should do some benchmarking (if only informally).

**Comment by wingyplus** [comment]
Do you have any idea show to measure it?

**Comment by axelson** [comment]
Closing since this is fixed in #233. But opened #236 to investigate `strings: :copy`. And @wingyplus to measure it you could try `:observer`. But for any other discussion on this topic please use #236
