### ISSUE TITLE
I'm ready to make this the official repo and merge our VS Code extensions

### ISSUE THREAD

**Issue by JakeBecker** [elixir-lsp/elixir-ls#170]
First, I want to say thank you so much for continuing this project while I've neglected it. I'm really proud and happy that ElixirLS has been useful enough that people have continued to work on it!

I've reached a point where I've accepted that I'm not going to maintain it in the near future. All my work lately has been on hardware that doesn't run Elixir, mostly 2x4s and drywall... It's hard to motivate myself to code on a project I don't use myself regularly.

I hope some day to go back to coding regularly, but in the meantime, I'd like to make this the canonical repository and grant you publishing access to the original ElixirLS extension on the VS Code marketplace. We can change the "author" field in the extension to something like "The Elixir Community" or something since it's not a solo project anymore. I'd appreciate being added as a maintainer here so I can continue contributing if at some point I feel like doing that again.

Sound like a plan?

**Comment by axelson** [comment]
Hi @JakeBecker!

Thank you very much for reaching out, and most of all for all your hard work on ElixirLS! I think that plan sounds great and I've already added you as a maintainer on this repository. To make `https://github.com/elixir-lsp/elixir-ls/` the canonical repository I wonder if it would make sense to transfer the original repository to the organization, I think that way we could keep all the issues and history better.

And I look forward to when you can get back to coding regularly!

**Comment by hauleth** [comment]
I think you could reach to the GitHub for help with repo merge.

**Comment by JakeBecker** [comment]
Okay, I've created a PR for the vscode-elixir-ls repo here: https://github.com/elixir-lsp/vscode-elixir-ls/pull/61

And for the elixir-ls repo here: https://github.com/elixir-lsp/elixir-ls/pull/174

These update the readmes and changelogs to indicate that the elixir-lsp repos will be the canonical ones. I set the publisher to JakeBecker so you can take over publishing to the original extension. (Changing or renaming the publisher would break existing links, unfortunately.) Email me at jake@jakebecker.org for an access token.

After you start publishing updates to the original extension, I think it'd be best to `vsce unpublish` the fork for clarity. I have a branch [here](https://github.com/JakeBecker/vscode-elixir-ls/tree/deprecate-fork) you could publish first to update the readme explaining why it's being deprecated. I'll update the documentation on my repos as well to direct people here at that point too.

Hopefully this makes everything simpler once it's done!

**Comment by axelson** [comment]
Okay, email sent! And I've merged those PR's. Thanks for additionally providing some wording for when we deprecate the vscode extension, that's very helpful. Is it okay with you if I reach out to GitHub's support (as mentioned by hauleth) about merging/making this repository the root fork?

**Comment by axelson** [comment]
This is now complete :tada:
