### ISSUE TITLE
Completion always returns snippets, even if snippets are not supported by the client

### ISSUE THREAD

**Issue by miquecg** [elixir-lsp/elixir-ls#171]
I'd like to ask what to expect from suggestions like `do/end` blocks. In my case they are *literally* inserted:
```
def foo do^@ $0^@end
```
I was expecting to have:
```
def foo do
  ‸ (cursor goes here)
end
```
Looks like a problem supporting snippets provided by the LS. It didn't happend before with previous versions of `elixir-ls`.  I'm running Vim on terminal with ALE.

**Comment by axelson** [comment]
@miquecg The "$0" indicates where the cursor is supposed to be. I'm not sure why this would change recently since not changes have been made in that area in quite a while. What version did you upgrade from and to? Are you sure you're using this repository vs https://github.com/JakeBecker/elixir-ls ?

Also does Vim ALE support the `snippetSupport` option?
```
		/**
		 * Client supports snippets as insert text.
		 *
		 * A snippet can define tab stops and placeholders with `$1`, `$2`
		 * and `${3:foo}`. `$0` defines the final tab stop, it defaults to
		 * the end of the snippet. Placeholders with equal identifiers are linked,
		 * that is typing in one will update others too.
		 */
		snippetSupport?: boolean;
```

**Comment by miquecg** [comment]
Hi @axelson.

Well, I've started using your Elixir LS recently, from version `0.3.0` I think. Probably snippets were not working at all before, but I don't remember to have placeholders inserted in place.

I'm using your fork, not the original repo.

Regarding ALE, looks like it doesn't support snippets feature: https://github.com/dense-analysis/ale/issues/1821

In fact, support for snippets is disabled on the init message to the server: https://github.com/dense-analysis/ale/blob/master/autoload/ale/lsp.vim#L355

Knowing this, what should I expect from do/end or similar suggestions?

**Comment by axelson** [comment]
@miquecg looking at this further it seems that even though ElixirLS reads snippet support, it is always sends snippets even if snippet support is disabled, which is a bug. I edited the issue title to better reflect the bug. It should be a relatively straightforward fix that is constrained to `apps/language_server/lib/language_server/providers/completion.ex`.

**Comment by miquecg** [comment]
Thanks, glad to help discovering a bug :)

**Comment by axelson** [comment]
@miquecg can you confirm that the fix works for you on the latest master?

**Comment by miquecg** [comment]
@axelson Looks like it's working ok.

Thanks!

**Comment by axelson** [comment]
Great, glad to hear it!

**Comment by jeffrey-xiao** [comment]
I'm not entirely sure if this issue has been fixed. On master, it seems like function completions always return snippets even if snippetSupport is false.

I'm using [vim-lsp](https://github.com/prabirshrestha/vim-lsp) which specifies snippetSupport as [false](https://github.com/prabirshrestha/vim-lsp/blob/5dd94c66f7195cf4605fe02c86a27d6d24d8fc88/autoload/lsp.vim#L468).

When completing `Enum.join`, `elixir-ls` gives me this as a completion: `Enum.join(${1:enumerable}, ${2:joiner \\\\ ""})`.

Looking into the [code](https://github.com/elixir-lsp/elixir-ls/blob/master/apps/language_server/lib/language_server/providers/completion.ex#L527), it seems like function completion always expands to snippet form.

Also I don't think the regex for checking if it's snippet handles the case with a text placeholder (e.g. `${1:enumerable}`).

Ideally, I would like it if the function completion without snippets is just an empty arguments list.

**Comment by axelson** [comment]
@jeffrey-xiao you're probably right, can you file that as a new issue?
