### ISSUE TITLE
Invalid diagnostic messages in umbrella app

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir-ls#175]
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 22 [erts-10.7] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.10.2 (compiled with Erlang/OTP 22)
```
* Operating system: macOS 10.15.4
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* LSP Client name: ElixirLS Fork v0.3.2

### Description

In an umbrella app consisting of common and backend apps (where backend uses common as a dependancy) I deleted a function form a module in the common app. This resulted in 3 diagnostic messages - 1 good and 2 invalid. When clicking on the good one I was navigated to the relevant source line. Clicking tho other two resulted in VSCode error popups. Below I pasted the results of Copy and error messages for those diagnostics.

##### Copy
```
{
	"resource": "/Users/user/my_app/apps/common/lib/some_module.ex",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 4,
	"message": "Call to missing or private function MyApp.Common.MyModule.deleted_function/1.",
	"source": "ElixirLS Dialyzer",
	"startLineNumber": 108,
	"startColumn": 15,
	"endLineNumber": 108,
	"endColumn": 86
}
```
##### Copy
```
{
	"resource": "/Users/user/my_app/apps/backend/lib/some_module.ex",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 4,
	"message": "MyApp.Common.MyModule.deleted_function/1\n is undefined or private\n",
	"source": "Elixir",
	"startLineNumber": 108,
	"startColumn": 1,
	"endLineNumber": 108,
	"endColumn": 1
}
```
##### Error on click
```
Unable to open 'some_module.ex': Unable to read file '/Users/user/my_app/apps/backend/lib/some_module.ex' (Error: Unable to resolve non-existing file '/Users/user/my_app/apps/backend/lib/some_module.ex').
```
##### Copy
```
{
	"resource": "/Users/user/my_app/lib/some_module.ex",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 4,
	"message": "MyApp.Common.MyModule.deleted_function/1\n is undefined or private\n",
	"source": "Elixir",
	"startLineNumber": 108,
	"startColumn": 1,
	"endLineNumber": 108,
	"endColumn": 1
}
```
##### Error on click
```
Unable to open 'some_module.ex': Unable to read file '/Users/user/my_app/lib/some_module.ex' (Error: Unable to resolve non-existing file '/Users/user/my_app/lib/some_module.ex').
```

### Troubleshooting
```
rm -rf .elixir-ls
```
and restarting editor does not help

When compiling the project from command line the error message is correct albeit it's missing the full path.
```
mix clean
mix compile
==> common
Compiling 156 files (.ex)
warning: MyApp.Common.MyModule.deleted_function/1 is undefined or private
  lib/some_module.ex:108: MyApp.Common.SomeModule.some_function/5

Generated common app
...
==> backend
Compiling 36 files (.ex)
Generated backend app
...
```

I'll try to work on a PR with a fix.

**Comment by axelson** [comment]
Do the three `some_module.ex` files exist? Or is `some_module.ex` only in the common app?

**Comment by lukaszsamson** [comment]
It's only in the common app.

**Comment by lukaszsamson** [comment]
When I finally got to fixing this bug the app that used to reproduce it no longer does. Maybe the recent PLT optimisation made it less likely to occur. I'm closing it for now.
