### ISSUE TITLE
Potential document symbols improvements

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#176]
Should we prepend function names with `def` and `defp` so that it is easier to scan a document symbols response? Also it would probably be nice if the symbols were sorted based on the order of appearance in the document (for example right now all the `@` attributes are after the functions even if the attributes are set earlier in the document).

**Comment by lukaszsamson** [comment]
> Should we prepend function names with def and defp

+1 on that
> Also it would probably be nice if the symbols were sorted based on the order of appearance in the document

If I remember correctly the elements are returned in the order of` Macro.prewalk` i.e. document order. In VSCode you can change the order though
<img width="215" alt="Screenshot 2020-04-02 at 16 32 44" src="https://user-images.githubusercontent.com/1078186/78261554-a9a70800-74ff-11ea-86f0-fc6aaa8fae7f.png">

**Comment by axelson** [comment]
Ah, sorting by position does indeed work. Now I just need to figure out how to do the equivalent in `lsp-mode`
