### ISSUE TITLE
Remove or isolate call to private module/function Mix.Dep.load_on_environment/1

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#18]
It has been removed/changed in Elixir 1.9-dev.

Upstream issue: https://github.com/JakeBecker/elixir-ls/issues/155

**Comment by Hanspagh** [comment]
Looks like this has already been fixed, I had a look at [this commit](https://github.com/JakeBecker/elixir-ls/commit/df0117cd63d59158088926bb171439e2bd451626) from the original branch. 
It seems like this `Mix.Dep.loaded` has correctly been changed to `Mix.Dep.load_on_environment`. Let me know if there is anything else I can do.

**Comment by axelson** [comment]
The idea behind this issue is to separate out the call to the private function `Mix.Dep.load_on_environment/1` into a separate module, so if it changes in a future version of Elixir (which could happen in a point release), it is easy to update ElixirLS to match. Here's an example from ElixirSense: https://github.com/elixir-lsp/elixir_sense/blob/master/lib/elixir_sense/core/normalized/typespec.ex

Although the title of the issue was outdated which makes it a little confusing. I've updated the title for accuracy.

**Comment by Hanspagh** [comment]
I see, should not be too difficult fo fix then 👍

**Comment by lukaszsamson** [comment]
I don't think it's worth doing
