### ISSUE TITLE
An exception in ElixirLS.LanguageServer.Providers.WorkspaceSymbols brings down the server

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#185]
If you're rapidly changing a between valid code and code with a syntax error (and saving in between) it is fairly easy to trigger an exception in `ElixirLS.LanguageServer.Providers.WorkspaceSymbols`:

```
08:58:37.748 [error] Task #PID<0.258.0> started from #PID<0.279.0> terminating
** (UndefinedFunctionError) function A.module_info/1 is undefined (module A is not available)
    A.module_info(:exports)
    (language_server 0.3.2) lib/language_server/providers/workspace_symbols.ex:381: anonymous fn/2 in ElixirLS.LanguageServer.Providers.WorkspaceSymbols.index/1
    (elixir 1.10.2) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (language_server 0.3.2) lib/language_server/providers/workspace_symbols.ex:380: anonymous fn/1 in ElixirLS.LanguageServer.Providers.WorkspaceSymbols.index/1
    (elixir 1.10.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

Then since `WorkspaceSymbols` is a GenServer and this happens in a `Task.start_link` the `WorkspaceSymbols` GenServer crashes. And `ElixirLS.LanguageServer.Supervisor` has a config of `max_restarts: 0` which means that this exception causes the entire LanguageServer to go down.

There's a few possible fixes and I haven't had time to think through them yet, but here's a few off the top of my head (we probably want to do more than one):
1. Fix the specific exception since it is a somewhat expected error
2. Move `WorkspaceSymbols` under a new supervisor that allows for restarts
3. Change `WorkspaceSymbols` to not be a GenServer (but then who would hold the state?)
4. Change `WorkspaceSymbols` to do it's processing without linking (will avoid crashes)
5. Change `WorkspaceSymbols` to use the already used async pattern from `ElixirLS.LanguageServer.Server`
6. detect when there's a compilation error and don't continue indexing

There's probably more but I wanted to get an initial list down.

**Comment by lukaszsamson** [comment]
> Fix the specific exception since it is a somewhat expected error

Yes, it's expected. The module is unloaded before its processing is finished. I've seen it also in tests. We should start with fixing it IMO.

> Move WorkspaceSymbols under a new supervisor that allows for restarts

We would loose the state on restart. We'd need to keep it somewhere else. Dumping to a file is an option and it would speed up the start time once it's built.

> Change WorkspaceSymbols to not be a GenServer (but then who would hold the state?)
> Change WorkspaceSymbols to do it's processing without linking (will avoid crashes)

We would need to combine those two. Linking tasks to the server process would be even worse.

> Change WorkspaceSymbols to use the already used async pattern from ElixirLS.LanguageServer.Server

It's a rather CPU intensive task. Server process would block.

> detect when there's a compilation error and don't continue indexing

It's still worth to index stdlib and dependancies

**Comment by axelson** [comment]
> > Move WorkspaceSymbols under a new supervisor that allows for restarts
> 
> We would loose the state on restart. We'd need to keep it somewhere else. Dumping to a file is an option and it would speed up the start time once it's built.

I think that rebuilding the state on restart is a viable option, although we could investigate dumping to a file as a performance enhancement. Although then we'd have to handle process crashes due to corrupted persisted state. For this reason I think moving WorkspaceSymbols under a new supervisor is a viable short-term option.

> > Fix the specific exception since it is a somewhat expected error
> 
> Yes, it's expected. The module is unloaded before its processing is finished. I've seen it also in tests. We should start with fixing it IMO.

Agreed

> > Change WorkspaceSymbols to use the already used async pattern from ElixirLS.LanguageServer.Server
> 
> It's a rather CPU intensive task. Server process would block.

That's not quite right, when I say the "already used async pattern" I'm referring to this piece of code: 
https://github.com/elixir-lsp/elixir-ls/blob/master/apps/language_server/lib/language_server/server.ex#L525-L532

Which spawn a new process (as a sidenote this should probably use `Task.Supervisor.async_nolink`) that runs in parallel to `ElixirLS.LanguageServer.Server`

> > detect when there's a compilation error and don't continue indexing
> 
> It's still worth to index stdlib and dependancies

Yeah that makes sense.

**Comment by lukaszsamson** [comment]
@axelson Can we close it and maybe open a new meta issue for refactoring supervision tree?

**Comment by axelson** [comment]
Good idea, moved to meta-level issue https://github.com/elixir-lsp/elixir-ls/issues/368
