### ISSUE TITLE
Add pre-built binary to release version

### ISSUE THREAD

**Issue by wingyplus** [elixir-lsp/elixir-ls#188]
### Environment

* Elixir & Erlang versions (elixir --version): elixir ~1.10
* Operating system: macOS
* Editor or IDE name (e.g. Emacs/VSCode): vim
* LSP Client name: vim-lsp, vim-lsp-settings

### Description

The [vim-lsp-settings](https://github.com/mattn/vim-lsp-settings/blob/master/installer/install-elixir-ls.sh) use old version of `JakeBecker/elixir-ls`. It's time to move it to `elixir-lsp` organization that's a current home for `elixir-ls`. But `elixir-ls` of JakeBecker version ship it with pre-built binary that `vim-lsp-settings` rely on it. So I want to propose that we should ship `elixir-ls` pre-built binary with release version. What do you think? :)

**Comment by axelson** [comment]
Hmm, that would be possible. It looks like previously there was a `elixir-ls.zip` that was shipped which was just a zip file of the release directory: https://github.com/JakeBecker/elixir-ls/releases/tag/v0.2.25

But it would be nice to be able to automatically create the release after creating the tag.

**Comment by axelson** [comment]
@wingyplus Okay, just made a new release and included a `elixir-ls.zip`: https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.3.3
