### ISSUE TITLE
Formatter config files not respected in multi-root workspaces

### ISSUE THREAD

**Issue by marceldegraaf** [elixir-lsp/elixir-ls#205]
(Copied from the original vscode-elixir-ls issue tracker, [issue #91](https://github.com/JakeBecker/vscode-elixir-ls/issues/91))

ElixirLS formats code as expected when only one Elixir project is open. It doesn't appear to pick up the different `.formatter.exs` files in multi-root workspaces.

Instead, it seems to use Elixir's default formatter settings, which trips `mix format --check-formatted` checks that _do_ use the correct `.formatter.exs` configuration.

Jake's [response](https://github.com/JakeBecker/vscode-elixir-ls/issues/91#issuecomment-406352788) on the original issue tracker was that multi-root workspaces aren't really supported yet. Does that still apply, and/or will that change in the future now this has become the main repository?

Happy to provide additional info if needed. 

---

### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 22, Elixir 1.10.2 and 1.9.4
* Operating system: macOS Catalina and Debian 10 (Buster)
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* LSP Client name: 
* If using VSCode, are you using "ElixirLS Fork: Elixir support and debugger" (note that it has "Fork" in the name)? Yes

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the entire dialyzer build

**Comment by axelson** [comment]
There's a PR underway to support multi-root workspaces. Here's the associated issue: https://github.com/elixir-lsp/vscode-elixir-ls/issues/58

Please track there for any updates.
