### ISSUE TITLE
Function completions always returned as snippets

### ISSUE THREAD

**Issue by jeffrey-xiao** [elixir-lsp/elixir-ls#207]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.9.4, Erlang/OPT 22
* Operating system: Linux
* Editor or IDE name (e.g. Emacs/VSCode): Vim 
* LSP Client name: vim-lsp

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the entire dialyzer build

The LSP client that I'm using specifies `snippetSupport` as [false](https://github.com/prabirshrestha/vim-lsp/blob/5dd94c66f7195cf4605fe02c86a27d6d24d8fc88/autoload/lsp.vim#L468), but all function completions are still being returned with snippets.

For example, `elixir-ls` gives `Enum.join(${1:enumerable}, ${2:joiner \\\\ ""})` for the completion of `Enum.join`.

Looking into the [code](https://github.com/elixir-lsp/elixir-ls/blob/3890d815af9c7525d27bbb839f8690379b8b1021/apps/language_server/lib/language_server/providers/completion.ex#L527), it seems like function completion always expands to snippet form.

The [regex](https://github.com/elixir-lsp/elixir-ls/blob/3890d815af9c7525d27bbb839f8690379b8b1021/apps/language_server/lib/language_server/providers/completion.ex#L662) for checking if a completion is a snippet  also does not account for when the snippet has a placeholder.

My ideal behaviour is to provide an empty argument list if the LSP client does not support snippets.

**Comment by axelson** [comment]
Marking this as "help wanted" and "good first issue" because this should be a fairly straightforward fix that won't require looking at any code outside of https://github.com/elixir-lsp/elixir-ls/blob/81057be222204a461aad132f31d4666b3ea082b2/apps/language_server/lib/language_server/providers/completion.ex

**Comment by axelson** [comment]
A good approach might be to define two versions of the completions, one that supports snippets and another that does not.
