### ISSUE TITLE
Add ability to format .leex templates

### ISSUE THREAD

**Issue by dbi1** [elixir-lsp/elixir-ls#215]
Hi,

Any chance we could add formatting for .leex templates (LiveView templates)?

Thank you for all the work on this very helpful extension!

**Comment by axelson** [comment]
This would be a great enhancement (we could implement it as a code action with respect to LSP). And we would want to support `.eex` files at the same time.

**Comment by thiagomajesk** [comment]
Hi @axelson! I've been trying a lot of alternatives to get both `.eex` and `.leex` files to format properly in VSCode. 
One of them involves using [Beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify) that [does not indent the files properly](https://github.com/HookyQR/VSCodeBeautify/issues/363).

Do you have any idea how to approach adding this functionality to the extension?

PS.: I see that there's [another extension](https://github.com/RoyalMist/vscode-eex-format) that supposedly does this, but I haven't tested. I also dunno if this conflicts with ElixirLs.

**Comment by lukaszsamson** [comment]
Superseded by https://github.com/elixir-lsp/elixir-ls/issues/660
