### ISSUE TITLE
Releases compiled with older Elixir

### ISSUE THREAD

**Issue by mwoods79** [elixir-lsp/elixir-ls#240]
Release v0.3.3 was compiled with Elixir 1.6.1 even though the minimum requirement is ElixirLS is 1.7

```
❯ ~/.elixir_ls/language_server.sh
Content-Length: 111

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Started ElixirLS Fork v0.3.3","type":4}}

Content-Length: 131

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Elixir version: \"1.6.1 (compiled with OTP 19)\"","type":4}}

Content-Length: 105

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Erlang version: \"20\"","type":4}}
```

**Comment by axelson** [comment]
What that log is showing is the version of elixir that the language server is currently running under, not the version that it was compiled with (which currently isn't shown although it could be added in #229). So it appears that ElixirLS is picking up 1.6.1 either from your global elixir version or from asdf. How did you install Elixir and Erlang?

Although, it would probably be good for ElixirLS to return an error or refuse to start on an unsupported version of Elixir.

**Comment by frm** [comment]
Just to add to this: my dotfiles automatically compile elixirls when installed with vim plug and just came across this issue. I use a global `.tool-versions` with Elixir 1.10 and the compilation failed with:

```
asdf: No version set for command mix
you might want to add one of the following in your .tool-versions file:
# installed elixir versions
```

due to the local `.tool-versions` being the one that gets picked up when compile.

**Comment by axelson** [comment]
@frm If you run `asdf install` from the repository then asdf will install the versions used for compiling releases. It is important to use a lower version for compatibility since you won't be able to run any code on an earlier version.

**Comment by axelson** [comment]
@mwoods79 did you find out what `.tool-versions` was being used?

**Comment by mwoods79** [comment]
@axelson yes, and thank you for your help. I had a brew installed elixir and an asdf installed elixir on this machine.
