### ISSUE TITLE
Investigate using new shell_docs function in OTP 23

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#242]
http://blog.erlang.org/OTP-23-Highlights/

> We have added a new module shell_docs in stdlib with functions for rendering documentation for a shell. This can be used for instance by Development Environments such as those based on the Language Server Protocol (LSP).

Also `:code.get_doc` seems possibly useful

**Comment by lukaszsamson** [comment]
This needs to be addressed in elixir_sense
