### ISSUE TITLE
Comprehensive approach to utf-16 positions

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#244]
https://github.com/elixir-lsp/elixir-ls/pull/200 added support for utf-16 formatting. However, it can be improved to be more comprehensive and better tested with automated tests. We should also double check that we've gotten all the places that utf-16 translation is needed.

**Comment by lukaszsamson** [comment]
I stumbled on this issue in definition provider. I think it's safe to assume formatting is the only place that handle this correctly. Fortunately this bug rarely manifests.

**Comment by lukaszsamson** [comment]
I went through the sources and identified many places where we either return incorrect positions or incorrectly pass positions to ElixirSense or other downstream processing. List of possible issues (probably not exhaustive):
- build diagnostic
- formatting mayers_difference
- hover
- on_type_formatting
- references
- definition
- completion
- signature_help
- macro_expansion

Fortunately there is some traction on UTF8 positions support, see https://github.com/Microsoft/language-server-protocol/issues/376#issuecomment-960633758

**Comment by axelson** [comment]
Yeah, I'm kind of thinking that we drop/deprecated UTF-16 support. I think that the majority of clients that people are using support UTF-8 and that would simplify (and speed up) ElixirLS.

**Comment by lukaszsamson** [comment]
I'm closing this one. We'll open a separate issue when utf8 positions are in spec
