### ISSUE TITLE
Find references is currently broken on 1.10

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#257]
`textDocument/references` is currently broken when running on 1.10. This is most likely related to xref changes when compiler tracing was implemented in Elixir. Still need to test if compiling elixir-ls on 1.10 will have an impact.

**Comment by axelson** [comment]
This might be considered a bug in Elixir 1.10, so if someone can reproduce the bug in `Mix.Tasks.Xref` (as used in ElixirSense) it could be reported upstream.

**Comment by lukaszsamson** [comment]
I tried master build and running on 1.10 as well as 0.4 build on 1.7 and running on 1.10 and in both combinations it worked.

**Comment by axelson** [comment]
Hmmm, I'll do some more investigation to see if there's a different root cause.

**Comment by msaraiva** [comment]
I'm using `v1.10.3` and it's working fine. It would nice to get more information from people experiencing this problem, like:

* Is there any error message in `ElixirLS` console?
* Does the problem happens in all projects or maybe just in umbrellas?
* Does running `Mix.Tasks.Xref.calls()` in a `iex -S mix` console works?

@lukaszsamson what do we need to do regarding https://github.com/elixir-lsp/elixir_sense/pull/80 to make it feasible? As far as I remember, it requires a stateful tracer, right? If that's the case, I don't think we'll have a choice but creating a stateful application for ElixirSense. Editors that don't use `elixir-ls` will have to find a way to use `elixir-ls` or roll their own solution. 

Unfortunately, we can't keep using deprecated API any longer, IMO. Besides, using the tracer will allow us to gradually simplify some of the most complex logic we have, making the code less sensitive to Elixir updates.

Also, having a stateful process around opens new possibilities for optimization and new features that might require access to previously fetched information (e.g. the list of all loaded modules, etc.)

@axelson WDTY?

**Comment by lukaszsamson** [comment]
> it requires a stateful tracer, right?

Yes, but it doesn't necessarily be managed by elixir_sense, it may be managed by elixir-ls and injected. The bigger problem is that it requires elixir >= 1.10 and I'm not sure it will even work when compiled with 1.7.

> Also, having a stateful process around opens new possibilities for optimization and new features 

A few modules could use a cache

**Comment by axelson** [comment]
Hmmm, it's seeming like I was wrong about this issue. Since we can't reproduce it I'm going to go ahead and close it, perhaps there was some other issue that was since fixed. If we can reproduce it in the future we can re-visit.

Regarding https://github.com/elixir-lsp/elixir_sense/pull/80 the issue is (as Łukasz mentioned) that it requires elixir 1.10+ and it's too early to require Elixir 1.10. And it most likely be a significant undertaking to maintain dual implementations where we'd use compiler tracing if it is available, but ignore it if it is not available (and we'd have to solve the packaging problem (#115) as well, or at least have end-users automatically compile ElixirLS).
