### ISSUE TITLE
Syntax highlighting stopped working for html.eex files

### ISSUE THREAD

**Issue by colopatiron** [elixir-lsp/elixir-ls#266]
After I uninstalled ElixirLS fork and installed ElixirLS, my html.eex files no longer have syntax highlighting.

The only other elixir vscode extension I have installed is ElixirLinter.

Any help would be appreciated.

**Comment by NikitaAvvakumov** [comment]
@colopatiron Take a look at the [changelog](https://github.com/elixir-lsp/elixir-ls/blob/master/CHANGELOG.md) for v0.4.0, section titled "VSCode potentially breaking changes" - perhaps that's the solution?

**Comment by colopatiron** [comment]
I overlooked one extension (EEx Formatter/Beautify) and it was causing the issue. Fixed with
```
  "files.associations": {
    "*.eex": "eex",
  },
```

**Comment by colopatiron** [comment]
I overlooked one extension (EEx Formatter/Beautify) and it was causing the issue. Fixed with
```
  "files.associations": {
    "*.eex": "eex",
  },
```
