### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by mvisca89** [elixir-lsp/elixir-ls#272]
HI, I have the next compiling error:

== Compilation error in file lib/language_server/dialyzer/analyzer.ex ==
** (ArgumentError) lib file dialyzer/src/dialyzer.hrl could not be found
    (elixir) lib/record/extractor.ex:41: Record.Extractor.from_lib_file/1
    (elixir) lib/record/extractor.ex:18: Record.Extractor.from_or_from_lib_file/1
    (elixir) lib/record/extractor.ex:5: Record.Extractor.extract/2
    lib/language_server/dialyzer/analyzer.ex:42: (module)

currently, I'm using elixir 1.9.1 and Erlang/OTP 22. I can't figure how to solve it and I didn't find anything useful.
Btw , I'm trying to use it with nvim + coc-elixir

**Comment by axelson** [comment]
@mvisca89 What OS are you running and how did you install elixir? I think this problem typically occurs when you don't have a complete installation of Erlang: https://github.com/elixir-lsp/elixir-ls/issues/208

**Comment by mvisca89** [comment]
Thx for the link. Currently, I'm using PopOS 19.04. I just purge all the erlang packages installed on my system, and then I just follow this guide https://elixir-lang.org/install.html#unix-and-unix-like.
Now works like a charm with nvim.
 I'm closing this. Thx

**Comment by axelson** [comment]
Glad you got it to work!
