### ISSUE TITLE
CPU Usage on Linux

### ISSUE THREAD

**Issue by luizpvas** [elixir-lsp/elixir-ls#276]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.9.1 / Erlang/OTP 22 [erts-10.4.4]
* Operating system: Linux Mint 19.1 Tessa
* Editor or IDE name (e.g. Emacs/VSCode): VSCode 1.45.1
* If using VSCode, are you using "ElixirLS: Elixir support and debugger"? Yes

### Issue

Hey guys, first of all thanks for this incredible package. The autocomplete works just great.

I use Linux Mint in an older laptop at home, and I noticed the CPU usage a bit high for normal usage - small project, writing and saving small files (< 100 LOC).

![image](https://user-images.githubusercontent.com/4276593/83467586-b2a94c80-a450-11ea-8475-c72c35a67d72.png)

CPU usage seems to grow over time, and vscode starts slowing down about 5min in. I'm not sure if there is a mistake on my part, I'm glad to help with anything. Thanks again!

### Logs

No particular log caught my attention, they all look something like the following snippet:

```
Compiling with Mix env test
Compiling 1 file (.ex)
[Info  - 9:40:13 PM] Compile took 229 milliseconds
[Info  - 9:40:13 PM] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 9:40:17 PM] [ElixirLS Dialyzer] Found 692 changed files in 3761 milliseconds
```

**Comment by lukaszsamson** [comment]
Any chance you have many VSCode windows open? I can see many beam processes. The CPU should stay high only during initial indexing and dialyzer PLT build (which may take a few minutes)

**Comment by luizpvas** [comment]
You were right, it seems I had more windows open and didn't notice.
In this laptop it took a bit more than 5min to index - CPU usage went down completly afterwards.

Thanks for the response!
