### ISSUE TITLE
Autocomplete format should display nicely on multiple clients

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#281]
This is pulled from the discussion on https://github.com/elixir-lsp/elixir-ls/pull/273

The main fix appears to be not returning markdown in `detail`

Maybe move the signature info to the documentation area so that detail is just origin + type.

@msaraiva are you planning on tackling this?

**Comment by msaraiva** [comment]
Hi @axelson!

Sure, I am 👍

I'm still playing with it, trying to find an alternative and also doing some minor tweaks. I'll soon post a screenshot of that change along with other alternatives so we can choose the best one.

Sorry for not being as fast as you expected. I warned you 😁

**Comment by axelson** [comment]
haha, it's not as much about not being as fast as I expected. It's more that I personally didn't want to track this issue in my head and wanted to make sure that it didn't get lost. Looking forward to the screenshots :+1:

**Comment by axelson** [comment]
This was fixed in #300
