### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by korsmakolnikov** [elixir-lsp/elixir-ls#286]
### Environment

* Elixir & Erlang versions (elixir --version): 1.10
* Operating system: Ubuntu focal fossa
* Editor or IDE name (e.g. Emacs/VSCode): vim
* LSP Client name: Coc

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

I have a very high and annoying CPU usage 
![image](https://user-images.githubusercontent.com/13141364/83950743-4dc56c00-a82d-11ea-8697-042d4d163632.png)

First I try to build the e-ls again and remove from Coc configuration completely. Then I start a new elixir project but... same results. 
Of course, disabling dialyzer fixes the problem but I think isn't intended so.
Suggestions?

**Comment by axelson** [comment]
Does it go away after 10-15 minutes? On first launch it takes quite a bit of CPU to build the dialyzer PLTs, CPU usage should go down after that. Alternatively you could disable the Dialyzer integration.
