### ISSUE TITLE
Memory leak in BEAM processes while using the VSCode extension

### ISSUE THREAD

**Issue by polvalente** [elixir-lsp/elixir-ls#301]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.9.4, Erlang OTP 22.3.4
* Operating system: Ubuntu 18.04.4
* Editor or IDE name (e.g. Emacs/VSCode):  VSCode
* LSP Client name: 
  * If using VSCode, are you using "ElixirLS: Elixir support and debugger"? Yes, I'm using "ElixirLS: Elixir support and debugger", not the Fork. Version 0.4.0

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
  - I had to sigkill the beam process to get my machine to be responsive again. It ate up 30GB of memory.
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project
  - This solved the issue only momentarily. As soon as the process finished rebuilding, memory usage started to rocket again.

### Logs

1.  If using a client other than VS Code, please try VSCode's "ElixirLS: Elixir support and debugger" extension. Does it reproduce your failure?
  - The problem was not reproduced in an empty project.
2.  Create a new Mix project with `mix new empty`, then open that project with VS Code and open an Elixir file. Is your issue reproducible on the empty project? If not, please publish a repo on Github that does reproduce it.
  - I tried applying the only new change I had made -- which was to add some NewRelic dependencies, but the problem was not reproduced.
3.  Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)
  - I cannot share the exact logs for the extension, but the leak appeared when I got some warnings due to code like this, which returns a warning: 
```elixir
 defmodule MyMacro do
  defmacro __using__(opts) do
    name = Keyword.get(opts, :name)

    quote do
      use NewRelicTools.ModuleTracer, trace_private?: false

      @behaviour MyMacro

      @name unquote(name)
      def name, do: name
    end
  end

  @callback name :: atom()
end
```

After removing the `use` statement from the macro, everything went back to normal, seemingly.

The same code in an empty project doesn't provoke the leak, though.
4.  Check the developer console by opening `Help > Toggle Developer Tools` and include any errors that look relevant.
The following log happened in correlation with said memory leak, but looking at `htop`, the memory is all going to the Erlang process.
```
  ERR Cannot read property 'getCell' of undefined: TypeError: Cannot read property 'getCell' of undefined
    at Object.t.convertLinkRangeToBuffer (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3371:362)
    at e._provideLinks (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4290:723)
    at e.provideLinks (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3370:508)
    at /usr/share/code/resources/app/node_modules.asar/xterm/lib/xterm.js:1:242351
    at Array.forEach (<anonymous>)
    at t._askForLink (/usr/share/code/resources/app/node_modules.asar/xterm/lib/xterm.js:1:242213)
    at t._onHover (/usr/share/code/resources/app/node_modules.asar/xterm/lib/xterm.js:1:241908)
    at t._onMouseMove (/usr/share/code/resources/app/node_modules.asar/xterm/lib/xterm.js:1:241768)
```

**Comment by polvalente** [comment]
I'm still filling in the template. Accidentally clicked the submit button!

**Comment by axelson** [comment]
Hmm, a little hard to track this down without some reproduction steps or a repo. How often does it occur for you?

**Comment by polvalente** [comment]
> Hmm, a little hard to track this down without some reproduction steps or a repo. How often does it occur for you?

It only occurred in this one project for me. I managed to bypass the problem by removing the `use NewRelicTools.ModuleTracer` statement. I guess it's some funny interaction with compilation warnings + the `@on_definition` calls that are injected by the ModuleTracer.

However, calling this `use` outside my custom macro didn't provoke the same bug.

**Comment by polvalente** [comment]
@axelson If you prefer to close this issue, it's no problem for me. I thought it best to keep it up so you could at least know this has been an issue.

**Comment by axelson** [comment]
Okay, I'll go ahead and close this ticket for now. But if it keeps happening we should try to get to the bottom of it. One avenue of approach is we could look into what is happening if you run `:observer.start` when it happens. Unfortunately it's a little tricky to get a hook into that right now. I used https://github.com/elixir-lsp/elixir-ls/pull/46 previously to look into a somewhat similar issue (it turned out to be an infinite loop in elixir_sense). So if you want to track it down you could try to investigate that approach.

**Comment by jacksonbenete** [comment]
I'm having 99% CPU usage on M1 with the VSCode extension, lag everything, computer barely usable until kill the LS or VSCode itself.
The repository is a simple phx.new boilerplate, and ElixirLS is literally the only extension I have installed.

Erlang/OTP 24, Elixir 1.12.3
BigSur 11.5.2 (Macbook Air 8GB RAM)
ElixirLS: v0.8.1: 1 September 2021
