### ISSUE TITLE
Detach forked repository

### ISSUE THREAD

**Issue by ihabunek** [elixir-lsp/elixir-ls#310]
Currently this repository is marked as `forked from JakeBecker/elixir-ls`. This would be perfectly fine if Github didn't treat this kind of repository differently in undesired ways:

* It's not possible to search code. This bit me when investigating #309. For example [this search](https://github.com/elixir-lsp/elixir-ls/search?q=LanguageServer&type=Code) says "Sorry, forked repositories are not currently searchable. You could try searching the parent repository."
* Commits made in a fork will not count toward your contributions. This is mostly vanity, but might be important to some people.

Github does not intend the forked repos to live on their own, only as a proxy for making contributions to the upstream repo. 

This page suggests detaching the fork could be done by contacting Github support:
https://help.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork

**Comment by jayjun** [comment]
Also when you make a pull request, GitHub defaults to merging into `JakeBecker/elixir-ls`. Then you must hunt for `elixir-lsp/elixir-ls`. I have avoided submitting to the wrong repository so far.

**Comment by axelson** [comment]
Yeah I think this makes sense. I will try to contact GitHub support.

**Comment by axelson** [comment]
And they've already taken care of it 🎊. Thanks for the report!
