### ISSUE TITLE
ElixirLS cannot start in docker container

### ISSUE THREAD

**Issue by sannek** [elixir-lsp/elixir-ls#311]
Since earlier today I'm having an issue where the ElixirLS server can no longer start when I'm working inside a container. (using the MIcrosoft [`ms-vscode-remote.remote-containers`](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension) It fails with the following error (shown here only once, but it happens 5 times in about a second, so then it gives up on restarting):

```
14:54:43.846 [info]  Application hipe exited: :stopped
[Warn  - 2:54:43 PM] ** (MatchError) no match of right hand side value: {:error, {:wx, {'no such file or directory', 'wx.app'}}}
    (language_server) lib/language_server/cli.ex:9: ElixirLS.LanguageServer.CLI.main/0
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/code.ex:240: Code.eval_string/3
[Error - 2:54:43 PM] Connection to server got closed. Server will not be restarted.
```

The only other error visible in the VSCode developer tools console is: `  ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.`

I have tried all of the following:
* rebooted computer
* restarted VSCode
* removed `.elixir_ls` directory

It does not seem to matter what branch of my project I'm on, and in the same project outside of the container ElixirLS works just fine.

Unfortunately I can't share the full project, and tbh I don't know enough about Docker to create a minimal example, but it is a Phoenix project that is running as part of a docker-compose collection of containers (db / client etc). I know this is less than helpful, but hopefully someone has an idea of what might be going on, and how I can fix it. Thanks in advance!

### Environment

* Elixir 1.9.2 (Erlang/OTP 22): 
* MacOS Catalina (10.15.5)
* VSCode
* ElixirLS: Elixir support and debugger

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

### Logs

1.  If using a client other than VS Code, please try VSCode's "ElixirLS: Elixir support and debugger" extension. Does it reproduce your failure?
2.  Create a new Mix project with `mix new empty`, then open that project with VS Code and open an Elixir file. Is your issue reproducible on the empty project? If not, please publish a repo on Github that does reproduce it.
3.  Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)
4.  Check the developer console by opening `Help > Toggle Developer Tools` and include any errors that look relevant.

**Comment by jayjun** [comment]
Cannot reproduce with VS Code ElixirLS 0.5.0. What is your extension’s version?

Also, I suspect making sure the Erlang inside your container is built with wxWidgets will resolve the issue. See https://github.com/asdf-vm/asdf-erlang#ubuntu-1604-lts-xenial-xerus for asdf instructions.

**Comment by sannek** [comment]
Thanks for your reply! I was using 0.5.0 (but reverting to 0.4.0 did not fix the issue). I figured it was something in the container, but it seemed coincidental enough with the extension update that I figured I'd report it anyway. I'll see if I can tinker with the dockerfile to make sure wxWidgets is included. Thanks again!
