### ISSUE TITLE
Test suite is broken

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#314]
Recently the test suite has become broken

Example failure:
- https://travis-ci.org/github/elixir-lsp/elixir-ls/builds/704739324
- https://travis-ci.org/github/elixir-lsp/elixir-ls/jobs/704739328

It appears that dialyzer is timing out for some reason. Possibly the server is crashing (I have some code I plan to commit to assert that the server doesn't crash in the tests, which will give better errors in that case).

**Comment by lukaszsamson** [comment]
The failures are no longer happening

**Comment by axelson** [comment]
Thanks for cleaning up this and other issues!
