### ISSUE TITLE
Completion adds ${1:xxxx} and so on

### ISSUE THREAD

**Issue by victorolinasc** [elixir-lsp/elixir-ls#316]
### Environment

* Elixir & Erlang versions (elixir --version): 1.10
* Operating system: Linux :)
* Editor or IDE name (e.g. Emacs/VSCode): Emacs :)
* LSP Client name: lsp-mode

### Troubleshooting

- [X] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [X] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

-------------------------

After recent updates the completion on Emacs is working but weird. Here is what it outputs:

```elixir
  def handle_batch(${1:batcher}, ${2:messages}, ${3:batch_info}, ${4:context}) do
	$0
  end
```

Not sure if this is an issue of elixir-ls itself but I thought this should be mentioned :)

**Comment by wingyplus** [comment]
I remember that lsp-mode requires yasnippet to work with snippet. Did you try it?

**Comment by axelson** [comment]
Yeah it would seem like something on the emacs side isn't interpreting the LSP snippet syntax correctly: https://microsoft.github.io/language-server-protocol/specification#snippet_syntax

**Comment by victorolinasc** [comment]
Thanks for the tip @wingyplus 

Will try debugging it WITH yasnippet. Be back with results soon.

**Comment by victorolinasc** [comment]
ANd it works (almost but it proves it is a lsp issue). Closing here! 

Thanks people!
