### ISSUE TITLE
lsp-ui-doc popup for function documentation doesn't show up in Emacs lsp-mode

### ISSUE THREAD

**Issue by x-ji** [elixir-lsp/elixir-ls#320]
I'm not sure if I should ask the question here or under the issues of `lsp-mode`. I'll first post it here and see if anybody has experienced something similar and could offer some advice. If it's deemed inappropriate I'll close it and reopen it in the `lsp-mode` repo.

So in Emacs `lsp-mode` one is supposed to be able to have a popup window (lsp-ui-doc-mode) that shows the documentation for the function under the cursor. I have it enabled by default and it works for other modes which use lsp (e.g. Javascript). I also remember it working with elixir-ls some time ago. However, I don't know from when, it stopped working. (Or maybe I mixed it up with the behavior of VSCode). Calling `lsp-ui-doc-show` manually also has no effect.

The interesting thing is that, if I run `lsp-describe-thing-at-point`, the documentation for the function does show up in a separate buffer. So elixir-ls is definitely able to retrieve the documentation just fine, but it seems that this information is just not provided to `lsp-ui-doc-mode` for some reason.

I wonder if anybody has any idea on how to fix it, since having the documentation pop up automatically would be much more helpful for me than having to press another key manually to see it in another buffer. Or if it's not reproducible, maybe there's something wrong with my Emacs configuration.

### Environment

* Elixir & Erlang versions (elixir --version): 1.10.2
* Operating system: MacOS
* Editor or IDE name (e.g. Emacs/VSCode): Emacs
* LSP Client name: lsp-mode

### Troubleshooting

- [ x ] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [ x ] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

### Logs
2.  Create a new Mix project with `mix new empty`, then open that project with VS Code and open an Elixir file. Is your issue reproducible on the empty project? =
  Yes
3.  Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)

Doesn't seem to be anything unusual in the logs:
```
Started ElixirLS v0.5.0
Elixir version: "1.10.2 (compiled with Erlang/OTP 22)"
Erlang version: "22"
ElixirLS compiled with Elixir 1.10.2 and erlang 22
MIX_ENV: test
MIX_TARGET: host
Command "language_server.sh" is present on the path.
Command "language_server.sh" is present on the path.
Found the following clients for /Users/jx/test/lib/test.ex: (server-id elixir-ls, priority -1)
The following clients were selected based on priority: (server-id elixir-ls, priority -1)
Compiling 1 file (.ex)
Generated test app
Compile took 1428 milliseconds
[ElixirLS WorkspaceSymbols] Indexing...
[ElixirLS Dialyzer] Checking for stale beam files
[ElixirLS Dialyzer] Found 7 changed files in 462 milliseconds
Cancelling textDocument/onTypeFormatting(193) in hook after-change-functions
[ElixirLS Dialyzer] Analyzing 7 modules: [Collectable, Enumerable, IEx.Info, Inspect, List.Chars, String.Chars, Test]
[ElixirLS WorkspaceSymbols] Module discovery complete
[ElixirLS WorkspaceSymbols] 20 callbacks added to index
[ElixirLS WorkspaceSymbols] 195 modules added to index
[ElixirLS WorkspaceSymbols] 369 types added to index
[ElixirLS Dialyzer] Analysis finished in 2549 milliseconds
Dialyzer analysis is up to date
[ElixirLS Dialyzer] Writing manifest...
[ElixirLS Dialyzer] Done writing manifest in 1180 milliseconds.
[ElixirLS WorkspaceSymbols] 4223 functions added to index

```

**Comment by axelson** [comment]
Does `lsp-describe-thing-at-point` work? If it does then I think it is a `lsp-mode` configuration issue, does the popup work for any other languages? Although I'm currently seeing something that may be similar to what you're seeing in my Doom Emacs setup (that I'm still working on). `lsp-describe-thing-at-point` works but I can't get the popup to show.

But in my Spacemacs setup lsp-ui has no problem with the popup.

**Comment by x-ji** [comment]
@axelson Yep, as I mentioned, `lsp-describe-thing-at-point` works and shows the documentation in a popup buffer. The `lsp-ui-doc` popup is also working for other languages so it's pretty weird. I'm using Spacemacs and I don't think I've set custom variables related to this.

**Comment by axelson** [comment]
I just added some installation instructions, can you check your configuration against them: https://github.com/elixir-lsp/elixir-ls/#emacs

Also the wiki has more info https://elixirforum.com/t/emacs-elixir-setup-configuration-wiki/19196

If you're still having trouble you can check this to trace the communication between client and server: https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/

But if the issue is still persisting then it seems like some sort of `lsp-mode` issue of some sort and you may want to try asking at their gitter.im or raise an issue.

**Comment by x-ji** [comment]
Thanks for the reply and pointers. I set `lsp-log-io` to `t` and looked at the logs. I saw that `textDocument/hover` seems to have been correctly triggered and a response is received, e.g. 

```
[Trace - 09:35:52 PM] Sending request 'textDocument/hover - (190)'.
Params: {
  "textDocument": {
    "uri": "file:///Users/jx/test/backend/test/support/data_case.ex"
  },
  "position": {
    "line": 64,
    "character": 5
  }
}


[Trace - 09:35:52 PM] Received response 'textDocument/hover - (190)' in 31ms.
Result: {
  "range": {
    "start": {
      "line": 64,
      "character": 2
    },
    "end": {
      "line": 64,
      "character": 5
    }
  },
  "contents": "> Kernel.def(call, expr \\\\\\\\ [])\n\nDefines a public function with the given name and body.\n\n## Examples\n\n    defmodule Foo do\n      def bar, do: :baz\n    end\n\n    Foo.bar()\n    #=> :baz\n\nA function that expects arguments can be defined as follows:\n\n    defmodule Foo do\n      def sum(a, b) do\n        a + b\n      end\n    end\n\nIn the example above, a `sum/2` function is defined; this function receives\ntwo arguments and returns their sum.\n\n## Default arguments\n\n`\\\\` is used to specify a default value for a parameter of a function. For\nexample:\n\n    defmodule MyMath do\n      def multiply_by(number, factor \\\\ 2) do\n        number * factor\n      end\n    end\n\n    MyMath.multiply_by(4, 3)\n    #=> 12\n\n    MyMath.multiply_by(4)\n    #=> 8\n\nThe compiler translates this into multiple functions with different arities,\nhere `MyMath.multiply_by/1` and `MyMath.multiply_by/2`, that represent cases when\narguments for parameters with default values are passed or not passed.\n\nWhen defining a function with default arguments as well as multiple\nexplicitly declared clauses, you must write a function head that declares the\ndefaults. For example:\n\n    defmodule MyString do\n      def join(string1, string2 \\\\ nil, separator \\\\ \" \")\n\n      def join(string1, nil, _separator) do\n        string1\n      end\n\n      def join(string1, string2, separator) do\n        string1 <> separator <> string2\n      end\n    end\n\nNote that `\\\\` can't be used with anonymous functions because they\ncan only have a sole arity.\n\n## Function and variable names\n\nFunction and variable names have the following syntax:\nA _lowercase ASCII letter_ or an _underscore_, followed by any number of\n_lowercase or uppercase ASCII letters_, _numbers_, or _underscores_.\nOptionally they can end in either an _exclamation mark_ or a _question mark_.\n\nFor variables, any identifier starting with an underscore should indicate an\nunused variable. For example:\n\n    def foo(bar) do\n      []\n    end\n    #=> warning: variable bar is unused\n\n    def foo(_bar) do\n      []\n    end\n    #=> no warning\n\n    def foo(_bar) do\n      _bar\n    end\n    #=> warning: the underscored variable \"_bar\" is used after being set\n\n## `rescue`/`catch`/`after`/`else`\n\nFunction bodies support `rescue`, `catch`, `after`, and `else` as `Kernel.SpecialForms.try/1`\ndoes. For example, the following two functions are equivalent:\n\n    def format(value) do\n      try do\n        format!(value)\n      catch\n        :exit, reason -> {:error, reason}\n      end\n    end\n\n    def format(value) do\n      format!(value)\n    catch\n      :exit, reason -> {:error, reason}\n    end\n\n\n"
}
```

However, nothing pops up on my UI whatsoever.

The response I received from `vls` in comparison:

```
[Trace - 09:32:13 PM] Sending request 'textDocument/documentLink - (188)'.
Params: {
  "textDocument": {
    "uri": "file:///Users/jx/test/lib/templates/src/App.vue"
  }
}


[Trace - 09:32:13 PM] Received response 'textDocument/hover - (186)' in 42ms.
Result: {
  "range": {
    "end": {
      "character": 13,
      "line": 13
    },
    "start": {
      "character": 5,
      "line": 13
    }
  },
  "contents": [
    "The template element is used to declare fragments of HTML that can be cloned and inserted in the document by script\\."
  ]
}

```

I don't see the difference between these two responses that could potentially cause the popup to fail to show up in the first case. The only thing is that the response from `elixir-ls` is much longer and I wonder if there could be any configuration that prevented it from being shown because of that.

I also posted the question in the repo of `lsp-ui` https://github.com/emacs-lsp/lsp-ui/issues/478. Seems that this could be more of a `lsp-ui` related issue. I will close the issue here and post the results afterwards. Thanks again for the help.

**Comment by x-ji** [comment]
Resolved by https://github.com/elixir-lsp/elixir-ls/pull/342
