### ISSUE TITLE
Consider setting +sbwt none BEAM option 

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir-ls#328]
[This](https://www.ably.io/blog/beam-optimization-mqtt/) blog post suggests that the default value may not be appropriate for our needs. Disabling scheduller busy wait may help reducing excessive CPU usage.
The same may apply to +sbwtdcpu and +sbwtdio settings
See detailed docs in http://erlang.org/doc/man/erl.html

**Comment by axelson** [comment]
Looking at those options they make a bunch of sense for an application like ElixirLS. I'm trying them out now and I started a PR.

**Comment by axelson** [comment]
The only time I can think of it potentially not making sense would be if the language server is running under docker. But even there it will probably make sense.
