### ISSUE TITLE
Better emacs documentation

### ISSUE THREAD

**Issue by Jostar1024** [elixir-lsp/elixir-ls#330]
### Environment

* Elixir & Erlang versions (elixir --version): 
* Operating system: Window 10, WSL2
* Editor or IDE name (e.g. Emacs/VSCode): Doom Emacs
* Editor Plugin/LSP Client name: lsp-mode

### Troubleshooting

- [ ] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [ ] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

### Logs

1.  If using a client other than VS Code, please try VSCode's "ElixirLS: Elixir support and debugger" extension. Does it reproduce your failure?
2.  Create a new Mix project with `mix new empty`, then open that project with VS Code and open an Elixir file. Is your issue reproducible on the empty project? If not, please publish a repo on Github that does reproduce it.
3.  Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)
4.  Check the developer console by opening `Help > Toggle Developer Tools` and include any errors that look relevant.

----
I think the project needs some configuration document for emacs. Here is my setup on doom emacs.
1. follow the instruction on [this link](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-enable-lsp-support-for-insert-language-here)
2. You need to declare the path for elixir lsp in `~/.doom.d/config.el`
```elisp
(use-package lsp-mode
  :commands lsp
  :ensure t
  :diminish lsp-mode
  :hook
  (elixir-mode . lsp)
  :init
  (add-to-list 'exec-path "~/projects/elixir-ls/release"))
```
Then the elixir-ls in doomed emacs is properly set.

Ref:
https://elixirforum.com/t/emacs-elixir-setup-configuration-wiki/19196/25

**Comment by lukaszsamson** [comment]
Please open a PR

**Comment by lukaszsamson** [comment]
Docs has been reworked since this was opened
