### ISSUE TITLE
Otp 20 incompatability

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#336]
+sbwtdcpu none +sbwtdio none are not supported on Erlang 20

Need to partially revert #331

**Comment by axelson** [comment]
Or we can drop OTP 20 support. Which we probably should do anyway. It looks like the OTP team only supports three versions anyway. This is the best reference I can find so far: http://erlang.2086793.n4.nabble.com/OTP-Versions-and-Maint-Branches-td4722416.html

**Comment by lukaszsamson** [comment]
+1 on dropping support for otp 20
