### ISSUE TITLE
textDocument/publishDiagnostics try to send with un-opened uri to editor

### ISSUE THREAD

**Issue by wingyplus** [elixir-lsp/elixir-ls#348]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.11.0-dev (82c4c36) (compiled with Erlang/OTP 23)
* Operating system: macOS 10.15.6
* Editor or IDE name (e.g. Emacs/VSCode): neovim
* Editor Plugin/LSP Client name: vim-lsp

### Troubleshooting

Consider this [repository](https://github.com/wingyplus/diagnostics_bug).

* Create a new project with `mix`
* Create a new file named `lib/diagnostics_bug_unused.ex` directory with a 1 argument function that cause unused warning in elixir compiler
* Close an editor and open file `lib/diagnostics_bug.ex`. 
* See vim call error buffer is nil after ElixirLS try to send `textDocument/publishDiagnostics` with uri `"file:///Users/thanabodee/src/github.com/elixir-lsp/dianostics_bug/lib/dianostics_bug_unused.ex"`, which's not open in an editor.
* Open file `lib/diagnostics_bug_unused.ex`, vim call error disappear after received `textDocument/publishDiagnostics`.

### Logs

You can see vim-lsp log file [here](https://gist.github.com/wingyplus/5889fafc8a31bafffc39831fbcf8ff6e).

**Comment by lukaszsamson** [comment]
This seems to be vim-lsp problem. See [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_publishDiagnostics):

> if a language has a project system (for example C#) diagnostics are not cleared when a file closes

Elixir does have a project system. Moreover, editing .ex files outside of a mix project is currently supported

**Comment by wingyplus** [comment]
@lukaszsamson I think we can improve publish diagnostics by do not sending diagnostics for the file that the client doesn't send `textDocument/didOpen`. And Vim doesn't really close when we execute `:q` in the editor. This is make more sense?

**Comment by lukaszsamson** [comment]
This would be a big change to the current behaviour. I wouldn't turn it on by default but instead put it behind a config setting. However, I checked three other language servers (Typescript, C# and rust) and they all return diagnostics on not opened files from the project. I couldn't find any setting that would control this.

**Comment by wingyplus** [comment]
@lukaszsamson Thanks for your clarify. I'll open an issue on vim-lsp. :)
