### ISSUE TITLE
Feature request: Elixir completion in .(l)eex files

### ISSUE THREAD

**Issue by Whoops** [elixir-lsp/elixir-ls#357]
It would be very handy, at least for me, if Elixir-LS could do auto-completion/intellisense inside `<% ... %>` tags in .(l)eex files. This is one of those things I don't realize how much I use until suddenly it's not there.

**Comment by lukaszsamson** [comment]
Autocomplete works in `.eex`, `.leex`, `.heex` (at least in vscode). Is this still an issue?
