### ISSUE TITLE
Feature Request: support textDocument/foldingRange

### ISSUE THREAD

**Issue by wingyplus** [elixir-lsp/elixir-ls#358]
textDocument/foldingRange will be useful for editor outside vscode (such as vim, emacs, etc.). For example in my vim editor:

Folding top-level defmodule:

![Screen Shot 2563-08-24 at 22 51 11](https://user-images.githubusercontent.com/484530/91193724-a1a36b00-e721-11ea-95d3-3ef1a16b55b8.png)

Or folding on multiple defmodule in top-level file:
<img width="1430" alt="Screen Shot 2563-08-25 at 22 09 16" src="https://user-images.githubusercontent.com/484530/91193632-846e9c80-e721-11ea-8b9c-ea662a205a6b.png">

I have a prototype on https://github.com/wingyplus/elixir-ls/tree/folding which partially support for defmodule on the top level file. The implementation that I use is parse the `source_file` to the `Code.string_to_quoted/1` and traverse the AST. The it's not 100% correct because the AST that produces by `Code.string_to_quoted/1` is optimize in some case, For example: 

* AST doesn't have `end` keyword position 
* AST will produces the same for a function that has only 1 primitive value expression, For example:

```elixir
defmodule A do
  def hello() do
    :world
  end
end
Or

defmodule A do
  def hello(), do: :world
end
```

Those 2 module will produce:

```
{:defmodule, [line: 1],
   [
     {:__aliases__, [line: 1], [:A]},
     [do: {:def, [line: 2], [{:hello, [line: 2], []}, [do: :world]]}]
   ]}
```

The one possible solution is trying `:elixir.string_to_tokens` that's look have information that I needs but it change arity to 5 in Elixir version 1.11 which add start column. 

I appreciate to working on this because I really want to. But I need to hear your feedback first. :)

**Comment by wingyplus** [comment]
I implement by using `:elixir_tokenizer.tokenize/3` is better than using `Code.string_to_quoted/1` here https://github.com/wingyplus/elixir-ls/commit/2d9a94ceb22147ab9c2e128cf029519f8bc0c758. It has a little bit case need to handle but not too far.

**Comment by lukaszsamson** [comment]
elixir_sense provides a wrapper around elixir tokenizer that aims to deal with breaking changes between elixir releases

**Comment by wingyplus** [comment]
@lukaszsamson Nice! I will looking into elixir_sense and open an issue on that repo.

**Comment by wingyplus** [comment]
I think it make sense to add folding into elixir_sense. The issue already opened on elixir_sense repository.

**Comment by lukaszsamson** [comment]
@wingyplus are you still working on that?

**Comment by wingyplus** [comment]
@lukaszsamson I still working on this but it's in slow progress because I have less time to contribute to this project less than before.

**Comment by lukaszsamson** [comment]
Closing this as #492 is now merged. @wingyplus thanks for your invlovent.

**Comment by wingyplus** [comment]
Thanks to all people who involve this part. And sorry that I didn’t help as I expected. 🙇‍♂️
