### ISSUE TITLE
Compilation error in file lib/language_server/dialyzer/analyzer.ex

### ISSUE THREAD

**Issue by 0rzech** [elixir-lsp/elixir-ls#36]
### Environment

* Elixir & Erlang versions (elixir --version): `Elixir 1.8.2` @ `Erlang/OTP 20`
* Operating system: `Ubuntu 18.04.2`

### Problem Description

elixir-ls compilation (`mix compile`) on master and latest release fails with:
```
== Compilation error in file lib/language_server/dialyzer/analyzer.ex ==
** (RuntimeError) error parsing file /usr/lib/erlang/lib/dialyzer-3.2.3/src/dialyzer.hrl, got: {:error, :enoent}
    (elixir) lib/record/extractor.ex:84: Record.Extractor.read_file/2
    (elixir) lib/record/extractor.ex:50: Record.Extractor.extract_record/2
    lib/language_server/dialyzer/analyzer.ex:42: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

**Comment by axelson** [comment]
Hmm, that seems likely to be an issue related to how you've installed elixir and erlang. 

Can you try installing elixir and erlang via asdf and see if you still have that error? You can follow the installation instructions for asdf and then the two plugins:
* https://github.com/asdf-vm/asdf
* https://github.com/asdf-vm/asdf-elixir/
* https://github.com/asdf-vm/asdf-erlang

**Comment by 0rzech** [comment]
Yeah, it looks like [erlang-dialyzer](https://packages.ubuntu.com/bionic/erlang-dialyzer) package does not contain source code at all: https://packages.ubuntu.com/bionic/amd64/erlang-dialyzer/filelist. Is it considered a bug in Erlang world? If yes, I could file a bug report.

**Comment by 0rzech** [comment]
You're right. The solution was to install `erlang-src` package.

**Comment by axelson** [comment]
I'm glad you were able to figure it out!
