### ISSUE TITLE
 Unable to get formatter options

### ISSUE THREAD

**Issue by alappe** [elixir-lsp/elixir-ls#365]
I'm having an issue with the formatter not working in umbrellas anymore. I also tried with the latest `master`, specifically `v0.5.0-75-gb39509a` hoping that  #350 would fix it but with the same outcome.

### Environment

* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 22 [erts-10.7.2.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.10.4 (compiled with Erlang/OTP 21)
```
* Operating system: macOS 10.15.6
* Editor or IDE name (e.g. Emacs/VSCode): neovim
* Editor Plugin/LSP Client name: coc.nvim

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

### Logs

From `:CocInfo` within vim:

```
 │   77 ## Output channel: elixir
 │   78
 │   79 Started ElixirLS v0.5.0
 │   80 Elixir version: "1.10.4 (compiled with Erlang/OTP 21)"
 │   81 Erlang version: "22"
 │   82 ElixirLS compiled with Elixir 1.9.4 and erlang 21
 │   83 MIX_ENV: test
 │   84 MIX_TARGET: host
 │   85 [Warn  - 3:51:58 PM] warning: Unable to get formatter options for /Users/nd/src/foofus/apps/foofus/lib/foofus_web/live/user_profile_live.ex: Unknown dependency :phoenix given to :import_deps in the format
 │   86   (language_server 0.5.0) lib/language_server/source_file.ex:226: ElixirLS.LanguageServer.SourceFile.formatter_opts/1
 │   87   (language_server 0.5.0) lib/language_server/providers/formatting.ex:11: ElixirLS.LanguageServer.Providers.Formatting.format/3
 │   88   (language_server 0.5.0) lib/language_server/server.ex:568: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
 │   89
 │   90 [Error  - 3:51:58 PM] Request textDocument/formatting failed.
 │   91   Message: Unable to fetch formatter options
 │   92   Code: -32603
```

`.formatter.exs` in umbrella root:

```
# Used by "mix format"
[
  inputs: ["mix.exs", "config/*.exs"],
  subdirectories: ["apps/*"]
]
```

`.formatter.exs` in umbrella child `foofus`:

```
[
  import_deps: [:phoenix],
  inputs: ["*.{ex,exs}", "{config,lib,test}/**/*.{ex,exs}"]
]
```

phoenix related deps in `mix.exs` of `foofus`:

```
   44       {:phoenix, "~> 1.5.1"},
   45       {:phoenix_html, "~> 2.11"},
   46       {:phoenix_live_view, "~> 0.14.4"},
   47       {:phoenix_live_reload, "~> 1.2", only: :dev},
```

**Comment by wingyplus** [comment]
If I understand it correctly, this issue happens because of ElixirLS aren't start to fetch dependencies into deps cache or are in fetching state. That's why it shows `Unknown dependency :phoenix given to :import_deps in the format` error message.

**Comment by axelson** [comment]
Thanks for the report! Do you have a sample app that reproduces this behavior? That would be helpful for testing it.

**Comment by alappe** [comment]
Meh, actually I don't at the moment. Now the indenting does not work but I do not see the error any more :-(

I'll close the issue for now and might reopen it, if I can reproduce the issue in a sample app.

Sorry for bothering you.

**Comment by axelson** [comment]
Okay, sounds good. FYI, indenting is usually handled by an editor plugin (although you can use ElixirLS to format the whole file which takes care of indentation after the fact)

**Comment by bitboxer** [comment]
I have the same issue right now in a project and am not sure what is producing this. Is there a way to debug this to get more information that is helpful here? Building a sample project sadly did not help. There is something wrong in my current project.
