### ISSUE TITLE
Debugging a single file

### ISSUE THREAD

**Issue by crberube** [elixir-lsp/elixir-ls#366]
### Environment

* Elixir & Erlang versions (elixir --version): 1.10.4
* Operating system: Linux (Debian)
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name: ElixirLS debugger v0.5.0

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

### Description

I am trying to set up a debug launch configuration which only runs tests for the currently open file. In order to ensure the issue is not with VSCode variables, I have used a static file path. I've tried passing the file in as an option to `taskArgs` as well as changing the `requireFiles` to only include the file in question. No matter what I do, the debugger runs through all of the test files in the project.

Does ElixirLS support this use case? If so, how could I achieve the desired result?

**Comment by lukaszsamson** [comment]
I can confirm it doesn't work with task arg `test/some_test.exs`. It does with `test/some_test.exs:12`.

**Comment by lukaszsamson** [comment]
After more investigation it seems that `mix test some_test.exs` will not honour `some_test.exs` task param when there are other `*_test.exs` files required by `requireFiles` option in launch config. Please note that the default one requires
```
"requireFiles": [
    "test/**/test_helper.exs",
    "test/**/*_test.exs"
  ]
```
The workaround is to only require the file you want to debug or not require `*_test.exs` at all. The downside is that you won't be able to set breakpoints in not required `.exs` - as pointed out in the readme.

I'll update the readme with the workaround.

@josevalim If you believe it may be a mix issue please let me know

**Comment by josevalim** [comment]
The require files should only be the test helper, at least is its purpose on Mix. The others are loaded on demand depending on what is being tested. While are all test files being required?

**Comment by lukaszsamson** [comment]
If the files are not required `:int` will not accept breakpoints with error
** Invalid beam file or no abstract code: 'Elixir.SomeTest'
see
https://github.com/elixir-lsp/elixir-ls/blob/99b6d7800b253f1c06a81bd29455b557a1243505/apps/elixir_ls_debugger/lib/debugger/server.ex#L671

**Comment by josevalim** [comment]
Unfortunately I do not know how the debugger works to have an opinion on that. All I can say though is that, if you require the test files, then they will be required, and it is not the job of `mix` to filter the list you asked it to load. :)
