### ISSUE TITLE
The server is not respecting the locals_without_parens rules in the Elixir project itself.

### ISSUE THREAD

**Issue by eksperimental** [elixir-lsp/elixir-ls#369]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir master, OTP 23
* Operating system: Linux
* Editor or IDE name (e.g. Emacs/VSCode): SublimeText 3
* Editor Plugin/LSP Client name: LSP-Elixir

It is not a Mix project, but it will be cool if the LS server could support Elixir core.
Please see the discussion.
https://github.com/elixir-lang/elixir/pull/10389#issuecomment-703057978
https://github.com/elixir-lang/elixir/pull/10389/files#diff-9ff5e42a2e18294ba5812f3aafca3bf9

`assert_eval_raise` is listed in `locals_without_parens`

Thank you

**Comment by lukaszsamson** [comment]
If the elixir core team is interested in submitting a PR then we could merge it. Otherwise, I am against adding support for a highly non standard project layout as it's going to be a maintenance burden with no benefit for most of users.
IMO, if we are to support non mix projects then https://github.com/elixir-lsp/elixir-ls/issues/307 should be prioritised higher.

**Comment by eksperimental** [comment]
Fair enough. Is there a way to disable the formatting for a specific folder and subfolders?

**Comment by lukaszsamson** [comment]
I guess this should work for a workspace: `"editor.formatOnSave": false` in `project/.vscode/settings.json`.
More options in https://stackoverflow.com/questions/44831313/how-to-exclude-files-from-format-on-save-in-vscode/44831631#44831631

**Comment by eksperimental** [comment]
> I guess this should work for a workspace: `"editor.formatOnSave": false` in `project/.vscode/settings.json`.
> More options in https://stackoverflow.com/questions/44831313/how-to-exclude-files-from-format-on-save-in-vscode/44831631#44831631

Sorry, I am in SublimeText 3

**Comment by lukaszsamson** [comment]
Sorry, I somehow assumed that You are using vscode. Not sublime user here but there is `lsp_format_on_save` setting (https://lsp.readthedocs.io/en/latest/features/). It's the editor that issues a format command. The language server only reports if it is supported.

**Comment by eksperimental** [comment]
> `lsp_format_on_save`

Thank you. That is exactly what I used for now, but that disables the formatting for all the projects. I once I am done editing Elixir core, I need to set it back on again.

Is there a way to list the directories that you want to be excluded from the formatting?

**Comment by lukaszsamson** [comment]
> Is there a way to list the directories that you want to be excluded from the formatting?

Currently not. As I wrote before it's the editor that requests formatting.

**Comment by eksperimental** [comment]
> > Is there a way to list the directories that you want to be excluded from the formatting?
> 
> Currently not. As I wrote before it's the editor that requests formatting.

thank you.

**Comment by eksperimental** [comment]
I have come up with a solution.
Run these commands in the `elixir` root folder
It creates symbolic links to the formatter file, and excludes them from your Git's view

```console
for file in lib/{elixir,eex,ex_unit,iex,logger,mix}/.formatter.exs; do
  ln -s ../../.formatter.exs ${file} &&
  echo $file >> .git/info/exclude;
done
```
