### ISSUE TITLE
Language Server Crashing. Dialyzer failing to complete PLT build

### ISSUE THREAD

**Issue by crberube** [elixir-lsp/elixir-ls#376]
### Environment

* Elixir & Erlang versions (elixir --version): 1.10.4
* Operating system: Debian GNU/Linux 10 (buster)
* Editor or IDE name (e.g. Emacs/VSCode): VSCode 1.49.3
* Editor Plugin/LSP Client name: ElixirLS v0.6.0

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

### Logs
Started ElixirLS v0.6.0
Elixir version: "1.10.4 (compiled with Erlang/OTP 22)"
Erlang version: "22"
ElixirLS compiled with Elixir 1.8.2 and erlang 21
MIX_ENV: test
MIX_TARGET: 
[Error - 6:47:29 PM] Request textDocument/documentSymbol failed.
  Message: [DocumentSymbols] Compilation error while parsing source file
  Code: -32000 
[Info  - 6:47:31 PM] Compile took 5878 milliseconds
[Info  - 6:47:31 PM] [ElixirLS WorkspaceSymbols] Indexing...
[Info  - 6:47:31 PM] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 6:47:31 PM] [ElixirLS WorkspaceSymbols] Module discovery complete
[Info  - 6:47:33 PM] [ElixirLS WorkspaceSymbols] 67 callbacks added to index
[Info  - 6:47:43 PM] [ElixirLS WorkspaceSymbols] 516 modules added to index
[Info  - 6:47:44 PM] [ElixirLS Dialyzer] Found 1542 changed files in 11939 milliseconds
MIX_ENV: test
MIX_TARGET: 
[Info  - 6:47:46 PM] [ElixirLS WorkspaceSymbols] 523 types added to index
[Info  - 6:47:55 PM] Compile took 10090 milliseconds
[Info  - 6:47:55 PM] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 6:48:07 PM] [ElixirLS Dialyzer] Found 1542 changed files in 10756 milliseconds
MIX_ENV: test
MIX_TARGET: 
[Info  - 6:48:18 PM] Compile took 10408 milliseconds
[Info  - 6:48:18 PM] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 6:48:24 PM] [ElixirLS Dialyzer] Found 1542 changed files in 5746 milliseconds
[Info  - 6:48:26 PM] [ElixirLS WorkspaceSymbols] 8306 functions added to index
[Info  - 6:53:47 PM] Connection to server got closed. Server will restart.
[Error - 6:53:48 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/root/.vscode-server/extensions/jakebecker.elixir-ls-0.6.1/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/root/.vscode-server/extensions/jakebecker.elixir-ls-0.6.1/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/root/.vscode-server/extensions/jakebecker.elixir-ls-0.6.1/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/root/.vscode-server/extensions/jakebecker.elixir-ls-0.6.1/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/root/.vscode-server/extensions/jakebecker.elixir-ls-0.6.1/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/root/.vscode-server/extensions/jakebecker.elixir-ls-0.6.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/root/.vscode-server/extensions/jakebecker.elixir-ls-0.6.1/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/root/.vscode-server/extensions/jakebecker.elixir-ls-0.6.1/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/root/.vscode-server/extensions/jakebecker.elixir-ls-0.6.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/root/.vscode-server/extensions/jakebecker.elixir-ls-0.6.1/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageReader.fireClose (/root/.vscode-server/extensions/jakebecker.elixir-ls-0.6.1/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/root/.vscode-server/extensions/jakebecker.elixir-ls-0.6.1/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)
Started ElixirLS v0.6.0
Elixir version: "1.10.4 (compiled with Erlang/OTP 22)"
Erlang version: "22"
ElixirLS compiled with Elixir 1.8.2 and erlang 21
MIX_ENV: test
MIX_TARGET: 
... etc.

**Comment by subsetpark** [comment]
I think I'm encountering the same error. 

This is calling `language_server.sh` directly, after unpacking the release DLed from Github. Here's the traceback:

```
12:29:04.403 [error] GenServer ElixirLS.LanguageServer.Server terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for true of type Atom
    (elixir 1.10.3) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.10.3) lib/enum.ex:141: Enumerable.reduce/3
    (elixir 1.10.3) lib/enum.ex:3383: Enum.map/2
    (language_server 0.6.0) lib/language_server/server.ex:626: ElixirLS.LanguageServer.Server.dialyze/1
    (language_server 0.6.0) lib/language_server/server.ex:651: ElixirLS.LanguageServer.Server.handle_build_result/3
    (language_server 0.6.0) lib/language_server/server.ex:116: ElixirLS.LanguageServer.Server.handle_cast/2
    (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6
Last message: {:"$gen_cast", {:build_finished, {:ok, []}}}
State: %ElixirLS.LanguageServer.Server{analysis_ready?: false, awaiting_contracts: [], build_diagnostics: [%Mix.Task.Compiler.Diagnostic{compiler_name: "Elixir", details: nil, file: "/home/zax/frame-src/massdriver/apps/core/lib/core/projects/media/aws/pipeline_requests/pipeline_request.ex", message: "Core.Projects.MediaServices.PipelineRequest.PublisherMock.send_to/2 is undefined (module Core.Projects.MediaServices.PipelineRequest.PublisherMock is not available or is yet to be defined)", position: 10, severity: :warning}], build_ref: #Reference<0.1412704742.1289486337.247509>, build_running?: true, client_capabilities: %{"textDocument" => %{"callHierarchy" => %{"dynamicRegistration" => false}, "codeAction" => %{"codeActionLiteralSupport" => %{"codeActionKind" => %{"valueSet" => ["", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports"]}}, "dynamicRegistration" => true, "isPreferredSupport" => true}, "completion" => %{"completionItem" => %{"documentationFormat" => ["markdown"], "resolveAdditionalTextEditsSupport" => true, "snippetSupport" => true}, "contextSupport" => true}, "declaration" => %{"linkSupport" => true}, "definition" => %{"linkSupport" => true}, "documentLink" => %{"dynamicRegistration" => true, "tooltipSupport" => true}, "documentSymbol" => %{"hierarchicalDocumentSymbolSupport" => true, "symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, "foldingRange" => %{"dynamicRegistration" => true}, "formatting" => %{"dynamicRegistration" => true}, "hover" => %{"contentFormat" => ["markdown", "plaintext"]}, "implementation" => %{"linkSupport" => true}, "publishDiagnostics" => %{"relatedInformation" => true, "tagSupport" => %{"valueSet" => [1, 2]}, "versionSupport" => true}, "rangeFormatting" => %{"dynamicRegistration" => true}, "rename" => %{"dynamicRegistration" => true, "prepareSupport" => true}, "signatureHelp" => %{"signatureInformation" => %{"parameterInformation" => %{"labelOffsetSupport" => true}}}, "synchronization" => %{"didSave" => true, "willSave" => true, "willSaveWaitUntil" => true}, "typeDefinition" => %{"linkSupport" => true}}, "window" => %{"workDoneProgress" => true}, "workspace" => %{"applyEdit" => true, "configuration" => true, "didChangeWatchedFiles" => %{"dynamicRegistration" => true}, "executeCommand" => %{"dynamicRegistration" => false}, "symbol" => %{"symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, "workspaceEdit" => %{"documentChanges" => true, "resourceOperations" => ["create", "rename", "delete"]}, "workspaceFolders" => true}}, dialyzer_diagnostics: [], dialyzer_sup: #PID<0.125.0>, load_all_modules?: false, needs_build?: false, project_dir: "/home/zax/frame-src/massdriver", received_shutdown?: false, requests: %{}, root_uri: "file:///home/zax/frame-src/massdriver", server_instance_id: "kvHlWO8b-SPJKYHi8fmfdh7_I_KuUbvR", settings: %{"dialyzerEnabled" => true, "dialyzerFormat" => "dialyxir_long", "dialyzerWarnOpts" => true, "fetchDeps" => true, "mixEnv" => "test", "signatureAfterComplete" => true, "suggestSpecs" => true}, source_files: %{"file:///home/zax/frame-src/massdriver/apps/core/lib/core/cache.ex" => %ElixirLS.LanguageServer.SourceFile{dirty?: false, text: "defmodule Core.MultilevelCache do\n  use Nebulex.Cache,\n    otp_app: :core,\n    adapter: Nebulex.Adapters.Multilevel\n\n  use Nebulex.Cache.Stats\n\n  def telemetry_events do\n    [:stats, :size]\n    |> Enum.map(&([:cache, :local] ++ [&1]))\n  end\n\n  def dispatch_cache_size do\n    :telemetry.execute(\n      [:cache, :local, :size],\n      %{value: size()},\n      %{cache: __MODULE__}\n    )\n  end\n  def dispatch_memory_info do\n    :telemetry.execute(\n      [:cache, :local, :size],\n      %{value: size()},\n      %{cache: __MODULE__}\n    )\n  end\nend\n\ndefmodule Core.Cache do\n  require Logger\n  alias Core.Memcache\n\n  @doc \"\"\"\n  Remove a key from the cache.\n  \"\"\"\n  def delete(prefixes, args) when is_list(prefixes),\n    do: Enum.map(prefixes, &delete(&1, args))\n\n  def delete(prefix, args) do\n    cache_key(prefix, args)\n    |> Memcache.delete()\n  end\n\n  @doc \"\"\"\n  Set a key in the cache.\n  \"\"\"\n  def set(prefix, args, value, opts \\\\ []) do\n    cache_key(prefix, args)\n    |> Memcache.set(value, opts)\n  end\n\n  @doc \"\"\"\n  Get a key from the cache, or nil if the key doesn't exist or if the\n  operation fails.\n  \"\"\"\n  def safe_get(key) do\n    try do\n      case Memcache.get(key) do\n        {:ok, result} -> result\n        _ -> nil\n      end\n    catch\n      :exit, _ -> nil\n    end\n  end\n\n  @doc \"\"\"\n  Caches a bulk result by generating keys for all the items in the first\n  arg in `args` (must be a list), mget'ing against them, then calling\n  `fun` on the missing items and mset'ing them back in the cache.\n  \"\"\"\n  def all_cached(prefix, args, fun, opts \\\\ [])\n\n  def all_cached(prefix, [cache_items | args], fun, opts)\n      when is_list(cache_items) and is_function(fun) do\n    if Keyword.get(opts, :cache, true) do\n      bulk_cached(prefix, cache_items, fun, args)\n    else\n      apply(fun, args)\n    end\n  end\n\n  @doc \"\"\"\n  Reads a cached result of an anonymous function, or executes it and\n  writes back to the cache\n  \"\"\"\n  def cached(prefix, args, fun, opts \\\\ [])\n\n  def cached(prefix, args, fun, opts) when is_list(args) and is_function(fun) do\n    if should_cache?(args) && Keyword.get(opts, :cache, true) do\n      cache_key(prefix, args)\n      |> with_cache(fun, args)\n    else\n      apply(fun, args)\n    end\n  end\n\n  def cached(prefix, arg, fun, opts), do: cached(prefix, [arg], fun, opts)\n\n  @doc \"\"\"\n  Retrieve an arbitrary value from the cache.\n  \"\"\"\n  @spec fetch(atom, any) :: {:ok, any} | nil\n  def fetch(prefix, args) do\n    try do\n      with true <- should_cache?(args),\n           {:ok, result} <- cache_key(prefix, args) |> Memcache.get() do\n        result\n      else\n        _ -> nil\n      end\n    catch\n      :exit, _ -> nil\n    end\n  end\n\n  @doc \"\"\"\n  Determine whether an arbitrary value is cacheable.\n  \"\"\"\n  def should_cache?([l | rest]) when is_list(l),\n    do: Enum.all?(l, &should_cache?/1) && should_cache?(rest)\n\n  def should_cache?([%{id: id} | rest]), do: !!id && should_cache?(rest)\n  def should_cache?([nil | _]), do: false\n  def should_cache?([val | rest]) when is_binary(val) or is_atom(val), do: should_cache?(rest)\n  def should_cache?([]), do: true\n  def should_cache?(_), do: false\n\n  def with_cache(key, fun, args \\\\ []) do\n    try do\n      Memcache.get(key)\n      |> case do\n        {:ok, result} when not is_nil(result) -> result\n        _ -> apply(fun, args) |> cache_result(key)\n      end\n    catch\n      :exit, _ -> apply(fun, args)\n    end\n  end\n\n  def cache_key(prefix, args) when is_list(args),\n    do: \"\#{prefix}_\#{Enum.map(args, &cache_part/1) |> Enum.join(\"_\")}\"\n\n  def cache_key(prefix, arg), do: \"\#{prefix}_\#{cache_part(arg)}\"\n\n  defp bulk_cached(prefix, items, fun, args) do\n    try do\n      items\n      |> Enum.map(&cache_key(prefix, &1))\n  (truncated)

```

**Comment by lukaszsamson** [comment]
@crberube Could you create a repository reproducing the issue?

@subsetpark How did you end up with `"dialyzerWarnOpts" => true` in your settings? This particular setting expects a list of strings. VSCode extension has a proper validation btw.

**Comment by subsetpark** [comment]
@lukaszsamson Thank you for pointing that out! I got that from the Elixir documentation in emacs `lsp-mode`. That said, I might have simply misunderstood the documentation that led to that config, or the documentation might have been inaccurate at the time. I'll update it and see if it removes that particular error.
