### ISSUE TITLE
Formatting doesn't work anymore on Windows 10 with version 0.6.1.

### ISSUE THREAD

**Issue by WernerBuchert** [elixir-lsp/elixir-ls#377]
### Environment

* Elixir & Erlang versions (elixir --version): 1.110 and also 1.10.4
* Operating system: Windows 10
* Editor or IDE name (e.g. Emacs/VSCode): VSCode 1.49.3
* Editor Plugin/LSP Client name: 0.6.1

### Troubleshooting

- [ ] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [ ] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

I've deleted the .elixir-ls directory two times, but no change; also disabling and reinstall does not help.

### Logs
No logs.

The ElixirFormatter doesn't work anymore, that is, it does really nothing. 
But there is also no error message and the Elixir source code is error-free.
This happened after updating to version 0.6.1. But on Linux it works with version 0.6.1.
Any advice?

**Comment by lukaszsamson** [comment]
Closing as it's already tracked in https://github.com/elixir-lsp/elixir-ls/pull/375
