### ISSUE TITLE
Code formatting is slow in large projects

### ISSUE THREAD

**Issue by arjan** [elixir-lsp/elixir-ls#378]
In a larg(ish) project of mine I noticed that formatting is suddenly very slow.
I narrowed it down to the call to `ElixirLS.LanguageServer.Providers.Formatting.should_format?/4`.

[That function](https://github.com/elixir-lsp/elixir-ls/blob/master/apps/language_server/lib/language_server/providers/formatting.ex#L50) expands all globs from the `inputs` parameter in the `.formatter.exs` config. In my case, one of the globs results in a list of 730 files; the call to `Path.wildcard` taking about 7 seconds.

This all seems very excessive to me, just to check whether a single file should be formatted or not.

A better approach might be to convert the glob definitions from the `inputs` option into a list of regular expressions, and then test the filename against those regexes. WDYT?

I can PR this if this is an agreeable solution.

### Environment

* Elixir & Erlang versions (elixir --version): 1.10.3
* Operating system: Arch Linux 
* Editor or IDE name (e.g. Emacs/VSCode):  Emacs
* Editor Plugin/LSP Client name: lsp-mode

**Comment by arjan** [comment]
And only now I realize that [converting globs to regexes is not a trivial task](https://github.com/fitzgen/glob-to-regexp/blob/master/index.js)... 😅

**Comment by lukaszsamson** [comment]
I like the idea with regexes, we already use it to some extent in debugger. 7s is really slow but this function needs some bugfixing besides optimisation. See https://github.com/elixir-lsp/elixir-ls/pull/362

**Comment by princemaple** [comment]
Elixir core is doing the same thing, https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/format.ex#L362-L364. I don't think expanding a glob to 3 digit number of items or finding an item in a sub 1k list would take 7s?

**Comment by arjan** [comment]
Was also quite stunned by this but apparently it is slow. Confirmed that it has to do with the two `node_modules` directories in my umbrella application (each containing some 100k files.. thank you npm ecosystem); if I remove those, the glob is in the 100ms range.

**Comment by arjan** [comment]
I'll try to see if I can get somewhere with the regex approach, and see if #362 could be fixed with this as well.

**Comment by princemaple** [comment]
the easiest solution is probably to update your inputs or your directory structure to prevent glob/wildcard from probing into your node_modules directory. parsing the glob and expand it into an equivalent regex is a lot harder.

**Comment by arjan** [comment]
True.. but the default inputs glob in `.formatter.exs` will cause this to be a pitfall for potentially all projects.

**Comment by princemaple** [comment]
`inputs: ["*.{ex,exs}", "priv/*/seeds.exs", "{config,lib,test}/**/*.{ex,exs}"]`
Really? Do you have your node_modules in `lib` or `priv`?

**Comment by arjan** [comment]
No of course not... they are under assets/. But the `Path.wildcard` is considerably faster if I remove them from the project altogether.

**Comment by arjan** [comment]
Hmm, actually, you are right.. my own glob was too wide, the default one seems OK.

**Comment by princemaple** [comment]
And what does your `inputs` look like?

**Comment by princemaple** [comment]
Yup, improvements on that will probably help a lot. XD

**Comment by princemaple** [comment]
@lukaszsamson FYI this is more likely a non issue?

**Comment by arjan** [comment]
Agreed.. but still the approach of doing a glob just to check one file might still cause issues in large repositories. But I'll close this one for now.
