### ISSUE TITLE
request: add a line break to the end of modules

### ISSUE THREAD

**Issue by chapmanjacobd** [elixir-lsp/elixir-ls#393]
I'm sure everyone has gotten used to it but as a beginner to elixir it feels more clean to have some separation:

status quo:

```elixir
defmodule HelloWeb.PageController do
  use HelloWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end
```

my radical proposal:

```elixir
defmodule HelloWeb.PageController do
  use HelloWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end

end
```

well... I guess it doesn't look _that_ much better but it feels better when there is more than one def. This is probably a controversial opinion so I am fine to keep using:

```
  #
end
```

I just want to present this alternative idea

**Comment by lukaszsamson** [comment]
I get it you mean format on save formatting style. If so, elixir-ls uses standard builtin elixir formatter and we have no plans to change it. If you would like to see any changes to it, please use elixir mailing list for feature discussions.
