### ISSUE TITLE
Protocol has already been consolidated warnings

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir-ls#395]
### Environment

* Elixir & Erlang versions (elixir --version): 1.11

Originally reported in https://github.com/elixir-ecto/ecto/issues/3464 but not related to ecto (https://github.com/elixir-ecto/ecto/issues/3464#issuecomment-718980007)

**Comment by 23Skidoo** [comment]
Adding `consolidate_protocols: Mix.env() != :test` to `mix.exs` appears to be the workaround.

**Comment by crbelaus** [comment]
This has been confirmed as a Phoenix bug and solved upstream (check [this comment](https://github.com/elixir-ecto/ecto/issues/3464#issuecomment-721915263)).

So I think that this issue can be safely closed.

**Comment by crbelaus** [comment]
The Phoenix part of this bug has been fixed in v1.5 and master ([check this comment][1]). This is fixed in phoenixframework/phoenix@b5580e9.

Maybe this can be useful for applying the same fix into ElixirLS.

[1]: https://github.com/elixir-ecto/ecto/issues/3464#issuecomment-721915263
