### ISSUE TITLE
Customize project compilation?

### ISSUE THREAD

**Issue by kenny-evitt** [elixir-lsp/elixir-ls#398]
### Environment

* Elixir & Erlang versions (elixir --version): 

```
Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.10.4 (compiled with Erlang/OTP 21)
```

* Operating system: macOS Mojave 10.14.6 (18G103)
* Editor or IDE name (e.g. Emacs/VSCode): VimR (Neovim)
* Editor Plugin/LSP Client name: [coc-elixir](https://github.com/elixir-lsp/coc-elixir)

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [ ] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

[I'm willing to do this but I don't *think* it's necessary or particularly useful for my issue.]

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

### Logs

1.  If using a client other than VS Code, please try VSCode's "ElixirLS: Elixir support and debugger" extension. Does it reproduce your failure?
2.  Create a new Mix project with `mix new empty`, then open that project with VS Code and open an Elixir file. Is your issue reproducible on the empty project? If not, please publish a repo on Github that does reproduce it.
3.  Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)
4.  Check the developer console by opening `Help > Toggle Developer Tools` and include any errors that look relevant.

[Again, I'm willing to do the above, but I don't *think* any of these steps are necessary or particularly useful for my issue.]

In the coc-elixir logs I'm seeing output like this:

```
...

==> phoenix_live_dashboard
Compiling 33 files (.ex)

== Compilation error in file lib/phoenix/live_dashboard/layout_view.ex ==
** (UndefinedFunctionError) function Appsignal.Phoenix.Template.EExEngine.compile/2 is undefined (module Appsignal.Phoenix.Template.EExEngine is not available)
    Appsignal.Phoenix.Template.EExEngine.compile("lib/phoenix/live_dashboard/templates/layout/dash.html.eex", "dash.html")
    (phoenix 1.5.4) lib/phoenix/template.ex:351: Phoenix.Template.compile/3
    (phoenix 1.5.4) lib/phoenix/template.ex:166: anonymous fn/4 in Phoenix.Template."MACRO-__before_compile__"/2
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix 1.5.4) expanding macro: Phoenix.Template.__before_compile__/1
    lib/phoenix/live_dashboard/layout_view.ex:1: Phoenix.LiveDashboard.LayoutView (module)
[Warn  - 6:06:25 PM] could not compile dependency :phoenix_live_dashboard, "mix compile" failed. You can recompile this dependency with "mix deps.compile phoenix_live_dashboard", update it with "mix deps.update phoenix_live_dashboard" or clean it with "mix deps.clean phoenix_live_dashboard"

```

This is – sadly! – a known issue with my project.

For a full/post-clean compile, I *need* to first run `mix deps.compile problem-dep --include-children` *before* I can (successfully) run `mix compile`. Is there some way I can configure ElixirLS to do this? Or is there a way I could 'manually' do this outside of ElixirLS?

**Comment by lukaszsamson** [comment]
If you came up with a PR we would consider it but it would be a maintenance burden with little help to most users. Please consider other ways: setting an alias on `mix compile` (that's what elixir-ls is calling). Ultimately, fixing the `problem-dep` or isolating the problem and reporting it upstream is going to be more beneficial to the community.

**Comment by kenny-evitt** [comment]
@lukaszsamson Thanks for the feedback!

I can fully appreciate that this *is* a relatively low-value request for almost all users.

Sadly, aliasing `mix compile` was more trouble than it was worth. I think (IIRC) that it effectively caused every compile to be a full/clean compile, for my project's code anyways.

The problem with the `problem-dep` is known, i.e. reported upstream and fixed in a development branch (again IIRC). This situation *should* be temporary as-is.

Is there any way I could manually workaround this for now? I.e. some way I could manually run `mix deps.compile problem-dep --include-children` for the copy of my project ElixirLS makes? That would be entirely sufficient as a temporary workaround.

**Comment by axelson** [comment]
@kenny-evitt You could try editing your mix.exs to have `build_path: ".elixir_ls/build"`, then closing your editor, removing your `.elixir_ls` directory and running `MIX_ENV=test mix deps.compile appsignal --include-children`, Then remove the `build_path` from your mix.exs and use your editor normally. Although you'd have to redo these steps if you ever clear out your `.elixir_ls` directory.

Although I wonder if there is some way you could make use of this snippet from `mix help deps.compile`, but as far as I know you can't set the project's build_path from the command line:
```
The compilation can be customized by passing a compile option in the
dependency:

    {:some_dependency, "0.1.0", compile: "command to compile"}
```

**Comment by kenny-evitt** [comment]
@axelson Thanks! I'll try the `:build_path` trick soon and let you know if I got it working.

I *think* the snippet won't help because the problem with the `problem_dep` is that it needs to be compiled before another dependency but that's not supported by Mix.

Here's the upstream issue by the way:

- [Compilation issues with Phoenix Live Dashboard · Issue #319 · appsignal/appsignal-elixir](https://github.com/appsignal/appsignal-elixir/issues/319#issuecomment-709813531)

**Comment by kenny-evitt** [comment]
@axelson That seemed to do the trick – the `:build_path` trick in particular! Thanks again!

**Comment by kenny-evitt** [comment]
@axelson Newer versions of Mix support a `MIX_BUILD_PATH` environment variable so I think I can compile `appsignal` via:

```
$ MIX_ENV=test MIX_BUILD_PATH=".elixir_ls/build/test" mix deps.compile appsignal --include-children
```

I'll try that when I get a chance.

**Comment by axelson** [comment]
Ah, I wasn't aware of that environment variable. That's probably an easier/better approach.

**Comment by kenny-evitt** [comment]
The `MIX_BUILD_PATH` environment variable didn't work for just now when I tried it:

```
$ MIX_ENV=test MIX_BUILD_PATH=".elixir_ls/build" mix deps.compile appsignal --include-children
...
===> Compiling certifi
===> Compiling src/certifi.erl failed
src/certifi.erl:none: undefined parse transform 'ct_expand'

==> partially
** (Mix) Could not compile dependency :certifi, "/Users/kenny/.asdf/installs/elixir/1.10.4/.mix/rebar3 bare compile --paths=".elixir_ls/build/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile certifi", update it with "mix deps.update certifi" or clean it with "mix deps.clean certifi"
```

Adding `build_path: ".elixir_ls/build"` to the output of `project/0` in my `mix.exs` file DID work tho.

For context, we just updated the _Erlang_ version for our project, which is what I'm guessing necessitated me using this workaround again.
