### ISSUE TITLE
Wrongly reported error with Ecto Query.API used along with custom macro

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-lsp/elixir-ls#409]
### Environment

* Elixir & Erlang versions (elixir --version): 
```
elixir --version
Erlang/OTP 23 [erts-11.1.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.11.2 (compiled with Erlang/OTP 23)
```
* Operating system: MacOS
* Editor or IDE name (e.g. Emacs/VSCode): Atom/VSCode
* Editor Plugin/LSP Client name: 

### Code

```
    queryable
    |> where(
      [contact: contact],
      weighted_fulltext_search(
        [
          {contact.first_name, "A"},
          {contact.last_name, "A"},
          {contact.title, "B"},
          {contact.name_prefix, "C"}
        ],
        ^search_query
      ) or
        ilike(type(contact.phone_numbers, :string), ^search_query_ilike) or
        ilike(type(contact.emails, :string), ^search_query_ilike)
    )
```

### Error

```
(ArgumentError) expected a keyword list, but an entry in the list is not a two-element tuple with an atom as its first element, got: {{{:., [line: 25], [{:contact, [line: 25], nil}, :first_name]}, [no_parens: true, line: 25], []}, "A"}

Stacktrace:
  │ (elixir 1.11.2) lib/keyword.ex:475: Keyword.keys/1
  │ (xxx_core 0.1.0) expanding macro: XXX.Core.Query.weighted_fulltext_search/2
  │ lib/xxx_domain/public_contacts/contact/query.ex:23: XXX.Domain.PublicContacts.Contact.Query.by_search_query/2
  │ (ecto 3.4.6) expanding macro: Ecto.Query.where/3
  │ lib/xxx_domain/public_contacts/contact/query.ex:21: XXX.Domain.PublicContacts.Contact.Query.by_search_query/2
  │ (elixir 1.11.2) expanding macro: Kernel.|>/2
  │ lib/xxx_domain/public_contacts/contact/query.ex:21: XXX.Domain.PublicContacts.Contact.Query.by_search_query/2
  │ (elixir 1.11.2) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

### Expected behavior

This code runs just fine in production, but ElixirLS is not able to compile it for some reason.

**Comment by AndrewDryga** [comment]
Another very common error we see is `match?(%XXX.Domain.Geo.Address{}, address)` raises 
```
(CompileError) XXX.Domain.Geo.Address.__struct__/0 is undefined, cannot expand struct XXX.Domain.Geo.Address. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code
```
when this struct has a full module name and must be available as it directly depends on the application that holds it in umbrella.

**Comment by lukaszsamson** [comment]
elixir-ls invokes `mix compile` so it should not fail if the project compiles cleanly. The fact that it fails might be a result of some stale data. Have you tried
```
rm -rf .elixir_ls
git clean -dfx
```
Does having dialyzer off makes a difference?
If those measures fail please try to create a repro project.

**Comment by AndrewDryga** [comment]
Unfortunately, It did not help. I'll try to setup a repo that reproduces this but not sure when that would happen (we have a huge codebase to strip off).

**Comment by AndrewDryga** [comment]
Okay, so the core issue here was that ElixirLS (the one provisioned with VSCode plugin) was compiled with Elixir 1.8 and Erlang 21 when my local Elixir version was 1.11.2 / Erlang 23. After I manually released a new version and replaced the release in the plugin folder most of the problems went away.
