### ISSUE TITLE
Syntax errors not highlighted

### ISSUE THREAD

**Issue by southkeys** [elixir-lsp/elixir-ls#410]
### Environment

* Elixir & Erlang versions (elixir --version): 1.11.2
* Operating system: MacOS Catalina 10.15.7
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name: ElixirLS

### Logs

2.  Create a new Mix project with `mix new empty`, then open that project with VS Code and open an Elixir file. Is your issue reproducible on the empty project? If not, please publish a repo on Github that does reproduce it. 
Yes it is reproducible

![Screen Shot 2020-11-19 at 5 27 05 PM](https://user-images.githubusercontent.com/10474042/99732503-9ac09600-2a8d-11eb-9c3e-b827d9e30c74.png)

**Comment by lukaszsamson** [comment]
Have you saved the file? Syntax checks currently only happen on save during build.
Please attach any logs if relevant.
That's what I'm seeing on my machine (macOS 10.15.7, elixir 1.11.2, VSCode)
<img width="781" alt="Screenshot 2020-11-20 at 01 07 53" src="https://user-images.githubusercontent.com/1078186/99739421-04ac6000-2acd-11eb-8ca7-c06a9bcbaebf.png">

**Comment by z82n** [comment]
> Have you saved the file? Syntax checks currently only happen on save during build.
> Please attach any logs if relevant.
> That's what I'm seeing on my machine (macOS 10.15.7, elixir 1.11.2, VSCode)
> <img alt="Screenshot 2020-11-20 at 01 07 53" width="781" src="https://user-images.githubusercontent.com/1078186/99739421-04ac6000-2acd-11eb-8ca7-c06a9bcbaebf.png">

Yes I've saved the file. 

I'm getting a bunch of

[Trace - 5:34:47 p.m.] Received response 'textDocument/hover - (9)' in 50ms. Request failed: Request cancelled (-32800).
[Trace - 6:19:38 p.m.] Received response 'textDocument/codeLens - (293)' in 18499ms. Request failed: Request cancelled (-32800).

**Comment by lukaszsamson** [comment]
Please post full logs from ElixirLS Output tab and from VSCode Developer Tools.

**Comment by lukaszsamson** [comment]
Closing due to lack of info from the OP
