### ISSUE TITLE
Default 'Project Dir' set to `.` causes failure

### ISSUE THREAD

**Issue by GenericJam** [elixir-lsp/elixir-ls#427]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.10.4, Erlang/OTP 23
* Operating system: Mac OS (Big Sur)
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name: ElixirLS v0.6.2 (jakebecker.elixir-ls)
* ElixirLS version: whatever comes with? I installed through VSCode.

This is the second time this has tripped me up. The first was about this time last year on  a different project. The default value set for 'Project Dir' is '.' but it should be blank. It causes a similar error to [here](https://github.com/JakeBecker/elixir-ls/issues/34) in this line [here](https://github.com/JakeBecker/elixir-ls/blob/846c3b3d8392e6e544301d30baf6586e748e34fd/apps/language_server/lib/language_server/build.ex#L6). These two ways of analyzing the root dir render differently so the string comparison fails even though they are pointing to the same location.
I got an error like 

`Skipping build because cwd changed from /Users/user/Code/Project/server/. to /Users/user/Code/Project/server`

This error can be viewed by turning messages on and viewing them in the VS Code output panel.

This goes away once you set the previously mentioned field to blank so it seems like this should be the default.

**Comment by lukaszsamson** [comment]
Please fill in ElixirLS and ElixirLS vscode plugin versions

**Comment by lukaszsamson** [comment]
Also since 0.5 default is "", see https://github.com/elixir-lsp/vscode-elixir-ls/commit/eb8f4d1476c962b57844352f419ced5a107e6554

**Comment by GenericJam** [comment]
If you say it's fixed I believe you. I don't know how I encountered it today. Is it possible VS Code is accessing an old cached copy? Like I said, I tripped over this same problem a year ago which you obviously were aware of since.

**Comment by lukaszsamson** [comment]
There is no validation forbidding ".". Most likely you had that value set at some point.
@axelson maybe we should add a warning?

**Comment by GenericJam** [comment]
It's possible this was stored in local settings as I initially installed it more than a year ago. I actually went so far as to uninstall vscode and reinstall to try to get rid of the error before I realized what it was. After I reinstalled all of my previous settings were still there so they're obviously being stored locally somewhere.

**Comment by axelson** [comment]
I agree that a warning would be a good improvement. Should we go even further and ignore a value of `.` replacing it with `""` (this would be in addition to the warning).

**Comment by lukaszsamson** [comment]
Tracked in https://github.com/elixir-lsp/elixir-ls/issues/536
