### ISSUE TITLE
Speed regression for elixir 1.11, manifest writing takes between 4 and 6 seconds

### ISSUE THREAD

**Issue by reneweteling** [elixir-lsp/elixir-ls#439]
## Speed regression
Since I've updated to elixir 1.11 and Big Sur (was around the same time) the elixir ls plugin became real sluggish, saving and formatting would take 10+ seconds, I've tried to debug what's wrong and it seems that writing the manifest `[Info  - 9:50:53 AM] [ElixirLS Dialyzer] Done writing manifest in 4128 milliseconds.` just takes ages. My MacBook has an SSD with an i7 quadcore, so I'm pretty confident it's not my machine. 

If there is anything I can do to help, let me know. Thanks in advance!

### Environment

* Elixir & Erlang versions (elixir --version): 
`Elixir 1.11.0 (compiled with Erlang/OTP 23)`

* Operating system: 
`ProductName:	macOS`
`ProductVersion:	11.1`
`BuildVersion:	20C69`

* Editor or IDE name (e.g. Emacs/VSCode): 
`VsCode`

* Editor Plugin/LSP Client name:
`jakebecker.elixir-ls v0.6.2`

### Logs

```
Compiling 1 file (.ex)
[Info  - 9:50:45 AM] Compile took 2941 milliseconds
[Info  - 9:50:45 AM] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 9:50:45 AM] [ElixirLS WorkspaceSymbols] Updating index...
[Info  - 9:50:48 AM] [ElixirLS WorkspaceSymbols] 1 modules need reindexing
[Info  - 9:50:48 AM] [ElixirLS WorkspaceSymbols] 0 callbacks added to index
[Info  - 9:50:48 AM] [ElixirLS WorkspaceSymbols] 0 types added to index
[Info  - 9:50:48 AM] [ElixirLS WorkspaceSymbols] 1 modules added to index
[Info  - 9:50:48 AM] [ElixirLS WorkspaceSymbols] 7 functions added to index
[Info  - 9:50:48 AM] [ElixirLS Dialyzer] Found 1 changed files in 424 milliseconds
[Info  - 9:50:48 AM] [ElixirLS Dialyzer] Analyzing 0 modules: []
[Info  - 9:50:48 AM] [ElixirLS Dialyzer] Analysis finished in 103 milliseconds
[Info  - 9:50:49 AM] Dialyzer analysis is up to date
[Info  - 9:50:51 AM] [ElixirLS Dialyzer] Writing manifest...
[Info  - 9:50:53 AM] [ElixirLS Dialyzer] Done writing manifest in 4128 milliseconds.
```

**Comment by axelson** [comment]
Hi there! Saving and formatting isn't dependent on the speed of writing the Dialyzer manifest, so that's a red herring. This is a known regression that is being tracked in #381. And you may want to take a look at PR #394 which will fix this issue but isn't quite ready for merging yet. Also you should check your formatter configuration to ensure that large directories such as `node_modules` are not being checked for formatting (but please continue any discussion in #381).

**Comment by lukaszsamson** [comment]
@reneweteling of course you can disable auto format on save in your editor and rely on `mix format` until that issue is resolved.

**Comment by reneweteling** [comment]
thanks @axelson!
