### ISSUE TITLE
Nova unsaved URI format crashes server

### ISSUE THREAD

**Issue by raulchedrese** [elixir-lsp/elixir-ls#444]
### Environment

* Elixir & Erlang versions (elixir --version): `Elixir 1.11.2 (compiled with Erlang/OTP 23)`
* Operating system: macOS 11.1 Big Sur
* Editor or IDE name (e.g. Emacs/VSCode): Nova
* Editor Plugin/LSP Client name: Nova ElixirLS

The language server crashes while attempting to parse a path from the "textDocument" URI sent by the Nova LSP client. I'm not sure if this is an issue with elixir-ls or Nova's LSP client since I couldn't find a specification for unsaved document URIs in the LSP docs. This works fine in VSCode because they use a different URI format.

**Nova format:**
```json
"textDocument": {
	"uri": "unsaved://343C3EE7-D575-486D-9D33-93AFFAF773BD"
}
```

**VSCode format:**
```json
"textDocument": {
	"uri": "untitled:Untitled-1"
}
```

### Logs
Line that triggers the crash: https://github.com/elixir-lsp/elixir-ls/blob/master/apps/language_server/lib/language_server/source_file.ex#L66

```
21:47:49.496 [error] GenServer ElixirLS.LanguageServer.Server terminating
** (FunctionClauseError) no function clause matching in URI.unpercent/3
	(elixir 1.11.2) lib/uri.ex:364: URI.unpercent(nil, "", false)
	(elixir 1.11.2) lib/uri.ex:341: URI.decode/1
	(language_server 0.6.0) lib/language_server/source_file.ex:43: ElixirLS.LanguageServer.SourceFile.path_from_uri/1
	(language_server 0.6.0) lib/language_server/source_file.ex:216: ElixirLS.LanguageServer.SourceFile.formatter_opts/1
	(language_server 0.6.0) lib/language_server/server.ex:486: ElixirLS.LanguageServer.Server.handle_request/2
	(language_server 0.6.0) lib/language_server/server.ex:332: ElixirLS.LanguageServer.Server.handle_request_packet/3
	(language_server 0.6.0) lib/language_server/server.ex:126: ElixirLS.LanguageServer.Server.handle_cast/2
	(stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
Last message: {:"$gen_cast", {:receive_packet, %{"id" => 7, "jsonrpc" => "2.0", "method" => "textDocument/completion", "params" => %{"context" => %{"triggerCharacter" => "s", "triggerKind" => 2}, "position" => %{"character" => 4, "line" => 8}, "textDocument" => %{"uri" => "unsaved://343C3EE7-D575-486D-9D33-93AFFAF773BD"}}}}}
```

**Comment by lukaszsamson** [comment]
Nova URI is a rather non standard as it is not mentioned in language server spec. Anyway, it looks like vscode `untitled:Untitled-1` is also handled incorrectly as it returns a not existing file.
A PR fixing that would be appreciated.
