### ISSUE TITLE
Dialyzer analysis failed with error

### ISSUE THREAD

**Issue by henrythebuilder** [elixir-lsp/elixir-ls#449]
### Environment

* Elixir & Erlang versions (elixir --version): 
    `Erlang/OTP 23 [erts-11.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]`
    `Elixir 1.12.0-dev (a540166) (compiled with Erlang/OTP 23)`
 
   _Erlang_ installed from 'Erlang Solutions' Debian packages (`23.2.1`)
   _Elixir_ compiled from source (master branch)

* Operating system: 
  `Debian Buster (10.7): Linux xps.home.local 5.9.0-0.bpo.2-amd64 #1 SMP Debian 5.9.6-1~bpo10+1 (2020-11-19) x86_64 GNU/Linux`
* Editor or IDE name (e.g. Emacs/VSCode): 
  `Emacs 27.1`
* Editor Plugin/LSP Client name:
  `eglot` + `elixir-ls`

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

Hello,
I'am a problem with the last version of elixir-ls from master branch.
Ok with the last release ([v0.6.2](https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.6.2)) compiled from source

The problem is for '_Building core Dialyzer Elixir PLT_',  in the last version many errors are raised of type `:dialyzer_error`

This type of errors occur in the '_eglot process'_ and also in the _elixir-ls project_ running the test suite (`mix test`)

Two logs attached: 
* [elixir-ls---mix-test.log](https://github.com/elixir-lsp/elixir-ls/files/5761846/elixir-ls---mix-test.log) -> is the output of `mix test --trace`
* [elixir-ls---eglot-from-emacs-error.log](https://github.com/elixir-lsp/elixir-ls/files/5761845/elixir-ls---eglot-from-emacs-error.log) -> is the output of emacs buffer (eglot buffer) cut-off on the first messages

I have not seen any messages/issues about this situation so so I ask for help if the problem is with the system/configuration/using or it must be traced back to something else

Thanks in advance
Enrico

**Comment by lukaszsamson** [comment]
I cannot reproduce this on MacOS and CI on Ubuntu is passing fine.
Please try solutions from https://github.com/jeremyjh/dialyxir/issues/233, https://github.com/robisonsantos/evm/issues/26, https://elixirforum.com/t/dialyzer-not-compiling-correctly/17873/12, https://stackoverflow.com/questions/42963627/cant-get-dialyzer-to-work-with-evm
Especially try deleting _build, .elixir-ls, and PLTs from MIX_HOME
Not also that development elixir versions are not supported.

**Comment by henrythebuilder** [comment]
Thanks for response,
I know that the development elixir versions is not supported but it is my intention to seek help to solve the problem if possible.
I've already tried deleting _build and .elixir-ls folder, the problem still exist also from a new project.
For PLTs from MIX_HOME i think it originated from there in fact i noticed the problem after the system updated erlang packages to new version, however I tried also this solution without good results.
I tried to update the elixir-ls source version from the release 0.6.2 onwards and i found the problem exists from commint `Dialyzer improvements (#422)`  -> (f08f5ab0) . Looking at the changes introduced since that point i tried something and a successful attempt was to reset the function `build_elixir_plt()` in the `ElixirLS.LanguageServer.Dialyzer.Manifest` module to the previous version, this led to successful testing in the elixir-ls project (mix test), and no errors were generated in emacs for a new elixir project, new PLT file generated in MIX_HOME (`elixir-ls-23.2.1_elixir-1.12.0-dev`), i don't know if this is correct, it was just an attempt to try to understand something, hoping it helps.

**Comment by lukaszsamson** [comment]
@henrythebuilder thanks for investigating.
Are you able to build the PLT with only changing
```
@erlang_apps []
```
Are you able to build PLT with dialyxir?

**Comment by henrythebuilder** [comment]
good news, maybe i found the problem!
In my system I'm always using _elixir_ (compiled from source) as symlink to the local repo, so the new version of elixir-ls catch also the temporary compiled file as `...elixir/lib/mix/tmp/...`, and these files are the cause of the problem as reported in the attached logs. Maybe the new version captures files that the old one did not consider.
Install elixir locally with `make DESTDIR=... install` solve the problem, only necessary files are installed (and visible) and all seam to work, mix test from elixir-ls repo and emacs integration: with a MIX_HOME without PLTs a new PLT was created as expected.
Thanks again for the support and sorry for the strange issue. 
:+1:

**Comment by lukaszsamson** [comment]
Good to hear that.
> Maybe the new version captures files that the old one did not consider.
 
That's true. Prior to this change only erlang beams used directly by elixir apps were included. Now all of them are.
