### ISSUE TITLE
Fuzzy function name matching

### ISSUE THREAD

**Issue by princemaple** [elixir-lsp/elixir-ls#466]
Typing `Enum.chub` I'd like to see `Enum.chunk_by` being suggested instead of terminating the auto completion

**Comment by princemaple** [comment]
Note to myself or anyone who may want to take this one:
https://github.com/elixir-lsp/elixir_sense/blob/master/lib/elixir_sense/providers/suggestion/complete.ex#L594
Probably just change `starts_with?` to a proper fuzzy matching function.

**Comment by princemaple** [comment]
It seems easy enough to make it work.
Not sure how much noise this would cause.

```elixir
defmodule SuggetionMatch do
  @moduledoc """
  Documentation for `SuggetionMatch`.
  """

  @doc """
  Fuzzy match string

  ## Examples

      iex> SuggetionMatch.match("map", "map")
      true

      iex> SuggetionMatch.match("map", "m")
      true

      iex> SuggetionMatch.match("map", "ma")
      true

      iex> SuggetionMatch.match("map", "mp")
      true

      iex> SuggetionMatch.match("chunk_by", "chub")
      true

      iex> SuggetionMatch.match("chunk_by", "chug")
      false
  """
  @spec match(name :: String.t(), hint :: String.t()) :: boolean()
  def match(<<head::utf8, name_rest::binary>>, <<head::utf8, hint_rest::binary>>) do
    match(name_rest, hint_rest)
  end

  def match(<<_head::utf8, name_rest::binary>>, <<_not_head::utf8, _hint_rest::binary>> = hint) do
    match(name_rest, hint)
  end

  def match(_name_rest, <<>>) do
    true
  end

  def match(<<>>, <<>>) do
    true
  end

  def match(<<>>, _) do
    false
  end
end
```

**Comment by lukaszsamson** [comment]
> Note to myself or anyone who may want to take this one:
> https://github.com/elixir-lsp/elixir_sense/blob/master/lib/elixir_sense/providers/suggestion/complete.ex#L594
> Probably just change `starts_with?` to a proper fuzzy matching function.

That's not the only place in elixir_sense that uses hint matching with `String.starts_with`

**Comment by princemaple** [comment]
Yup. I did notice the other occurrences in the same module, and repeated implementation in other modules as well.

**Comment by princemaple** [comment]
So, the list of files where this could help, in ElixirSense:

- lib/elixir_sense/plugins/option.ex
- lib/elixir_sense/providers/suggestion/reducers/type_specs.ex
- lib/elixir_sense/providers/suggestion/reducers/callbacks.ex
- lib/elixir_sense/providers/suggestion/reducers/struct.ex
- lib/elixir_sense/providers/suggestion/reducers/params.ex
- lib/elixir_sense/providers/suggestion/reducers/overridable.ex
- lib/elixir_sense/providers/suggestion/reducers/protocol.ex
- lib/elixir_sense/providers/suggestion/reducers/docs_snippets.ex
- lib/elixir_sense/providers/suggestion/complete.ex
- lib/elixir_sense/plugins/ecto/schema.ex

**Comment by axelson** [comment]
Associated PR: #491

**Comment by lukaszsamson** [comment]
While fuzzy matching on function names has been merged there are other cases where it may be useful - see https://github.com/elixir-lsp/elixir_sense/issues/122. Besides those I think we need to change matching algorithm in WorskpaceSymbolsProvider.
