### ISSUE TITLE
Setup.bat should ignore stdout

### ISSUE THREAD

**Issue by E14** [elixir-lsp/elixir-ls#469]
> `CALL "%APPDATA%\elixir_ls\setup.bat" > nul 2>&1` If the user can make sure the script works before really using it.

_Originally posted by @princemaple in https://github.com/elixir-lsp/elixir-ls/issues/374#issuecomment-771536127_

I don't think it is a good idea to void stderr though

**Comment by lukaszsamson** [comment]
@E14 could you submit a PR?

> I don't think it is a good idea to void stderr though

stderr output seems to be harmless  (at least in vscode)
