### ISSUE TITLE
Latest changes to language_server.sh break startup on macOS

### ISSUE THREAD

**Issue by optikfluffel** [elixir-lsp/elixir-ls#470]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir `1.11.3` & Erlang `23.2.3`
* Operating system: macOS `10.15.7`
* Editor or IDE name (e.g. Emacs/VSCode): Sublime Text `3.2.2`
* Editor Plugin/LSP Client name: `LSP-elixir`

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

### Logs

1.  If using a client other than VS Code, please try VSCode's "ElixirLS: Elixir support and debugger" extension. Does it reproduce your failure?
2.  Create a new Mix project with `mix new empty`, then open that project with VS Code and open an Elixir file. Is your issue reproducible on the empty project? If not, please publish a repo on Github that does reproduce it.
3.  Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)
4.  Check the developer console by opening `Help > Toggle Developer Tools` and include any errors that look relevant.

---

Hey everyone, it seems your [recent changes to language_server.sh](https://github.com/elixir-lsp/elixir-ls/commit/843e1a6cc964df82f604be94d0784773205758f3) broke something on macOS. If I revert those changes everything works fine again.

See [sublimelsp/LSP-elixir#14](https://github.com/sublimelsp/LSP-elixir/issues/14) for details.

**Comment by lukaszsamson** [comment]
@optikfluffel can you try to debug wich call to `dirname` actually failing? I cannot reproduce that on macOS 10.15.7

@jtrees do you have an idea what may be broken in your PR?

**Comment by optikfluffel** [comment]
@lukaszsamson when I put something like `echo "in readlink_f"` on top of the readlink_f function it never shows up, so my best guess would be that `dir=$(dirname $(readlink_f "$0"))` at the bottom is the one failing

**Comment by jtrees** [comment]
@optikfluffel Where is elixir-ls in your filesystem? Does the path contain a space by any chance? Looks like I missed some important quotes in my previous PR. If that's the issue, then it should be fixed with #473.

**Comment by optikfluffel** [comment]
@jtrees yes, there is a space in there. I just gave #473 a spin and it seems fine to me, thanks for the quick fix! :)

**Comment by jtrees** [comment]
Great! And thanks for the speedy feedback!
