### ISSUE TITLE
Better vim installation instructions

### ISSUE THREAD

**Issue by jondkinney** [elixir-lsp/elixir-ls#48]
Hi there!

Thanks for the work on elixir-ls. I might be missing it, but I don't see any friendly details on how to get it installed. I found https://www.rockyourcode.com/developing-with-elixir-in-vim which worked for me with Vim and Ale, but curious if it makes sense to point folks to some more help getting things installed?

Thanks!

**Comment by lukaszsamson** [comment]
Looks that has been addressed in https://github.com/elixir-lsp/elixir-ls/pull/326
