### ISSUE TITLE
Format adds empty lines with CRLF line endings

### ISSUE THREAD

**Issue by wanton7** [elixir-lsp/elixir-ls#484]
### Environment

Erlang/OTP 21 [erts-10.3] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.11.3 (compiled with Erlang/OTP 21)
Windows 10 64-bit
VSCode
jakebecker.elixir-ls v0.6.5

### Troubleshooting

- [X] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [X] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

### Problem
Formatting (Shift+Ctrl+F and format on save) adds empty lines if you use CRLF line endings

From this
![image](https://user-images.githubusercontent.com/1009930/107424237-16c6f900-6b26-11eb-80e4-624257b76971.png)

To this
![image](https://user-images.githubusercontent.com/1009930/107424286-26464200-6b26-11eb-9d8a-d6f48fbeba70.png)

**Comment by axelson** [comment]
This was reported at https://github.com/elixir-lsp/vscode-elixir-ls/issues/169 as well. The commonality appears to be windows. It's probably something to do with line endings.
