### ISSUE TITLE
Avoid Multiple Parallel Compiles?

### ISSUE THREAD

**Issue by atonse** [elixir-lsp/elixir-ls#487]
### Environment

* Elixir & Erlang versions (elixir --version): 1.11.3
* Operating system: macOS Big Sur (M1 Mac mini)
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name: elixir-ls

My apologies if this is a duplicate. I didn't find anything about this in the Wiki.

I usually run `mix phx.server` in my terminal when developing. I also run VSCode which runs ElixirLS. However, when I update files or switch branches, I've noticed that both of those have to recompile (taking twice as long).

Is there a way to configure these two envs to just compile once? Or is the right way to do this to use VS Code's tasks and it'll just compile one location? (.elixir_ls/whatever, rather than also _build)

**Comment by axelson** [comment]
Hi @atonse :wave:,

Unfortunately Elixir doesn't support multiple parallel compiles (although it does use parallelization within a single compilation process). Because of this ElixirLS has to have it's own `_build` folder or we will risk corrupting the build.

**Comment by atonse** [comment]
Why can't we actually just run this as an additional app in our regular projects? (in `:dev` only), that way when I run my phoenix app in dev, it'll also load the LSP, and that would solve the issue of having two different compiles.
