### ISSUE TITLE
use textEdit to avoid ambiguity

### ISSUE THREAD

**Issue by princemaple** [elixir-lsp/elixir-ls#496]
Related to #27 and #28

### Environment

* Elixir & Erlang versions (elixir --version): 1.11.3
* Operating system: Win10
* Editor or IDE name (e.g. Emacs/VSCode): Sublime
* Editor Plugin/LSP Client name: LSP (https://github.com/sublimelsp/LSP)

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

### Logs

the beginning:
https://discord.com/channels/280102180189634562/645268178397560865/813535858287312947

we did some digging, with communication logs
https://discord.com/channels/280102180189634562/645268178397560865/813566113190379611

my video recording 1, completion of module name removes prefix. This is not a problem in VSCode - VSC and ST probably treat prefix differently.
https://discord.com/channels/280102180189634562/645268178397560865/813883618778021950
![recording1](https://user-images.githubusercontent.com/1329716/108947259-40e6f200-76b4-11eb-8a28-7706cbf68dc5.gif)

my video recording 2, completion of atom removes `:`, I can't get VSCode to trigger this completion at all, works half successfully in ST
https://discord.com/channels/280102180189634562/645268178397560865/813904959921192980
![recording2](https://user-images.githubusercontent.com/1329716/108947273-45aba600-76b4-11eb-95c0-4d72082e636a.gif)

**Comment by lukaszsamson** [comment]
Closing this as it's already tracked in #28. Thanks for investigating.
