### ISSUE TITLE
Mix.Error Unknown dependency :ecto_sql

### ISSUE THREAD

**Issue by haslinger** [elixir-lsp/elixir-ls#516]
### Environment

* Erlang/OTP 23 [erts-11.1.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
* Elixir 1.11.2 (compiled with Erlang/OTP 23)
* VSCode ElixirLS version: 0.6.5
* Operating System Version: linux 5.4.0-67-generic

### Output 

```
Started ElixirLS v0.6.5
Elixir version: "1.11.2 (compiled with Erlang/OTP 23)"
Erlang version: "23"
ElixirLS compiled with Elixir 1.8.2 and erlang 21
Skipping build because cwd changed from /home/stefan/phoenix/pan-in-development/. to /home/stefan/phoenix/pan-in-development
[Info  - 09:53:17] Dialyzer analysis is up to date
[Warn  - 09:53:30] warning: Unable to get formatter options for /home/stefan/phoenix/pan-in-development/lib/pan_web/frontend_controller/category_frontend_controller.ex: Mix.Error Unknown dependency :ecto_sql given to :import_deps in the formatter configuration. The dependency is not listed in your mix.exs for environment :test
  (language_server 0.6.5) lib/language_server/source_file.ex:331: ElixirLS.LanguageServer.SourceFile.formatter_opts/1
  (language_server 0.6.5) lib/language_server/providers/formatting.ex:7: ElixirLS.LanguageServer.Providers.Formatting.format/3
  (language_server 0.6.5) lib/language_server/server.ex:753: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2

[Error - 09:53:30] Request textDocument/formatting failed.
  Message: Unable to fetch formatter options
  Code: -32603 
```

### More Info, Comments and Thanks

* The full repo code is available to be browsed [over here](https://gitlab.informatom.com/panoptikum/pan/-/tree/main).
* The [mix file](https://gitlab.informatom.com/panoptikum/pan/-/blob/main/mix.exs) contains ecto_sql as an explicit dependency
* If I'd remove ecto_sql from formatter.exs and just leave phoenix in as a dependency, the error message would be basically the same, but with phoenix
* I earlier had an extra formatter.exs with ecto_sql in the migrations dir where it created the same error message.
* The `mix format` task works nicely on the command line, so I have a fallback solution.
* I had it working before (with older elixir and phoenix versions) on this machine.
* Thank you for all your work! (It was really super nice, as long as it worked, you made me switch to VSCode for elixir-development, I was on Atom before.)
* If I can provide any more infos to help sort this out, please let me know.

**Comment by lukaszsamson** [comment]
Cannot reproduce.
The repo you posted does not import any deps in `.formatter.exs`. Even when I added `:phoenix` and `:ecto_sql` I couldn't reproduce this crash.

Please check if your Project Dir config is correct, this line is suspicious
```
Skipping build because cwd changed from /home/stefan/phoenix/pan-in-development/. to /home/stefan/phoenix/pan-in-development
```
If you're using standard directory layout then it should be empty.

**Comment by haslinger** [comment]
Thank you for pointing me in the right direction, I had "." as Project Dir setting. Removed that, restarted, compilation succeeded and formatting docs works like a charm again.
