### ISSUE TITLE
Add parameter to set evaluate_code_expression timeout

### ISSUE THREAD

**Issue by funnisquares** [elixir-lsp/elixir-ls#525]
When trying to debug some web requests, sometimes the 1 second timeout is too short, I think there should be a way to set the timeout to some other value.

**Comment by axelson** [comment]
Hmm, we should probably just increase the timeout value. How about 10 seconds?

**Comment by lukaszsamson** [comment]
It shouldn't be difficult to read it from launch config

**Comment by funnisquares** [comment]
I think it would be preferable to have it be a config parameter, so as to accommodate every need. 10 seconds would be better than the 1 second timeout it has currently, and would suffice for me, but maybe it wouldn't for someone with a very slow internet connection trying to some function that fetches an API call to a remote server.

**Comment by funnisquares** [comment]
I think it would be preferable to have it be a config parameter, so as to accommodate every need. 10 seconds would be better than the 1 second timeout it has currently, and would suffice for me, but maybe it wouldn't for someone with a very slow internet connection trying to some function that fetches an API call to a remote server. 

I've just started learning elixir more in-depth, so I might be wrong. But why the need for a timeout when evaluating expressions in the debug console? Wouldn't it be better having the timeout be as large as possible (maybe infinite?), and leave to the user the responsibility of forcing the execution to stop in case the evaluation is taking longer than it should? I don't know exactly the inner workings of ElixirLS debugger though, so it might be difficult to implement a client-side halt to a running expression, or maybe there are good reasons not to leave this responsibility to the user.

------------

Also possibly related, calling functions through the debug console will always timeout if the function (or any other function called inside it) has a breakpoint set.
