### ISSUE TITLE
[Windows] Suggest spec Code Lens not working

### ISSUE THREAD

**Issue by gallexme** [elixir-lsp/elixir-ls#528]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 23 [erts-11.2] [source] [64-bit] Elixir 1.11.4 (compiled with Erlang/OTP 21) 
* Operating system: Windows 10 /WSL Arch
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name: ElixirLS

### Troubleshooting

- [X] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [X] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

### Logs

3.  Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)
No Errors

4.  Check the developer console by opening `Help > Toggle Developer Tools` and include any errors that look relevant.
No Errors

Installing 0.7.0 then repeatedly deleting .elixir_ls does not help
installing 0.6.2 then repeatedly deleting .elixir-ls does help

with 0.6.2 i get suggestions for the @spec , with 0.7.0 i dont

0.6.2: https://cdn.discordapp.com/attachments/269508806759809042/829735077779996712/unknown.png

0.7.0: https://media.discordapp.net/attachments/646832679999897610/829994787565731911/unknown.png

**Comment by lukaszsamson** [comment]
@gallexme What do you mean by "@spec Auto Suggestion"? Do you mean Code Lens suggesting type specs for functions/macros (which I verified is working) or `@spec` attribute code completion (which is also working) or code completions inside typespecs (which is also working)? We need more info and a project that reproduces this issue.

**Comment by gallexme** [comment]
0.6.2 Pic shows the suggestion I'm talking about, a gray @spec recommendation which u can click and automatically gets inserted into the code, I'm not the only one with the issue, it happens with any project

I'm using Windowsz, but same issue with arch Linux on wsl2

For one guy it worked by repeatedly installing 0.7, but for me only after installing a 0.6 version

@axelson 
Meant 
"Hmm, that's likely a bug introduced since we generalized that portion of the code. Please file a bug report thumbsup"



Other user having same issue:
![Screenshot_20210414_094413_com discord](https://user-images.githubusercontent.com/1122989/114673045-143f7600-9d06-11eb-891b-defcea0aaa79.jpg)


Im using Using otp 23 and elixir 1.11
Same issue happens with otp24 rc2 and elixir 1.11 on arch Linux 

How can I provide u more Infos? 


https://gitlab.com/zen_core/zen_core
Is one project where that issue happens 
But I also see it happening on empty elixir applications

**Comment by lukaszsamson** [comment]
@gallexme you didn't post any pic.

> a gray @SPEC recommendation which u can click and automatically gets inserted into the code

It's called Code Lens and the problem is on Windows only. On macOS it works fine.

<img width="718" alt="Screenshot 2021-04-14 at 09 56 33" src="https://user-images.githubusercontent.com/1078186/114676213-603fea00-9d09-11eb-8e8c-2d68df41e6f3.png">

**Comment by gallexme** [comment]
did post those 2 pics in the issue
but its okay :)

0.6.2: https://cdn.discordapp.com/attachments/269508806759809042/829735077779996712/unknown.png

0.7.0: https://media.discordapp.net/attachments/646832679999897610/829994787565731911/unknown.png
