### ISSUE TITLE
ElixirLS should detect `.` as the project directory and raise an error

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#536]
elixirLS.projectDir having the value `.` causes the extension to not work. We should either ignore `.` or raise an issue

Results in an error like `Skipping build because cwd changed from /home/jason/dev/gen_tracker/. to /home/jason/dev/gen_tracker` in the output log

**Comment by fmterrorf** [comment]
Hi :wave: I'd like to take a stab at this issue. I see your comment here https://github.com/elixir-lsp/elixir-ls/issues/427#issuecomment-738175152 
> I agree that a warning would be a good improvement. Should we go even further and ignore a value of . replacing it with ""? (this would be in addition to the warning).

That would be done [here](https://github.com/elixir-lsp/elixir-ls/blob/master/apps/language_server/lib/language_server/build.ex#L5) correct? Where we'll check if the `rootPath` is `.` and replace it with `""`

**Comment by lukaszsamson** [comment]
@fmterrorf I would not pollute this module with settings validation. Let's do it in server.ex in `set_settings`.
