### ISSUE TITLE
Not possible to navigate?

### ISSUE THREAD

**Issue by thojanssens** [elixir-lsp/elixir-ls#538]
### Environment

* Elixir & Erlang versions (elixir --version): 
Erlang/OTP 22 [erts-10.7] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]
Elixir 1.11.3 (compiled with Erlang/OTP 21)
* Operating system: Windows 10
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name: Elixir LS v0.7.0

### Troubleshooting

- [ x ] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [ x ] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

The classic Ctrl + Click to navigate on a module or function doesn't seem to work. I switched from IntelliJ to VS Code and on the latter I can't navigate anymore.

**Comment by lukaszsamson** [comment]
Please post a project that reproduces this issue. Note that navigation to erlang/elixir sources may not work if the sources are not present at the dir returned metadata in  module.module_info.

**Comment by lukaszsamson** [comment]
Closing due lack of OP's interest
