### ISSUE TITLE
Feature request: reuse existing PLTs for core (erlang/elixir) instead of generating from scratch

### ISSUE THREAD

**Issue by Trevoke** [elixir-lsp/elixir-ls#539]

**Comment by axelson** [comment]
I'm hoping to make use of https://github.com/asummers/plts/ in ElixirLS

**Comment by lukaszsamson** [comment]
On modern hardware PLT generation takes 1-2 minutes. IMO it's not worth the effort and having it in ElixirLS we have full control over what gets into PLTs. If someone is willing to contribute support for that I'd be OK to revisit that
