### ISSUE TITLE
Suggestions: Enable autocomplete when using `Application.compile_env/3` and similar for dependency injection

### ISSUE THREAD

**Issue by gugahoa** [elixir-lsp/elixir-ls#541]
Hi all,
I just noticed that Dialyzer can successfully output warnings and errors when we use `Application.compile_env/3` for dependency injection. I was quite happy and though that maybe the language server would also give me autocomplete, but it didn't.

It seems like a great thing to have. When I looked up `compile_env` in this repo, I didn't find anything mentioning this, so I created a new issue.

If this seems like a good contribution to have, could you give me pointers on how to implement it?

**Comment by lukaszsamson** [comment]
The main difference is that dialyzer works on compiled beam files and our suggestions engine mostly work with AST. It would be quite easy to parse AST and get the env but to get the value you would need to read client configuration. The apps are theoretically loaded but I'm not sure if the config is. If you want to give it a try look into elixir_sense library. Especially
- https://github.com/elixir-lsp/elixir_sense/blob/master/lib/elixir_sense/core/binding.ex (simple type inference engine)
- https://github.com/elixir-lsp/elixir_sense/blob/master/lib/elixir_sense/core/metadata_builder.ex (extracting type and binding info from AST)
- https://github.com/elixir-lsp/elixir_sense/blob/master/lib/elixir_sense/providers/suggestion/complete.ex (code completion engine)
