### ISSUE TITLE
Feature Request: Provide config hook to run extra formatters (for surface)

### ISSUE THREAD

**Issue by chevinbrown** [elixir-lsp/elixir-ls#548]
### Background
Tried tinkering with a vs-code formatter-extension to invoke [surface-formatter](https://hexdocs.pm/surface_formatter/readme.html), but then realized that won't work b/c you can only have one formatter per file-type. We need to be able to invoke surface-formatter from elixir-formatter. Unfortunately, this is probably beyond my ability to help with right now.

**Comment by lukaszsamson** [comment]
IMO it's out of the scope of this project. We do not have resources to support every non standard project. Please open an issue on surface tools repo.

**Comment by chevinbrown** [comment]
@lukaszsamson of course; I did bring this up w/ #surface in elixir-slack. The suggestion was to provide some config hook to invoke extra formatters from the elixir-format command. I understand many flavors may evolve, so this could apply to other templating engines like surface, slime, or more.
