### ISSUE TITLE
How to configure settings from within Emacs?

### ISSUE THREAD

**Issue by Qqwy** [elixir-lsp/elixir-ls#552]
I have a 'monorepo', a git repository containing multiple subdirectories, each with a project in a different programming language. One of them is an Elixir project.

LSP is complaining that it cannot find the mix-file in such a situation: 

> LSP :: No mixfile found in project. To use a subdirectory, set `elixirLS.projectDir` in your settings

The README talks about a `settings.json` but this seems to be VSCode-specific. I am using (Spac)emacs. Where should I create a `settings.json`? Or should this setting be set somewhere else when using Emacs?

**Comment by axelson** [comment]
Are you using `lsp-mode`? If so then then I would remove teh top-level directory from lsp-mode's project list, and initialize lsp-mode with the specific subdirectory (by pressing `I` to choose it interactively). I wrote a little bit on partially similar issue here: https://github.com/elixir-lsp/elixir-ls/issues/364#issuecomment-829589139

**Comment by Qqwy** [comment]
Thank you! Removing the project and re-initializing it interactively worked perfectly :blush:

**Comment by axelson** [comment]
Great! Glad to hear you got it all sorted out.
