### ISSUE TITLE
Notification handler 'textDocument/publishDiagnostics' failed

### ISSUE THREAD

**Issue by conradwt** [elixir-lsp/elixir-ls#556]
### Environment

* Elixir & Erlang versions (elixir --version): 1.12.1
* Operating system: macOS 11.4
* Editor or IDE name (e.g. Emacs/VSCode):  1.57.0-insider
* Editor Plugin/LSP Client name: ElixirLS: Elixir support and debugger

### Troubleshooting

- [X] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [X] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

### Logs

1.  If using a client other than VS Code, please try VSCode's "ElixirLS: Elixir support and debugger" extension. Does it reproduce your failure?

I'm not seeing a failure in the Ouput Window.

2.  Create a new Mix project with `mix new empty`, then open that project with VS Code and open an Elixir file. Is your issue reproducible on the empty project? If not, please publish a repo on Github that does reproduce it.

I cannot reproduce my issue with a new project.

3.  Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)

```
MIX_ENV: test
MIX_TARGET: 
Compiling 3 files (.ex)
[Info  - 3:37:40 PM] Compile took 1013 milliseconds
[Info  - 3:37:40 PM] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 3:37:40 PM] [ElixirLS WorkspaceSymbols] Updating index...
[Info  - 3:37:42 PM] [ElixirLS Dialyzer] Found 3 changed files in 486 milliseconds
[Info  - 3:37:42 PM] [ElixirLS WorkspaceSymbols] 1 modules need reindexing
[Info  - 3:37:42 PM] [ElixirLS WorkspaceSymbols] 0 callbacks added to index
[Info  - 3:37:42 PM] [ElixirLS WorkspaceSymbols] 0 types added to index
[Info  - 3:37:42 PM] [ElixirLS WorkspaceSymbols] 1 modules added to index
[Info  - 3:37:42 PM] [ElixirLS WorkspaceSymbols] 9 functions added to index
[Info  - 3:37:52 PM] [ElixirLS Dialyzer] Analysis finished in 92292 milliseconds
[Info  - 3:37:52 PM] [ElixirLS Dialyzer] Analyzing 0 modules: []
[Info  - 3:37:52 PM] [ElixirLS Dialyzer] Analysis finished in 85 milliseconds
[Info  - 3:37:53 PM] Dialyzer analysis is up to date
[Info  - 3:37:54 PM] [ElixirLS Dialyzer] Writing manifest...
[Info  - 3:37:56 PM] [ElixirLS Dialyzer] Done writing manifest in 2915 milliseconds.
```

4.  Check the developer console by opening `Help > Toggle Developer Tools` and include any errors that look relevant.

```
console.ts:137 [Extension Host] Notification handler 'textDocument/publishDiagnostics' failed with message: Illegal argument: line must be non-negative (at ConsoleLogger.error (/Users/conradwt/.vscode-insiders/extensions/jakebecker.elixir-ls-0.7.0/node_modules/vscode-languageclient/lib/client.js:21:17))
```

**Comment by lukaszsamson** [comment]
@conradwt can you share a project that reproduces this error?
Please fill the template with otp version and elixir-lsp plugin version.
Please note that we do not support unreleased versions (this includes vscode insiders)

**Comment by conradwt** [comment]
> @conradwt can you share a project that reproduces this error?

https://github.com/conradwt/zero-to-graphql-using-phoenix

> Please fill the template with otp version and elixir-lsp plugin version.

Erlang 24.0.2 and 22.3.4.20

> Please note that we do not support unreleased versions (this includes vscode insiders)

This may be the issue because vscode-insiders are updated nightly.

**Comment by lukaszsamson** [comment]
This seems to be another problem caused by this bug https://github.com/erlang/otp/pull/4893. For now you can try downgrading to otp 23
I'll look into reproducing and fixing this later.

**Comment by conradwt** [comment]
@lukaszsamson I'll downgrade to Erlang/OTP 23.3.4.3 and see if that works better for me.  Thanks for the information.

**Comment by conradwt** [comment]
@lukaszsamson I have installed Erlang/OTP 23.3.4.3 and now I'm seeing the following on editor startup:

```
init terminating in do_boot ({undef,[{elixir,start_cli,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
[Info  - 2:20:18 PM] Connection to server got closed. Server will restart.
init terminating in do_boot ({undef,[{elixir,start_cli,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
[Info  - 2:20:19 PM] Connection to server got closed. Server will restart.
init terminating in do_boot ({undef,[{elixir,start_cli,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
[Info  - 2:20:20 PM] Connection to server got closed. Server will restart.
init terminating in do_boot ({undef,[{elixir,start_cli,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
[Info  - 2:20:21 PM] Connection to server got closed. Server will restart.
init terminating in do_boot ({undef,[{elixir,start_cli,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
[Error - 2:20:21 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by lukaszsamson** [comment]
@conradwt this looks like a broken elixir install

**Comment by rktjmp** [comment]
I saw a similar issue as the OP in Neovim, it doesn't give as nice a warning but the core is the same, commenting here in case someone searches the issues for `nvim line number outside range`.

https://github.com/neovim/neovim/pull/14737

It does seem like `elixir-ls` is transmitting diagnostics with a `-1` line start?

I know the lines-as-0 are a bug with dialyzer, but how do they end up as -1 and not 0 when coming out of elixir-ls? I had a look through the (very readable) dialyzer and rpc code but nothing stood up unless the messages logged out by `mix dialyzer` are different to what get sent via `:dialyzer_analysis_callgraph.start`?

Decoded message in nvim:
```
{
  jsonrpc = "2.0",
  method = "textDocument/publishDiagnostics",
  params = {
    diagnostics = { {
        message = "Function mount/3 has no local return.",
        range = {
          end = {
            character = 0,
            line = -1
          },
          start = {
            character = 0,
            line = -1
          }
        },
        severity = 2,
        source = "ElixirLS Dialyzer"
      } },
    uri = "file:///<...>.ex"
  }
}
```

`mix dialyzer` error:
```
<...>.ex:0:no_return
Function mount/3 has no local return.
```

**Comment by lukaszsamson** [comment]
> I know the lines-as-0 are a bug with dialyzer, but how do they end up as -1 and not 0 when coming out of elixir-ls?

@rktjmp erlang and elixir use 1 based indexing and LSP protocol 0 based. The workaround should be a simple `max(line - 1, 0)`

**Comment by rktjmp** [comment]
That's what I thought initially but I couldn't find the line numbers transform in this codebase.

Frustratingly searching for `line - 1` on github shows no code results but I did eventually find `location.ex` and submitted a patch here: https://github.com/elixir-lsp/elixir-ls/pull/558.

You argue that upstream is at fault but I guess I am a defensive programmer and Dialyzer has already proven to be "hostile".
