### ISSUE TITLE
elixir-ls builds not actually compatable with OTP 21

### ISSUE THREAD

**Issue by aidalgol** [elixir-lsp/elixir-ls#560]
* Elixir & Erlang versions (elixir --version):
  ```
  Erlang/OTP 21 [erts-10.2.4] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1]
  Elixir 1.10.4 (compiled with Erlang/OTP 21)
  ```
* Operating system: Debian 10
* Editor or IDE name (e.g. Emacs/VSCode): None
* Editor Plugin/LSP Client name: None

The README says that OTP 21 is the minimum required versiont, but when I run `language_server.sh` from https://github.com/elixir-lsp/elixir-ls/releases/download/v0.7.0/elixir-ls-1.10.4.zip on my system, I get an error about the OTP version being too old, even though I am running with the version of OTP stated in the error message.  The build from elixir-ls-1.9.zip (same release) does not work either, saying it uses opcode 164 instead of 169, but elixir-ls-1.8.2.zip does run successfully.  If I build elixir-ls from the source tarball from the same release, it also works as expected.
```
$ /path/to/elixir-ls-1.10.4/language_server.sh 

09:54:48.977 [error] Loading of /path/to/elixir-ls-1.10.4/language_server-0.7.0.ez/language_server-0.7.0/ebin/Elixir.ElixirLS.LanguageServer.CLI.beam failed: :badfile


09:54:48.978 [error] beam/beam_load.c(1878): Error loading module 'Elixir.ElixirLS.LanguageServer.CLI':
  This BEAM file was compiled for a later version of the run-time system than 21.
  To fix this, please recompile this module with an 21 compiler.
  (Use of opcode 169; this emulator supports only up to 163.)



09:54:48.978 [error] Loading of /path/to/elixir-ls-1.10.4/language_server-0.7.0.ez/language_server-0.7.0/ebin/Elixir.ElixirLS.LanguageServer.CLI.beam failed: :badfile


09:54:48.978 [error] beam/beam_load.c(1878): Error loading module 'Elixir.ElixirLS.LanguageServer.CLI':
  This BEAM file was compiled for a later version of the run-time system than 21.
  To fix this, please recompile this module with an 21 compiler.
  (Use of opcode 169; this emulator supports only up to 163.)


** (UndefinedFunctionError) function ElixirLS.LanguageServer.CLI.main/0 is undefined (module ElixirLS.LanguageServer.CLI is not available)
    ElixirLS.LanguageServer.CLI.main()
    (stdlib 3.7.1) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.10.4) lib/code.ex:341: Code.eval_string_with_error_handling/3
```

**Comment by lukaszsamson** [comment]
We are officially supporting last 3 OTP releases, that wold be 22-24

**Comment by aidalgol** [comment]
> We are officially supporting last 3 OTP releases, that wold be 22-24

OK, so then it sounds like this is a documentation bug, since the README says that 21 is the minimum supported release.

**Comment by axelson** [comment]
@aidalgol thanks for pointing that out. I'm updating the docs in https://github.com/elixir-lsp/elixir-ls/pull/561
