### ISSUE TITLE
Feature request: allow additional watched file extensions to be added via configuration

### ISSUE THREAD

**Issue by vanjabucic** [elixir-lsp/elixir-ls#567]
Problem: watched file extensions are static with no way to add additional extensions
Possible solution: allow configuring additional extensions in VSCode via ElixirLS configuration 
Current workaround: using RunOnSave to perform `mix compile` when saving files with certain extensions

---
While working on custom Phoenix.Template.Engines in VSCode I noticed that ElixirLS is not triggering rebuilds on file save. That is due to the fact that the file extension was *.veex and thus not part of the default list of watched file extensions.
Looked for a way to configure additional file extensions, but there was none.

Source code is referencing a static list of file extensions:

![image](https://user-images.githubusercontent.com/3629038/124298348-258c6780-db2a-11eb-8a69-0443895283e2.png)

Normally I would be comfortable making the change necessary and submitting a PR, but seeing how early in the process the static file extension list is used I wanted to see if anyone has some thoughts about it.
My first reaction was to fire additional `register_capability_request("workspace/didChangeWatchedFiles", ..)` on reception of a new configuration that contains `additional_watched_extensions` list...

Suggestions welcome..

**Comment by vanjabucic** [comment]
Note: there was a possible bug introduced in 0851d87a8df7bafa123b669e94e095c33f857765
`watchers = for ext <- @watched_extensions, do: %{"globPattern" => "**/*." <> ext}` 
@watched_extensions already contains the `.` (`@watched_extensions [".ex", ".exs", ".erl", ".hrl", ".yrl", ".xrl", ".eex", ".leex"]`)
resulting in the globPattern having double dots in the string...  Had to remove that dot in "**/*." in order to receive file events on my new file extension.

**Comment by lukaszsamson** [comment]
> Note: there was a possible bug introduced in [0851d87](https://github.com/elixir-lsp/elixir-ls/commit/0851d87a8df7bafa123b669e94e095c33f857765)
> `watchers = for ext <- @watched_extensions, do: %{"globPattern" => "**/*." <> ext}`
> @watched_extensions already contains the `.` (`@watched_extensions [".ex", ".exs", ".erl", ".hrl", ".yrl", ".xrl", ".eex", ".leex"]`)
> resulting in the globPattern having double dots in the string... Had to remove that dot in "**/*." in order to receive file events on my new file extension.

Nice catch, there’s indeed a bug

**Comment by lukaszsamson** [comment]
Addressed in #569
