### ISSUE TITLE
Code completion for module attributes drops `@` symbol

### ISSUE THREAD

**Issue by sheepduke** [elixir-lsp/elixir-ls#573]
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Elixir 1.12.2 (compiled with Erlang/OTP 24)
```
* Operating system: 
```
Linux home 5.13.1-gentoo-x86_64 #1 SMP Thu Jul 15 12:37:23 CST 2021 x86_64 AMD Ryzen 7 2700X Eight-Core Processor AuthenticAMD GNU/Linux
```

* Editor or IDE name (e.g. Emacs/VSCode): `GNU Emacs 27.2`
* Editor Plugin/LSP Client name: `eglot 20210611.2249`

### How to reproduce

1. Create a new test project: `mix new test`.
2. Edit the `lib/test.ex` file with the following content:
 ```
defmodule Test do
  @some_key 100

  def hello do
    @some
  end
end
```
3. Move cursor just after `@some` in `hello` function, then press `<TAB>` to trigger completion.
4. The code becomes the following:
```
  def hello do
    some_key
  end
```

Here, instead of completing as `@some_key`, the leading `@` was dropped.

#### Eglot

The following is the log snippet from `*EGLOT (test/elixir-mode) events*` buffer:

```lisp
(:jsonrpc "2.0" :method "textDocument/didChange" :params
          (:textDocument
           (:uri "file:///home/sheep/temp/test/lib/test.ex" :version 61)
           :contentChanges
           [(:range
             (:start
              (:line 17 :character 4)
              :end
              (:line 17 :character 9))
             :rangeLength 5 :text "")
            (:range
             (:start
              (:line 17 :character 4)
              :end
              (:line 17 :character 4))
             :rangeLength 0 :text "@some_key")
            (:range
             (:start
              (:line 17 :character 4)
              :end
              (:line 17 :character 13))
             :rangeLength 9 :text "")
            (:range
             (:start
              (:line 17 :character 4)
              :end
              (:line 17 :character 4))
             :rangeLength 0 :text "some_key")]))
```

#### Company

Please note that the value of `insertText` is `some_key` instead of `@some_key`.

```
Company 0.9.13

company-backends: (company-capf)

Used backend: company-capf
Value of c-a-p-f: (eglot-completion-at-point t)
Major mode: elixir-mode
Prefix: "@some_"
Completions:
  #("@some_key" 0 1 (eglot--lsp-item (:detail "module attribute" :documentation (:kind "markdown" :value "") :filterText "some_key" :insertText "some_key" :insertTextFormat 2 :kind 6 :label #("@some_key" 0 1 (eglot--lsp-item #2)) :sortText "00000000") face completions-common-part completion-score 0.5555555555555556) 1 2 (face completions-common-part) 2 3 (face completions-common-part) 3 4 (face completions-common-part) 4 5 (face completions-common-part) 5 6 (face completions-common-part) 6 7 (face completions-first-difference)) #(" module attribute" 1 17 (face font-lock-function-name-face))
```

### Configuration

```lisp
(use-package eglot :ensure
  :preface
  (defun elixir-get-lsp-server-path ()
    "Get LSP server path."
    (format "%s/software/elixir-ls/language_server.%s"
            (getenv "HOME")
            (if (windows?) "bat" "sh")))

  (defun eglot-format-elixir-buffer ()
    "Sort the buffer using eglot when in elixir mode."
    (interactive)
    (when (member 'eglot--managed-mode minor-mode-list)
      (eglot-format-buffer)))

  (defun eglot-find-mix-project (dir)
    "Try to locate a Elixir project root by 'mix.exs' above DIR."
    (when (or (string-suffix-p ".ex" (buffer-file-name))
              (string-suffix-p ".exs" (buffer-file-name)))
      (message "Finding ")
      (let ((mix_root (locate-dominating-file dir "mix.exs")))
        (message "Found Elixir project root in '%s' starting from '%s'" mix_root dir)
        (if (stringp mix_root) `(transient . ,mix_root) nil))))

  :config
  (add-to-list 'eglot-server-programs
               `(elixir-mode ,(elixir-get-lsp-server-path)))
  (add-hook 'project-find-functions 'eglot-find-mix-project)

  :bind
  (:map eglot-mode-map
        ("C-c C-d" . eldoc-doc-buffer))

  :hook
  (elixir-mode . eglot-ensure)
  (before-save . eglot-format-elixir-buffer))
```

**Comment by sheepduke** [comment]
Honestly, this is not necessarily an issue of elixir-ls. However, I do not have VS Code so I could not verify if it works there.

Please let me know if more information is needed to investigate it! :-)

**Comment by sheepduke** [comment]
Performing more tests and close it temporally.

**Comment by sheepduke** [comment]
Given the eglot log, was eglot sending wrong text, or was elixir-ls responding wrong result?

**Comment by axelson** [comment]
Hi there, thanks for the report!

The problem here is that `insertText` is very ambiguous. From the specification:
> /**
	 * A string that should be inserted into a document when selecting
	 * this completion. When `falsy` the label is used as the insert text
	 * for this item.
	 *
	 * The `insertText` is subject to interpretation by the client side.
	 * Some tools might not take the string literally. For example
	 * VS Code when code complete is requested in this example
	 * `con<cursor position>` and a completion item with an `insertText` of
	 * `console` is provided it will only insert `sole`. Therefore it is
	 * recommended to use `textEdit` instead since it avoids additional client
	 * side interpretation.
	 */
	insertText?: string;

A report of a similar error can be read in https://github.com/elixir-lsp/elixir-ls/issues/496 and is being tracked in https://github.com/elixir-lsp/elixir-ls/issues/28
We do plan to move to `textEdit` but we have not yet started that work (PR's welcome as always)
