### ISSUE TITLE
Builds are incorrectly skipped on `root_path` mismatch

### ISSUE THREAD

**Issue by raulchedrese** [elixir-lsp/elixir-ls#575]
### Environment

* Elixir & Erlang versions: `Elixir 1.12.0 (compiled with Erlang/OTP 24)` 
* Operating system: macOS 11.4
* Editor or IDE name: Nova
* Editor Plugin/LSP Client name: [nova-elixir-ls](https://github.com/raulchedrese/nova-elixir-ls)

In the latest version of Nova elixir-ls is not rebuilding on save. I'm seeing this error in the logs:
`skipping build because cwd changed from /Volumes/Macintosh HD/Users/raulchedrese/projects/Rayo to /Users/raulchedrese/projects/Rayo`.

Best I can tell Nova is sending these values on start up.
```
"rootPath" => "/Volumes/Macintosh HD/Users/raulchedrese/projects/Rayo",
"rootUri" => "file:///Volumes/Macintosh%20HD/Users/raulchedrese/projects/Rayo/",
```

This check then fails. https://github.com/elixir-lsp/elixir-ls/blob/6a786d7d9e7ca97a2c9c77ea4acd0057a98734d8/apps/language_server/lib/language_server/build.ex#L5

It is expecting `root_path` to be `/Users/raulchedrese/projects/Rayo`.

I was able to work around this locally by replacing the above line with:
```elixir
if !String.ends_with?(Path.absname(root_path), Path.absname(File.cwd!())) do
```

**Comment by lukaszsamson** [comment]
We need to handle it during initialise. I think the correct solution would be to cd into root_path, then get pwd and use it as root_path. Otherwise elixir is not aware that those are the same paths
```
iex(1)> Path.absname("/Volumes/Macintosh\ HD/Users/lukaszsamson")
"/Volumes/Macintosh HD/Users/lukaszsamson"
iex(2)> Path.absname("/Users/lukaszsamson")                      
"/Users/lukaszsamson"
iex(3)> Path.expand("/Volumes/Macintosh\ HD/Users/lukaszsamson") 
"/Volumes/Macintosh HD/Users/lukaszsamson"
iex(4)> Path.expand("/Users/lukaszsamson")                      
"/Users/lukaszsamson"

iex(3)> File.cd!("/Volumes/Macintosh HD/Users/lukaszsamson")
:ok
iex(4)> File.cwd!                                            
"/Users/lukaszsamson"
```

**Comment by raulchedrese** [comment]
Hey @lukaszsamson, thanks for the response!

https://github.com/elixir-lsp/elixir-ls/blob/d3fda3b12db7aea529298f7afae63e0c16a1b513/apps/language_server/lib/language_server/server.ex#L524

Replacing this line with:
```elixir
cwd_uri = SourceFile.path_to_uri(File.cwd!())
%{state | root_uri: cwd_uri}
```

Seems to resolve the issue. Does that seem like a reasonable solution?

**Comment by lukaszsamson** [comment]
> Does that seem like a reasonable solution?

@raulchedrese Yes, thats what I had in mind. Do you want to make a PR?

**Comment by raulchedrese** [comment]
Opened a PR here: https://github.com/elixir-lsp/elixir-ls/pull/579
