### ISSUE TITLE
~H sigil support

### ISSUE THREAD

**Issue by exit9** [elixir-lsp/elixir-ls#577]
### Environment

* Elixir 1.12 & Erlang 24 
* Linux 
* VSCode 
* elixir-ls-vscode

### Hello.

There's new ~H sigil in Phoenix 1.6 acts like shorthand to html.leex. Is any plans for support it? I think it would be the same as ~L sigil. And I unfortunately can't find ~L support in repo and history to make pull request myself.
https://github.com/phoenixframework/phoenix_live_view/blob/45d871f5d633c61b9304f005b9d7d86df9c252a3/lib/phoenix_live_view/helpers.ex#L703

**Comment by lukaszsamson** [comment]
Look for sigil support in https://github.com/elixir-lsp/vscode-elixir-ls
