### ISSUE TITLE
Please tag your releases!

### ISSUE THREAD

**Issue by smaximov** [elixir-lsp/elixir-ls#58]
Hello, I run into this when trying to set up Emacs integration with Elixir LS. At first, I went to the [releases](https://github.com/elixir-lsp/elixir-ls/releases) page to fetch the latest release, where I noticed that the latest version (v0.2.18) was released almost half a year ago. Then I opened Changelog, and it turned out that there were actually eight more releases with the latest one (v0.2.26) released 12 days ago. It's a little confusing for newcomers, so please, create Git tags for new releases!

**Comment by axelson** [comment]
Thanks for the nudge! Created the tags/releases. Looks like we just didn't create a tag for the new release, and didn't push the tags along with the changes from jake's repo. But now they're pushed.
