### ISSUE TITLE
Unable to read from device: :invalid_content_length

### ISSUE THREAD

**Issue by miguelverissimo** [elixir-lsp/elixir-ls#582]
The LS crashes immediately after launch with the following message:

```
Content-Length: 102

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Started ElixirLS v0.7.0","type":4}}Content-Length: 135

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Elixir version: \"1.11.4 (compiled with Erlang/OTP 23)\"","type":4}}Content-Length: 101

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Erlang version: \"23\"","type":4}}Content-Length: 129

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"ElixirLS compiled with Elixir 1.12.1 and erlang 23","type":4}}
Content-Length: 518

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"\u001B[33mwarning: \u001B[0mUnable to read from device: :invalid_content_length\n  (elixir 1.11.4) lib/stream.ex:1415: Stream.do_resource/5\n  (elixir 1.11.4) lib/stream.ex:1609: Enumerable.Stream.do_each/4\n  (elixir 1.11.4) lib/stream.ex:649: Stream.run/1\n  (stdlib 3.14.2.1) erl_eval.erl:680: :erl_eval.do_apply/6\n  (elixir 1.11.4) src/elixir.erl:280: :elixir.recur_eval/3\n  (elixir 1.11.4) src/elixir.erl:265: :elixir.eval_forms/3\n","type":2}}
```
This happens both for the precompiled releases, and built from source - the message above is from a local build.

Can't quite figure out how to go about, any direction is appreciated

### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.12.1 (compiled with Erlang/OTP 23)
* Operating system: Ubuntu 20.04.2 LTS
* Editor or IDE name (e.g. Emacs/VSCode): nvim
* Editor Plugin/LSP Client name: coc-elixir

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

### Logs

1.  If using a client other than VS Code, please try VSCode's "ElixirLS: Elixir support and debugger" extension. Does it reproduce your failure?
2.  Create a new Mix project with `mix new empty`, then open that project with VS Code and open an Elixir file. Is your issue reproducible on the empty project? If not, please publish a repo on Github that does reproduce it.
3.  Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)
4.  Check the developer console by opening `Help > Toggle Developer Tools` and include any errors that look relevant.

**Comment by lukaszsamson** [comment]
@miguelverissimo The error comes from https://github.com/elixir-lsp/elixir-ls/blob/60bbaa310e575a817763bfed3ed500501cec7ad8/apps/elixir_ls_utils/lib/packet_stream.ex#L108 or https://github.com/elixir-lsp/elixir-ls/blob/60bbaa310e575a817763bfed3ed500501cec7ad8/apps/elixir_ls_utils/lib/packet_stream.ex#L112
which means that your client is most likely sending invalid protocol messages. See https://microsoft.github.io/language-server-protocol/specifications/specification-current/#headerPart for details.
Closing as we do not support faulty clients
