### ISSUE TITLE
ElixirLS Dialyzer Warnings Support for Umbrellas?

### ISSUE THREAD

**Issue by tmepple** [elixir-lsp/elixir-ls#59]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.9.1 (compiled with Erlang/OTP 22)
* Operating system: MacOS 10.14.6
* Client (editor or IDE): VSCode 1.38.1 and ST3 v3208 (LSP plugin) as it's an LS issue not a plugin issue

### Issue

I can't get Dialyzer warnings to emit in a fresh Phoenix 1.4.9 umbrella project.  Here are the steps I took (after setting "tracing" to verbose):

1. `mix phx.new blah`
2. `code -n blah`

I made this trivial edit to `lib/blah_web/controllers/page_controller.ex`:

```elixir
  def index(conn, _params) do
    _a = blah(42)
    render(conn, "index.html")
  end

  def blah(nil), do: false
```

After a few seconds it works great telling me:

```
The function call will not succeed.

BlahWeb.PageController.blah(42)

will never return since it differs in arguments with
positions 1st from the success typing arguments:

(nil)
ElixirLS Dialyzer
```
I can see that warning in the tracing log showing the LS emitted that warning which was rendered properly by VSCode.

Now if I create an umbrella project with `mix phx.new blah --umbrella` and make the same exact change to `page_controller.ex` this warning does not show up.  Tracing log shows the LS does not send the warning to the frontend even though Dialyzer is started and the `dialyzer_manifest_22.0.7_elixir-1.9.1_test` file is created properly in `/.elixir-ls`.  There are no error messages or other anomalies in the tracing log.

Compiler warnings always work it's the Dialyzer warnings that are not emitting on umbrella projects.  I tested with Jake's LS also and the same thing is happening.  Thanks for any help!

**Comment by tmepple** [comment]
I made a failing test case in my fork: https://github.com/tmepple/elixir-ls showing dialyzer warnings are not emitted in the simplest umbrella app although they work great in regular projects.  Then I studied the code interfacing dialyzer for a PR and couldn't figure out how to make it work.

It may be that elixir-ls was never intended to integrate dialyzer with umbrella apps but I didn't see that documented anywhere or in issues.  I found something 

Installing `:dialyxir` into my umbrella root then running `mix dialyzer` from the command works but it would be nice if it were integrated into the editor.

**Comment by hworld** [comment]
Are umbrella apps supposed to be working in the current code, or is it a feature explicitly not supported? If it's a goal and it should be working, I'd love to take a stab at figuring it out. Any guidance would be really appreciated!

**Comment by axelson** [comment]
@hworld umbrella apps are intended to work with the current code, although I don't have any specific guidance on getting started.

**Comment by hworld** [comment]
All right, I've figured some stuff out. The issue seems to be that the Analyzer (`ElixirLS.LanguageServer.Dialyzer.Analyzer`) returns its warnings with files at the root of their own app within the umbrella "apps" folder. What this means is that the filename doesn't contain the app path within the umbrella. Analyzer is a very simple wrapper around dialyzer, so it seems like dialyzer just doesn't contain information we need in the returned `warnings` for the full paths.

You can see an example of the file paths returned from dialyzer for the warnings it found in this screenshot on the "before" lines:

![Screenshot from 2020-03-04 16-08-10](https://user-images.githubusercontent.com/1024321/75934804-67bc7080-5e32-11ea-897b-6f7692739d5e.png)

To come up with the "after" lines, I did some really hacky code to try to resolve the file against any of the app paths, only if it's an umbrella app:

```elixir
defp resolve_file_in_project(path) do
  if Mix.Project.umbrella?() do
    resolved_paths =
      for app_path <- Map.values(Mix.Project.apps_paths()),
          path_with_app = Path.join(app_path, path),
          File.exists?(path_with_app) do
        path_with_app
      end

    case resolved_paths do
      [] -> path
      paths -> List.first(paths)
    end
  else
    path
  end
end
```

I then injected it into the `add_warnings()` function like so:

```elixir
defp add_warnings(warnings, raw_warnings) do
    new_warnings =
      for {_, {file, line, m_or_mfa}, _} = warning <- raw_warnings,
          file = resolve_file_in_project(file),
          in_project?(file) do
        module =
          case m_or_mfa do
            module when is_atom(module) -> module
            {module, _, _} when is_atom(module) -> module
          end

        {module, {file, line, warning}}
      end

    new_warnings
    |> Enum.group_by(&elem(&1, 0), &elem(&1, 1))
    |> Enum.into(warnings)
  end
```

This fixes it. However, I'm not sure what the solution should actually be. I'm worried about possible collisions of filenames across their apps. Since umbrella apps just don't work at all, we could write the `resolve_file_in_project()` function to never match warnings if there's multiple paths found that it _could_ be. It at least wouldn't be worse than the situation now since we don't show any warning data from dialyzer in umbrellas at the moment.

Thoughts?

**Comment by axelson** [comment]
Nice catch! Is there anything in the raw warning that would tie it to a specific application in the umbrella?

**Comment by hworld** [comment]
Here's a dump of a single "raw" warning from the dialyzer analysis:

```elixir
{
    :warn_contract_subtype,
    {
        'lib/mediaex/processors/game_thumbnail.ex',
        71,
        {
            Mediaex.Processors.GameThumbnail,
            :try_screenshot_fallback,
            2
        }
    },
    {
        :contract_subtype,
        [
            Mediaex.Processors.GameThumbnail,
            :try_screenshot_fallback,
            2,
            '(\'Elixir.Lib.Models.MediaItem\':t(),\'Elixir.Lib.Models.Game\':t()) -> \'Elixir.Lib.Models.MediaItem\':t()', '(_,atom() | \#{\'id\':=_, _=>_}) -> any()'
        ]
    }
}
```

`raw_warnings` is just an array of these tuples.

The "source file" is `lib/mediaex/processors/game_thumbnail.ex` but it's really `apps/mediaex/lib/mediaex/processors/game_thumbnail.ex`.

The "smartest" thing I can think to do would be to try to do the logic I outlined above (trying to find any files that would match across all their apps), and if there's a collision, we can take the first part of the module name (the text before the first `.`) and try to resolve it against a matching app with that name.

The most common collision I can think of is for stuff like: `Mediax.Application` where they would put that under `lib/application.ex`, which would collide with all the other apps with that filename. Trying to match against the "Mediaex" part to resolve to the `apps/mediaex/lib/application.ex` seems like it would fix most cases? I'm not super knowledgeable about the layout of elixir projects, so it's hard for me to know if this would be a good solution or not.

**Comment by axelson** [comment]
To get the full source path we can use `Mediaex.Processors.GameThumbnail.module_info(:compile)[:source]`, it should generally be available: http://erlang.org/doc/reference_manual/modules.html#module_info-0-and-module_info-1-functions

It's only not available if the beam file has been stripped but I don't expect that to be the case here.

**Comment by hworld** [comment]
Aha, yeah, that worked really well! Here's the code I've got now:

```elixir
defp resolve_module(module) when is_atom(module), do: module
defp resolve_module({module, _, _}) when is_atom(module), do: module

defp resolve_module_file(module, fallback \\ "") do
  module.module_info(:compile)
  |> Keyword.get(:source, fallback)
  |> Path.relative_to_cwd()
end

defp add_warnings(warnings, raw_warnings) do
  new_warnings =
    for {_, {file, line, m_or_mfa}, _} = warning <- raw_warnings,
        module = resolve_module(m_or_mfa),
        file = resolve_module_file(module, file),
        in_project?(file) do
      {module, {file, line, warning}}
    end

  new_warnings
  |> Enum.group_by(&elem(&1, 0), &elem(&1, 1))
  |> Enum.into(warnings)
end
```
It seems to work for everything. If you're happy with this solution, I can try to get a test and a PR in place.

**Comment by axelson** [comment]
Yeah a PR with a test or two would be great :+1:
