### ISSUE TITLE
`fromPipe` command removes code in heredocs

### ISSUE THREAD

**Issue by fuelen** [elixir-lsp/elixir-ls#595]
### Environment

* Elixir & Erlang versions (elixir --version):  1.12.1 & 24.0.5
* Editor or IDE name (e.g. Emacs/VSCode):  neovim
* Editor Plugin/LSP Client name: built-in

Code:
```
list = [1, 2, 3]

"""
...
#{list |> Enum.map(&to_string/1)}
# ^ cursor is here
...
"""
```
after executing from pipe command, the block becomes this:
```elixir
list = [1, 2, 3]

"""
...
(
  
)}
# ^
...
"""
```

**Comment by lukaszsamson** [comment]
I don't think we can support that. We are manipulating AST nodes here and in AST heredoc is a simple string, not a function call. @polvalente do you agree with me?
