### ISSUE TITLE
Crash when printing into stdout inside of nif load callback

### ISSUE THREAD

**Issue by kaaboaye** [elixir-lsp/elixir-ls#604]
When you print something into `stdout` inside erlang nif initialization callback

https://erlang.org/doc/man/erl_nif.html#initialization
`int (*load)(ErlNifEnv* caller_env, void** priv_data, ERL_NIF_TERM load_info)`

ElixirLs in VScode will hang without any timeout on formatting or pretty much any other action.

![image](https://user-images.githubusercontent.com/12039839/132052937-e0ac860f-a1bd-4038-a93d-59e0220cc8d7.png)

There will be no output in ElixirLs logs after `MIX_TARGET: `

However in VScode console there will be a lot of those messages

![image](https://user-images.githubusercontent.com/12039839/132052408-a8027bce-22bf-48c4-88f7-b442b4e519f0.png)

### Workaround

Use `stderr` instead of `stdout`.
In the case of rust it will be `eprintln!` instead of `println!`.

### Minimal reproduction

https://github.com/kaaboaye/elixir-ls-stdout-when-nif-load-bug-reproduction/blob/main/native/demo/src/lib.rs
https://github.com/kaaboaye/elixir-ls-stdout-when-nif-load-bug-reproduction/blob/main/lib/plskillme.ex

### Environment

* Elixir & Erlang versions (elixir --version):  Any I think, but tested on Elixir 1.12 OTP 24
* Operating system:  Arch on x86_64 and MacOs on AARM
* Editor or IDE name (e.g. Emacs/VSCode):  VSCode
* Editor Plugin/LSP Client name: ElixirLS

**Comment by lukaszsamson** [comment]
That's expected as elixir-ls uses stdio for communication with the client. Language Server Protocol (https://microsoft.github.io/language-server-protocol/specifications/specification-current/#implementationConsiderations) states that pipes or sockets can be also used but none of this is currently supported nor planned though a PR would be welcome. For now please ensure that your NIFs do not write to stdout nor read from stdin.

**Comment by kaaboaye** [comment]
Sure I fully understand the `wontfix` however it could be a good idea to add this case to the troubleshooting section.

**Comment by lukaszsamson** [comment]
> it could be a good idea to add this case to the troubleshooting section.

Sure. A PR would be welcome
