### ISSUE TITLE
Fail when building from source

### ISSUE THREAD

**Issue by Pistrie** [elixir-lsp/elixir-ls#607]
When I run `mix compile` I get an error saying that not all dependencies are satisfied, and that I should run `mix deps.get`  to get them. This works fine for most of them but then I run into the error provided under the logs header. Rerunning `mix compile` shows that it failed to get `docsh` and `dialyxir`. I'm new to elixir and it's ecosystem, so any and all help with this will be greatly appreciated.

### Environment

* Elixir & Erlang versions (elixir --version): 
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.12.2 (compiled with Erlang/OTP 24)
* Operating system: openSUSE Tumbleweed
* Editor or IDE name (e.g. Emacs/VSCode): Doom Emacs
* Editor Plugin/LSP Client name: N/A

### Logs
```
10:33:03.618 [error] Task #PID<0.199.0> started from :hex_fetcher terminating
** (UndefinedFunctionError) function :ssl.cipher_suites/1 is undefined or private
    (ssl 10.4.2) :ssl.cipher_suites(:openssl)
    (hex 0.20.5) lib/hex/http/ssl.ex:124: Hex.HTTP.SSL.filter_ciphers/1
    (hex 0.20.5) lib/hex/http/ssl.ex:66: Hex.HTTP.SSL.ssl_opts/1
    (hex 0.20.5) lib/hex/http.ex:41: Hex.HTTP.build_http_opts/2
    (hex 0.20.5) lib/hex/http.ex:16: Hex.HTTP.request/5
    (hex 0.20.5) lib/hex/registry/server.ex:306: anonymous fn/3 in Hex.Registry.Server.prefetch_online/2
    (elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
Function: #Function<17.45335590/0 in Hex.Registry.Server.prefetch_online/2>
    Args: []
```

**Comment by lukaszsamson** [comment]
Note thet this is elixir or hex that is crashing. We run CI on OTP 24 and elixir 12 with no problems. Most likely your erlang setup is incorrect/incomplete. This happens often when using erlang as packaged by Linux distros' maintainers instead of building by asdf/kerl.

**Comment by Pistrie** [comment]
I did install it with a package manager instead of asdf. I'll try using that instead and report back with more info

**Comment by axelson** [comment]
@Pistrie :ssl.cipher_suites/1 was removed in OTP 24 (see http://erlang.org/doc/general_info/removed.html#functions-removed-in-otp-24)
This means that the version of elixir you're using does not support OTP 24. You can see the compatibility table here: https://hexdocs.pm/elixir/1.12/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp

This might be a bug with your package manager/distro. I'd recommend using asdf instead.

**Comment by Pistrie** [comment]
Yup, I tried with asdf and now it works. Thanks!
