### ISSUE TITLE
Failed to run 'elixir' command. ElixirLS will probably fail to launch.

### ISSUE THREAD

**Issue by krainboltgreene** [elixir-lsp/elixir-ls#608]
### Environment

* Elixir & Erlang versions (elixir --version): `Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit] Elixir 1.12.1 (compiled with Erlang/OTP 24)`
* Operating system: `Linux 033d18dbe177 5.4.0-1055-azure #57~18.04.1-Ubuntu SMP Fri Jul 16 19:40:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Editor or IDE name (e.g. Emacs/VSCode): `VSCode (Codespaces)`

Output logs:

```
[Trace - 9:57:33 AM] Sending request 'initialize - (0)'.
erl_child_setup closed

Crash dump is being written to: erl_crash.dump...done
[Info  - 9:57:35 AM] Connection to server got closed. Server will restart.
```

Developer Tool logs:

```
Failed to run 'elixir' command. ElixirLS will probably fail to launch. Logged PATH to Development Console.
[Extension Host] Failed to run 'elixir' command. Current process's PATH: /home/codespace/.vscode-remote/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
The ElixirLS - blank-application server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

I manually ran `/home/codespace/.vscode-remote/extensions/jakebeck…xir-ls-0.8.1/elixir-ls-release/language_server.sh` in my terminal and it booted up just fine.

**Comment by krainboltgreene** [comment]
I've done my very best to debug this myself, plus looking various issues and bug reports.

I have two guesses:

  1. Something is fundamentally wrong with my environment (see output logs)
  2. Somehow it's not picking up on my asdf install.

**Comment by lukaszsamson** [comment]
Please ensure that elixir is in PATH env of vscode process. I guess it's not correctly lading your bash_rc/bash_profile. Use search - there were already similar reports before.

> I manually ran /home/codespace/.vscode-remote/extensions/jakebeck…xir-ls-0.8.1/elixir-ls-release/language_server.sh in my terminal and it booted up just fine.

Closing as this confirms that it's not a problem with elixir-ls itself. If you find it's a problem with the vscode extension please open an issue in https://github.com/elixir-lsp/vscode-elixir-ls

**Comment by krainboltgreene** [comment]
@lukaszsamson 

It's definitely in my `.bash_rc` and `.bash_profile`. I suspect this has to do with codespaces itself.

**Comment by krainboltgreene** [comment]
@lukaszsamson Can you just move this issue over to that repo please? I don't want to have to copy and paste all this.

**Comment by lukaszsamson** [comment]
> It's definitely in my .bash_rc and .bash_profile. I suspect this has to do with codespaces itself.

What really matters is wether vscode process has proper PATH environment set.
```
cat /proc/{vscode pid}/environ | tr '\0' '\n' | grep PATH
```
Verify that the session that loads vscode loads bash_rc/pash_profile correctly.

**Comment by lukaszsamson** [comment]
> Can you just move this issue over to that repo please? 

I dont't have access in that repo. @axelson?
