### ISSUE TITLE
Credo integration

### ISSUE THREAD

**Issue by x-ji** [elixir-lsp/elixir-ls#61]
### Environment

* Elixir & Erlang versions (elixir --version): 1.8.1
* Operating system: MacOS
* Client (editor or IDE): Emacs

The codebase that I'm working on enforces strict `credo` check on the source code, so it would be nice to have credo working with flycheck, just as is the case by default under `alchemist`.

Somebody mentioned [in ElixirForum](https://elixirforum.com/t/emacs-elixir-setup-configuration-wiki/19196/108) that they also tried to do it with the following config:

```
  (add-hook 'elixir-mode-hook
    (lambda ()
      (flycheck-credo-setup)))

  (add-hook 'lsp-after-initialize-hook
            (lambda ()
              (flycheck-add-next-checker 'lsp-ui
                                         'elixir-credo)))
```

But it doesn't really work, as credo messages will only be updated in the flycheck buffer, whenever `lsp-ui` error messages are also updated.

Is there a way to make credo work with lsp? Or is it currently not possible due to some limitations?

**Comment by x-ji** [comment]
Mpanarin [in ElixirForum](https://elixirforum.com/t/emacs-elixir-setup-configuration-wiki/19196/130) mentioned that a plugin architecture might be needed for `elixir-ls` to allow integrating information from linters such as `credo`.

**Comment by lukaszsamson** [comment]
@x-ji A PR would be welcome

**Comment by lukaszsamson** [comment]
There are other language servers that wrap credo
