### ISSUE TITLE
Cannot get keyword keys completions to work

### ISSUE THREAD

**Issue by lud** [elixir-lsp/elixir-ls#611]
* Elixir & Erlang versions (elixir --version): Erlang/OTP 24 [erts-12.0.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Elixir 1.12.3 (compiled with Erlang/OTP 22)

* VSCode ElixirLS version: 0.8.1
* Operating System Version: linux 5.11.0-37-generic

Hi, I see in the README that completions include _keys in keyword functions arguments (if defined in spec)_, and I've seen it work with Ecto, although I cannot make it work for my own code (Ecto uses macros where I've seen the feature in action, I cannot find a typespec).

What is the required form of typespec for keyword keys completions to work? I've tried several ways and none works:

First with types

    @type key :: :key1 | :key2
    @type props :: [{key, term}]
    @spec my_fun(props) :: t
    
  Then with direct types and named inline type
  
    @spec my_fun([{:key1 | key2, term}]) :: t

    @spec my_fun([{key, term}]) :: t when key: :key1 | key2
    
Then with explicit pairs

    @spec my_fun([prop]) :: t() when prop: {:key1, term()} | {:key2, term()}

Is there a precise way of doing it?

Thank you

**Comment by axelson** [comment]
![Screen Shot 2021-11-14 02-04-42](https://user-images.githubusercontent.com/9973/141704393-477024da-d665-4805-81db-61df33fa4665.png)

Does this approach work for you?

**Comment by lud** [comment]
Hi,

Thank you, it works. Unfortunately it does not work anymore if I declare `@spec compute2(opts | map)` but I can create two different functions for the types.
