### ISSUE TITLE
Module ElixirLS.Utils.OutputDevice is not available VSCode error

### ISSUE THREAD

**Issue by synga** [elixir-lsp/elixir-ls#612]
### Environment

* Elixir & Erlang versions (elixir --version): 
Erlang/OTP 21 [erts-10.3] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]
Elixir 1.11.4 (compiled with Erlang/OTP 21)

* Operating system: Windows 10 Pro 64 bit
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name: ElixirLS: Elixir support and debugger v0.8.1

Hey everyone, i'm kinda new to Elixir and i'm struggling with VS Code. The extension doesn't work and it crashes when trying to initialize.

I tried creating a new empty project, since i'm starting a project with Phoenix using `mix phx.new name`, but a empty project also gives the same error.

In VS Code output i have this message:

```
[Info  - 19:56:19] Connection to server got closed. Server will restart.
** (UndefinedFunctionError) function ElixirLS.Utils.OutputDevice.get_opts/0 is undefined (module ElixirLS.Utils.OutputDevice is not available)
    ElixirLS.Utils.OutputDevice.get_opts()
    lib/wire_protocol.ex:33: ElixirLS.Utils.WireProtocol.intercept_output/2
    lib/language_server/cli.ex:6: ElixirLS.LanguageServer.CLI.main/0
    (stdlib 3.8) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.4) lib/code.ex:341: Code.eval_string_with_error_handling/3
```

It tries 5 times before it crashes, then it throws a error alert saying it crashed 5 times and it's not trying again. In my developes tools it gives the same error.

I was also using a Credo extension, but i removed it to test if there was a conflict between them, but it gives te same error.

Is there something i can do? Thanks in advance.

**Comment by lukaszsamson** [comment]
@synga can you upgrade to a supported release. if not you can downgrade elixir-LS. I'm going to close it. Feel free to reopen if you experience it on supported versions.
