### ISSUE TITLE
Crashes when using magit's `time-machine-transient-state`

### ISSUE THREAD

**Issue by x-ji** [elixir-lsp/elixir-ls#62]
### Environment

* Elixir & Erlang versions (elixir --version): 1.8.1
* Operating system: MacOS
* Client (editor or IDE): Emacs 26.3

### Crash report template

_Delete this section if not reporting a crash_

1.  If using a client other than VS Code, please try VS Code's ElixirLS extension. Does it reproduce your failure?
  It doesn't have magit
2.  Create a new Mix project with `mix new empty`, then open that project with VS Code and open an Elixir file. Is your issue reproducible on the empty project? If not, please publish a repo on Github that does reproduce it.
  Yes
3.  Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)
  Not in VSCode
4.  Check the developer console by opening `Help > Toggle Developer Tools` and include any errors that look relevant.
  Not in VSCode

### Steps to reproduce
1. Create a new project
2. Create at least two git commits
3. Use `time-machine-transient-state` to display the state of the file under a previous commit

**Comment by lukaszsamson** [comment]
@x-ji Please provide logs if you want this fixed. Otherwise we are unable to support every Emacs plugin out there
