### ISSUE TITLE
Default for fetch dependencies should be "off"

### ISSUE THREAD

**Issue by marcandre** [elixir-lsp/elixir-ls#626]
Automatic fetching of the dependencies in the background is problematic for many people (e.g. [here](https://github.com/elixir-lsp/elixir-ls/issues/267)) and may be even more problematic with the improved semantic recompilation of upcoming Elixir 1.13, as I explain in [this issue](https://github.com/elixir-lang/elixir/issues/11392).

It would be wise to turn this setting off by default, at the very least for new users.

**Comment by axelson** [comment]
Hi @marcandre! Thanks for the report! This is something that I've been thinking about recently. I agree that we should turn the default to off.
