### ISSUE TITLE
Website deploy failed

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#635]
It failed with: `Error: Config file 'mkdocs.yml' does not exist.`

https://github.com/elixir-lsp/elixir-ls/runs/4420319963?check_suite_focus=true

Probably easy to resolve but I wanted to file an issue for tracking.

**Comment by DaniruKun** [comment]
@axelson was this resolved? It might have been failing because no checkout step was present before the built attempt.

**Comment by lukaszsamson** [comment]
I think it's resolved now https://github.com/elixir-lsp/elixir-ls/actions/runs/2472979277
