### ISSUE TITLE
v0.9.0 elixir-ls releases zip contains files labeled 0.8.2

### ISSUE THREAD

**Issue by pojiro** [elixir-lsp/elixir-ls#637]
@axelson Thanks for your great work.

I noticed the title thing from [zips](https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.9.0). This is due to the version noted in [this commit](https://github.com/elixir-lsp/elixir-ls/pull/634/files) is 0.8.2.

If you didn't intend to do so, I think it would be less confusing to fix it.

**Comment by wingyplus** [comment]
I open a PR to fix this issue. Feel free to close it if it's intentional.
