### ISSUE TITLE
Precompiled elixir 1.13?

### ISSUE THREAD

**Issue by Sleepful** [elixir-lsp/elixir-ls#638]
I see
https://github.com/elixir-lsp/elixir-ls/pull/620
but I don't see an asset for 1.13 in 
https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.9.0

Building from `master` works fine :)

**Comment by axelson** [comment]
Thanks for the report! I'm adding 1.13 to the CI task that builds the releases: https://github.com/elixir-lsp/elixir-ls/pull/641
