### ISSUE TITLE
Phoenix Server Not Starting

### ISSUE THREAD

**Issue by sirfitzy** [elixir-lsp/elixir-ls#659]
### Issue 
Phoenix servers fail to launch on VSCode. 

Hi everyone, any help would be much appreciated :)  

I created a brand new phoenix app (https://github.com/SirFitz/new_app) and tried running with the VSCode extension, but the application never launches.
It stalls in the image below, which contains my config: 
<img width="826" alt="Screenshot 2022-01-19 at 5 48 29 PM" src="https://user-images.githubusercontent.com/88445435/150231303-3ee1a11a-3c8b-443f-af6a-5d6756066e4b.png">
 

All details about the environment are below

### Environment

* Elixir & Erlang versions (elixir --version): 1.12.3 (compiled with Erlang/OTP 24)
* Operating system: macOS 12.1
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name: ElixirLS: Elixir support and debugger

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.
- Not experiencing high CPU Usage

### Logs

1.  If using a client other than VS Code, please try VSCode's "ElixirLS: Elixir support and debugger" extension. Does it reproduce your failure? 

- I'm using ElixirLS: Elixir support and debugger v0.9.0

2.  Create a new Mix project with `mix new empty`, then open that project with VS Code and open an Elixir file. Is your issue reproducible on the empty project? If not, please publish a repo on Github that does reproduce it.
- That app works, the issue is running apps Phoenix
- Here is a fresh phoenix repository that can be used to replicate the issue: https://github.com/SirFitz/new_app

3.  Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)
- No relevant Output, ElixirLS isn't in the dropdown 

4.  Check the developer console by opening `Help > Toggle Developer Tools` and include any errors that look relevant.
- No relevant errors in the console
<img width="555" alt="Screenshot 2022-01-19 at 5 46 48 PM" src="https://user-images.githubusercontent.com/88445435/150230741-db8d52dd-af88-441b-9933-e2ec06a884e1.png">

**Comment by lukaszsamson** [comment]
Cannot reproduce
<img width="1007" alt="Screenshot 2022-01-23 at 10 08 21" src="https://user-images.githubusercontent.com/1078186/150671829-dc308bd4-9616-4b8d-a8f1-f270cdc4a91b.png">

Most likely your launch config is invalid. Why are you starting apps? It's this is needed only for tests. Try with
```
{
      "type": "mix_task",
      "name": "phx.server",
      "request": "launch",
      "task": "phx.server",
      "projectDir": "${workspaceRoot}"
    }
```
