### ISSUE TITLE
Add workspace symbol support

### ISSUE THREAD

**Issue by paradox460** [elixir-lsp/elixir-ls#66]
https://microsoft.github.io//language-server-protocol/specifications/specification-3-14/#workspace_symbol

There's currently per-document symbol search, but not per-workspace. Adding it allows for fairly rapid jumping from one file to another

**Comment by axelson** [comment]
Yes that would be very useful :+1: 

PR's welcome but I don't have any current plans to work on this.

**Comment by axelson** [comment]
This is now complete in #110
