### ISSUE TITLE
Incorporate nested outline view

### ISSUE THREAD

**Issue by paradox460** [elixir-lsp/elixir-ls#67]
A user against the older JakeBecker plugin implemented a nested outline view

https://github.com/kent-medin/elixir-ls/commit/14c892b4e96015345a537f68312abe1b92e1981e

This solves the old issue https://github.com/JakeBecker/elixir-ls/issues/188

![image](https://user-images.githubusercontent.com/168193/68633031-3693eb00-04a5-11ea-951e-9f795ec787e0.png)

**Comment by axelson** [comment]
Code looks okay, but I'd have to check if it applies cleanly to the current master branch
