### ISSUE TITLE
Dialyzer crashes on OTP 25 when language server compiled with older versions

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir-ls#696]
```
** (ErlangError) Erlang error: {:badrecord, {:analysis, :undefined, :succ_typings, [], :undefined, ['
...
], [], :byte_code, {:plt, #Reference<0.2999960940.2059272193.24383>, #Reference<0.2999960940.2059272193.24385>, #Reference<0.2999960940.2059272193.24384>, #Reference<0.2999960940.2059272193.24386>, #Reference<0.2999960940.2059272193.24387>}, true, false, false, false, :none, [], []}}
    (dialyzer 5.0) dialyzer_analysis_callgraph.erl:70: :dialyzer_analysis_callgraph.start/3
```

**Comment by herbedev** [comment]
Ditto this - want to take advantage of the new compile times for ARM arch, but can't!

**Comment by elliottneilclark** [comment]
Are most developers on 25? Could elixir-ls be published with a more recent OTP version while debugging the version mismatch?

**Comment by lukaszsamson** [comment]
> Are most developers on 25

In 2 years from now. Today (I guess) most is on 23 or 24.

> Could elixir-ls be published with a more recent OTP version

Not with the current approach to building/packaging. As a side note I would like to change it as it has negative impact in other cases.

As for now you can clone the repo (or vscode extension repo) and build on OTP 25.
