### ISSUE TITLE
Auto completion for struct fields

### ISSUE THREAD

**Issue by g5becks** [elixir-lsp/elixir-ls#70]
### Environment

* Elixir & Erlang versions (elixir --version):  Elixir 1.9.4
* Operating system: Mac os catalina
* Client (editor or IDE): Visual Studio Code

This is not a bug report, I merely have a question regarding the autocomplete for structs.

According to [this](https://elixirforum.com/t/introducing-elixirls-the-elixir-language-server/5857/67) elixir-ls is supposed to be able to do autocompletion for the names of struct fields. But at least for me, this literally never happens.

I am curious to know if there is something that may need to be done on my end to get this to work and also if this feature only works under certain contexts or not.

Thanks.

**Comment by axelson** [comment]
@g5becks What is supported is:
> Auto completion for struct fields inside of %SomeStruct{}

Is that what you are trying? Here's an example of it working (in Emacs but it should work in VSCode as well):
![autocomplete-screenshot](https://user-images.githubusercontent.com/9973/68996167-9d652b80-083a-11ea-8a4a-44e45d3fbd23.png)

In the screenshot the `:graph` field of the `%State{}` struct is being autocompleted.

**Comment by axelson** [comment]
Closing based on accepted solution at: https://elixirforum.com/t/auto-completion-for-struct-fields-elixir-ls/26867/2

**Comment by nadavhames** [comment]
I actually think the current completion behavior could be fine-tuned to have much better DX:

For instance, lets say I have...
```elixir
defmodule User do
  @enforce_keys [:age, :name]
  defstruct age: :nil, name: "anonymous", favorite_color: "purple"
end
```
...and somewhere else I start to make an instance of the struct. 
I think that the completion tooltip with the field options should be triggered at two more points in addition to typing out the field names themselves:
1. When the user types the first `{` of the struct syntax.
![image](https://user-images.githubusercontent.com/25757773/195411134-9848deed-e8a8-4836-b533-64ecd952421c.png)
2. When the user adds a comma to the end of an existing field 
![image](https://user-images.githubusercontent.com/25757773/195410769-d6c5a8cd-2a6a-4698-a940-39741d8b3e4a.png)


These 2 situations are perfect times to just bring up the tooltip and let the user choose from a list of all possible fields. Anyone know if this is possible to do with the lsp and if so, should I open a separate issue for this? Thanks!
