### ISSUE TITLE
Expand top-level module and select current function/symbol in breadcrumb

### ISSUE THREAD

**Issue by trkoch** [elixir-lsp/elixir-ls#700]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 24 [erts-12.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace], Elixir 1.13.3 (compiled with Erlang/OTP 24)
* VSCode ElixirLS version: 0.9.0
* Operating System Version: darwin 21.3.0

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor 

### Issue

The top-level module of the file is not expanded in breadcrumbs. It doesn't expand no matter how wide the window is, or where the cursor is positioned.

<img width="513" alt="image" src="https://user-images.githubusercontent.com/73974/159002514-85b98440-b5f9-4cdc-a0c0-ce16a0275bcb.png">

When on a function within a module and running the command `breadcrumbs.focusAndSelect`, the top-level module is shown instead of the current function.

<img width="570" alt="image" src="https://user-images.githubusercontent.com/73974/159003487-a6afd183-edba-4ee8-a2d1-302096afc94b.png">

Data coming from the language server seems to be correct, e.g. the outline view and breadcrumbs (once expanded) look fine and selecting an item jumps to the expected position.

<img width="208" alt="image" src="https://user-images.githubusercontent.com/73974/159002903-0d4ef150-0c81-4417-8471-817a01eb9446.png">

Behavior is the same in current VSCode Insiders build.

**Comment by lukaszsamson** [comment]
> My guess is that vscode expects proper ranges returned in documentSymbols request and we return empty ranges (i.e. start line 5, start char 2, end line 5, end char 2)

Yes, that was it. I added an implementation returning ranges for most symbols (defmodule, def, attribute, test) where elixir parser returns sufficient metadata. Unfortunately as of elixir 1.13 selection ranges work reliably only for defs (and defs with params). There is no metadata in AST and more difficult hacks would be necessary.
