### ISSUE TITLE
Proposal: Package elixir-ls as an escript 

### ISSUE THREAD

**Issue by Benjamin-Philip** [elixir-lsp/elixir-ls#711]
I have been procrastinating in making the switch from `alchemist.el` for a few months now.
I realised that the main reason that I have not made the switch yet is because I don't want to manually download and manage elixir-ls binaries as is the current norm. 

Another project that I have contributed to, [Livebook](https://github.com/livebook-dev/livebook) supports multiple methods of installation, which includes, cloning from source, installing an escript from hex, or as a docker image.

While I don't expect a docker image, I do think that having a installation option via `mix escript.install` would very useful, and less tedious than manually cloning from source and building the binaries / downloading release binaries.

Thus I have 2 questions:

1. Is this possible with elixir-ls? Is there any reason why this hasn't already been done?
2. Would a PR for such functionality be accepted?

**Comment by lukaszsamson** [comment]
Please continue discussion in https://github.com/elixir-lsp/elixir-ls/issues/115
