### ISSUE TITLE
changing .elixir_ls path

### ISSUE THREAD

**Issue by ignamartinoli** [elixir-lsp/elixir-ls#723]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.13.4 (compiled with Erlang/OTP 25)
* Elixir Language Server version: 0.11.0
* Operating system: Gentoo Linux
* Editor or IDE name (e.g. Emacs/VSCode): Neovim 0.7.2
* Editor Plugin/LSP Client name and version: `nvim-lspconfig` and `mason.nvim` (`elixir_ls`)

### Current behavior

When launching the Language Server, the `.elixir_ls` directory gets created in my `$HOME`.

Is there an environment variable or something that can change the path where this directory gets created?
Can it be disabled altogether?

**Comment by lukaszsamson** [comment]
How are you launching it?

**Comment by ignamartinoli** [comment]
It gets launched by `nvim-lspconfig` and `mason-lspconfig`.

From what I set up, following [the guide](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#elixirls), the executable just gets called

**Comment by lukaszsamson** [comment]
Can you post a detailed trace? I think your client is sending `rootUri`/`rootPath`/`workspaceFolders` pointing to your `$HOME` and elixir-ls is convinced that it opens a project that needs to be compiled and it needs`.elixir_ls` dir for that. I cannot reproduce it in vscode - when I open a project dir it creates `.elixir_ls` in that project dir. When I open a single file (`rootUri` is `null`) then `.elixir-ls` is not created at all.

> Is there an environment variable or something that can change the path where this directory gets created?

No. How would you make it work? It needs to be relative to the open dir

> Can it be disabled altogether?

I don't think we can do that

**Comment by ignamartinoli** [comment]
Running `:LspLog` yields:

```
[START][2022-10-06 17:00:21] LSP logging initiated
[WARN][2022-10-06 17:00:21] .../lua/vim/lsp.lua:1072	"server_request: no handler found for"	"workspace/diagnostic/refresh"
```

I also receive this message:

```
LSP[elixir][Info] Did not receive workspace/didChangeConfiguration notification after 5 seconds. Using default settings.
```

**Comment by lukaszsamson** [comment]
This looks like a configuration issue on your end. Please use forum for help or post a reproduction steps.
