### ISSUE TITLE
Plugin for Lapce

### ISSUE THREAD

**Issue by mayel** [elixir-lsp/elixir-ls#728]
I wonder if someone has already considered creating a LSP plugin for https://lapce.dev (a new GUI code editor in Rust)

See here for existing examples: https://github.com/lapce-community

**Comment by lukaszsamson** [comment]
I haven’t heard of one yet

**Comment by mayel** [comment]
I've started an attempt: https://github.com/mayel/lapce-elixir-ls

**Comment by lukaszsamson** [comment]
@mayel please send a PR with links added to Readme and docs

**Comment by mayel** [comment]
👍 Will do once the plugin works 🤞
