### ISSUE TITLE
Add clear and reset dialyzer commands

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir-ls#742]

**Comment by olivermt** [comment]
Just FYI and thanks to @mfeckie on elixir slack:
![image](https://user-images.githubusercontent.com/737765/218980115-a922f1d1-f693-48fa-b12c-27f7cf5bcaad.png)
This will do the same effect if it goes stale on you, without having to restart all of vscode

**Comment by lukaszsamson** [comment]
With OTP 26+ incremental dialyzer this is no longer needed
