### ISSUE TITLE
Compilation tracer sometimes causes the entire mix project to recompile

### ISSUE THREAD

**Issue by connorlay** [elixir-lsp/elixir-ls#745]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Elixir Language Server version: current `master`
* Operating system: Pop_OS! 22.04 LTS
* Editor or IDE name (e.g. Emacs/VSCode): Helix `master` https://github.com/helix-editor/helix
* Editor Plugin/LSP Client name and version: Helix (lsp client is built-in)

### Current behavior

git bisect led me to this commit: e95dcc5df14c13a09560a31cb4a118f7b3a25b3c

On the latest stable version of elixir-ls `v0.11.0`, saving a file triggers recompilation for just that file and its dependencies. On `master`, saving a file _sometimes_ causes the entire mix project to be recompiled. For large phoenix monoliths this essentially makes the language server unusable ☹️ 

I'm still figuring out consistent reproduction steps for this issue, but I want to open an issue now to start tracking this if others are experiencing it. The project that I'm seeing this is closed-source, so I can't share much at the moment.

Possible culprits worth further investigation (more may be added):

- [ ] mix dependencies using relative paths (aka "poncho projects")
- [ ] helix's lsp client (cc @the-mikedavis)
- [ ] MIX_ENV=test as the default for elixir-ls
- [ ] could this be platform specific to Linux

If or when I have the issue isolated and reproducible, I'll publish a repository 🙂 

### Expected behavior

Saving a file should only recompile what is necessary, not the entire mix project.

**Comment by lukaszsamson** [comment]
The commit did no relevant changes to build. If it somhow triggers a recompilation then it’s elixir or mix behavior. If you run mix compile with the same MIX_ENV it should rebuild exactly the same files.
Please note that I plan to add a one time forced recompilation after enabling tracing so elixir-ls is able to rebuild it’s databases. Rebuild on every save is obviously not intended.

**Comment by connorlay** [comment]
Thanks @lukaszsamson , I'll see if I can cause this behavior to occur outside of the language server 🙂

**Comment by connorlay** [comment]
Alright, I think this might be an issue specific to Helix. I cannot reproduce this when using VS Code as my client 🤔
