### ISSUE TITLE
"completion--some: Wrong type argument: stringp, nil" when trying to select autocompletion at point

### ISSUE THREAD

**Issue by wzin** [elixir-lsp/elixir-ls#75]
### Environment

* Elixir & Erlang versions (elixir --version):

```
Erlang/OTP 22 [erts-10.5.5] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.9.4 (compiled with Erlang/OTP 21)
```

* Operating system:

```
Ubuntu 18.04.3 LTS
```

* Client (editor or IDE):

```spacemacs on GNU Emacs 26.3```

### How to reproduce

1. have auto-completion and elixir-ls in latest version
2. try typing:

Enum.t (press tab)

3. the completion-at-point appears, select whatever suggested entry and press enter
4. nothing happens, the messages buffer contains `completion--some: Wrong type argument: stringp, nil` log entry after enter was pressed

Desired outcome: Enum.t is replaced by the suggested completion line item.

This issue might be specific to my configuration and setup or might event be not specific to elixir-ls but I would appreciate any help on this issue.

**Comment by lukaszsamson** [comment]
I'm sorry but this does not look like an elixir-ls problem as completion is working fine in vscode. I'm not using emacs and the extensions you mentioned but a simple google search on the error message hints that it is an emacs specific problem. I suggest checking your configuration or the extensions you are using.

**Comment by NobbZ** [comment]
Please tell us what LSP-client you use, `lsp-mode` or `eglot`, perhaps a lesser known one?

Also show relevant configuration.

Does this also happen when you use `company` or `autocomplete` with your LSP-client (depending on what it has a backend for). I've rarely seen someone using the builtin completion mechanisms…

Anyway, from currently available data points I'd say either your LSP-client or its configuration is broken/incorrect.

**Comment by axelson** [comment]
@wzin are you using the development version of spacemacs?
