### ISSUE TITLE
ElixirLS debugger has crashed

### ISSUE THREAD

**Issue by NikitaNaumenko** [elixir-lsp/elixir-ls#760]
### Environment

* Elixir & Erlang versions (elixir --version):  Erlang/OTP 24 [erts-12.0.3] Elixir 1.12.2 (compiled with Erlang/OTP 24)
* Elixir Language Server version: 0.11
* Operating system: macos ventura
* Editor or IDE name (e.g. Emacs/VSCode):   vscode, nvim
* Editor Plugin/LSP Client name and version: elixirLS(vscode), nvim-lsp config

### Current behavior
Hello! When I just run elixir ls debugger nothing happened, it just crashes silently with no log
My config is
`{

    "version": "0.2.0",
    "configurations": [
        {
            "type": "mix_task",
            "name": "mix (Default task)",
            "request": "launch",
            "projectDir": "${workspaceRoot}"
        },
        {
            "type": "mix_task",
            "name": "mix test",
            "request": "launch",
            "task": "test",
            "taskArgs": [
                "--trace"
            ],
            "startApps": true,
            "projectDir": "${workspaceRoot}",

        },
        {
            "type": "mix_task",
            "name": "phx.server",
            "request": "launch",
            "task": "phx.server",
            "projectDir": "${workspaceRoot}"
          }
    ]
}`

<img width="801" alt="image" src="https://user-images.githubusercontent.com/18601102/199966712-d1a571bf-102e-4a21-9bcc-a5ed2a5e0e29.png">

The same issue in neovim with nvim-dap plugin, I tried many configs from readme, but the result always the same
### Expected behavior

Should work or raise any exception

**Comment by NikitaNaumenko** [comment]
I've checked it on 1.14 and otp 25 it works fine

**Comment by lukaszsamson** [comment]
I can't reproduce it
```
Started ElixirLS Debugger v0.12.0ElixirLS Debugger built with elixir "1.11.4" on OTP "22"Running on elixir "1.12.3 (compiled with Erlang/OTP 24)" on OTP "24"
==> elixir_make
Compiling 1 file (.ex)
Generated elixir_make app
```
Can you post a project that reproduces this crash on ElixirLS 0.12?

**Comment by NikitaNaumenko** [comment]
First of all, thank for your response
You cant reproduce it because you run it on 1.12.3, on 1.12.3 it works, but on 1.12.2 still same issue
<img width="716" alt="image" src="https://user-images.githubusercontent.com/18601102/201399792-52c845d4-281a-4083-8b90-55c4a1aadf6d.png">

**Comment by lukaszsamson** [comment]
Elixir 1.12.2 release broke backwards compatibility, see https://github.com/elixir-lsp/elixir-ls/issues/571
If possible upgrade to 1.12.3 or newer
