### ISSUE TITLE
allow disabling automatic alias insertion

### ISSUE THREAD

**Issue by LukasKnuth** [elixir-lsp/elixir-ls#774]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 24 [erts-12.1.5], Elixir 1.13.0 (compiled with Erlang/OTP 22)
* VSCode ElixirLS version: 0.12.0
* Operating System Version: darwin 21.6.0
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name and version: v0.12.0

### Current behavior

When looking for a Module via auto-completion, such as "Application", many items are shown to select from:

<img width="527" alt="image" src="https://user-images.githubusercontent.com/692211/202404334-21bee05c-a6f9-49c8-9064-617d8d820b10.png">

These suggestions all look the same. If I auto-complete the first one, it automatically adds

```
alias Plug.Crypto.Application
```

to the top of my file. This is not what I'm looking for.

Additionally, if I have modules inside of my Module, autocompleting these anywhere will add an alias as well, which I guess is correct but also useless:

```
defmodule A do
  # THIS is added when auto completing in f/0
  alias A.B

  defmodule B do
    # some stuff here
  end

  def f do
    B.something()
  end
end
```

I looked through the extension settings but can't find a way to disable this feature. I looked though the code in #722 (which I understand introduces this feature) but couldn't find anything either.

### Expected behavior

* Order the suggestions "shortest module path first"
  * For example, `Application` before `Plug.Crypto.Application`
* Include the full module path into the suggestions so that you have to type the full module _once_, but for already aliased modules, no lookup is performed
* **OR** let me deactivate the auto-alias behaviour entirely

**Comment by mindok** [comment]
+1 from me too. Spent a while figuring out why `NaiveDateTime.from_iso8601!` wasn't working. It had snuck in an alias `Timex.NaiveDateTime`. Seeing the details of the module would be great, so at least you can pick the right one - the auto-alias functionality is really handy until there are module name clashes.

**Comment by mindok** [comment]
> Also, it's puzzling to me why `DidChange` and `DidChangeConfiguration` appear in the list at all, since they don't start with `Diag`.

Fuzzy search.

**Comment by scohen** [comment]
That’s pretty darn fuzzy 😂

**Comment by lukaszsamson** [comment]
I think we need to display full module name if the alias is going to be inserted (or some other visual information). There's a detail field but it's not displayed by default. 
Regarding protocol implementations, I think we should deprioretize them.

**Comment by scohen** [comment]
I'd go further for protocol implementations and eliminate them entirely, I've never once needed to alias one. It's noisy and there are a lot of them.

**Comment by wodow** [comment]
I desperately want to turn this off -- it's causing a couple of unnoticed bugs per day at the moment.

I will roll back to v0.11 for now but will try to understand how (IDE-independent?) configuration is possible to add a config flag.

**Comment by lukaszsamson** [comment]
I decided to completely remove auto aliasing of protocol implementations. This should cut a big part of unwanted items. I'm also experimenting with improvements to displaying of those alias items. `labelDetails.description` added in LSP 3.17 (https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItemLabelDetails) seems like a reasonable place to put additional alias metadata. In vscode the result is
<img width="1020" alt="Screenshot 2022-12-11 at 00 11 50" src="https://user-images.githubusercontent.com/1078186/206878884-3e6906db-2848-45d2-8d76-058bbc964101.png">
WDYT?

**Comment by mindok** [comment]
@lukaszsamson - that's a big improvement on both fronts (removing the protocol implementations, and adding the description).

Given the functionality silently updates the code (although in much better ways with the first two changes), I still think it makes sense to have the option to disable it.

**Comment by paulanthonywilson** [comment]
> I desperately want to turn this off -- it's causing a couple of unnoticed bugs per day at the moment.

I too vote for the ability for this to be disabled, or removed altogether. I am sure that it seemed like a good idea but I don't think I've every found it useful  but regularly get caught out by unintentional incorrect aliasing, often in weird places, all the time.

**Comment by mvkvc** [comment]
Yes `alias nil` keeps being imported for me as well and very often. In general being able to disable the auto adding of imports would be great for me.

**Comment by lukaszsamson** [comment]
PR please. And please post a piece of code that reproduces `alias nil`

**Comment by c4710n** [comment]
If setting aside the issue with `alias nil` for now, I'd like contribute **the feature for disabling automatic alias insertion**.

* I have located the key code at [apps/language_server/lib/language_server/providers/completion.ex](https://github.com/plastic-forks/elixir-ls/blob/23de15fae3cc9056679537c9b4ab7d97e7940dd8/apps/language_server/lib/language_server/providers/completion.ex#L158).
* I also plan to add a new configuration for controlling this feature. Currently, I have several options to choose:
  - `elixirLS.suggestAlias`
  - `elixirLS.autoInsertRequiredAlias`
  - @LukasKnuth Perhaps you could also give me a suggestion.
  
@LukasKnuth, am I on the right road?

**Comment by lukaszsamson** [comment]
`elixirLS.autoInsertRequiredAlias` looks OK
