### ISSUE TITLE
Failing to run on M2 Mac

### ISSUE THREAD

**Issue by lawik** [elixir-lsp/elixir-ls#780]
### Environment

* Elixir & Erlang versions (elixir --version): Both Elixir 1.14.2, OTP 25 and some other one
* Elixir Language Server version: 0.12
* Operating system: MacOS Monterey
* Editor or IDE name (e.g. Emacs/VSCode): VSCode

### Current behavior

With version 0.12 the LS output entirely stopped at indicating the version of Elixir and Erlang. Nothing further happened. No .elixir_ls folder, essentially only syntax highlighting was working. There was really. not logs, even under verbose that indicated any problems.

Reverting to version 0.11 seems to have fixed it.

I'm entirely unclear about how this should be triggered.

**Comment by lukaszsamson** [comment]
Please share the output of
```
~/.vscode/extensions/jakebecker.elixir-ls-0.12.0/elixir-ls-release/language_server.sh
```
should be similar to
```
Content-Length: 103

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Started ElixirLS v0.12.0","type":3}}Content-Length: 130

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"ElixirLS built with elixir \"1.11.4\" on OTP \"22\"","type":3}}Content-Length: 151

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Running on elixir \"1.14.2 (compiled with Erlang/OTP 25)\" on OTP \"25\"","type":3}}
```

**Comment by lawik** [comment]
Yeah, that's what I'm getting.

**Comment by lukaszsamson** [comment]
Then the server is starting. There may be some other issue in your setup.

**Comment by lawik** [comment]
I have no idea what. I've cleaned out extension, reinstalled and so on.

Installing the 0.11 version gives a bit more information. I tried a while back and it never proceeded past the Dialyzer line below. As I recall I let it sit for hours. It still gets stuck there.

```
Started ElixirLS v0.11.0
Elixir version: "1.14.2 (compiled with Erlang/OTP 25)"
Erlang version: "25"
ElixirLS compiled with Elixir 1.11.4 and erlang 22
MIX_ENV: test
MIX_TARGET: host
[Info  - 9:55:08 PM] Compile took 429 milliseconds
[Info  - 9:55:08 PM] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 9:55:08 PM] [ElixirLS WorkspaceSymbols] Indexing...
[Info  - 9:55:08 PM] [ElixirLS Dialyzer] Found 270 changed files in 76 milliseconds
[Info  - 9:55:09 PM] [ElixirLS Dialyzer] Analyzing 270 modules: [.. cut for length ..]
```

**Comment by lawik** [comment]
Two restarts seem to have fixed it. May have been a kernel extension pending install.
