### ISSUE TITLE
Testing panel can't run test files that contain doctests

### ISSUE THREAD

**Issue by sevenseacat** [elixir-lsp/elixir-ls#781]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Elixir Language Server version: Started ElixirLS v0.12.0 // ElixirLS built with elixir "1.11.4" on OTP "22"
* Operating system: MacOS Ventura
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name and version: ??

### Current behavior

I just today noticed that VSCode has a Testing panel in the sidebar, that seems to integrate with ElixirLS to be able to run my tests.

<img width="941" alt="Screenshot 2022-12-02 at 6 33 33 pm" src="https://user-images.githubusercontent.com/543859/205273310-b9b20331-c6d5-40c5-b545-b21c5d93e45e.png">

However, clicking the "run" triangle (or running the tests from the panel) hangs, with "tests in progress" icon.

The ElixirLS logs show an error - 

```
[Trace - 6:30:13 PM] Received response 'workspace/executeCommand - (50)' in 16ms. Request failed: %MatchError{term: "doctest Y2015.Day01.part2/3 (6)"} (-32000).
```

(The doctests don't seem anything out of the ordinary - https://github.com/sevenseacat/advent_of_code/blob/main/lib/y2015/day01.ex )

This error happens even if I fully quantify the doctest line (ie. don't use the aliased form).

If I comment out the doctest line in the test file, then the "run" triangle appears for individual tests as well as the whole file, and the tests can be run successfully.

<img width="954" alt="Screenshot 2022-12-02 at 6 35 48 pm" src="https://user-images.githubusercontent.com/543859/205273715-baf1465c-5004-4d2c-a2e2-fce1497f221c.png">

(I do have test lenses enabled, but these errors occur even when disabled - seems this testing panel is separate from that functionality) 

### Expected behavior

With the doctest line uncommented, individual tests from the file (or the whole file) should be able  to be run without error. Ideally there should be a "run" icon next to the doctest line too, to be able to run the doctests, but that might be too hard!

**Comment by lukaszsamson** [comment]
Fixed in https://github.com/elixir-lsp/elixir-ls/pull/800 and https://github.com/elixir-lsp/vscode-elixir-ls/pull/293
