### ISSUE TITLE
Diagnostic show in wrong line

### ISSUE THREAD

**Issue by csokun** [elixir-lsp/elixir-ls#782]
### Environment

* Elixir & Erlang versions (elixir --version): 1.14.2 OTP 24
* Elixir Language Server version: 
* Operating system: Linux
* Editor or IDE name (e.g. Emacs/VSCode): nvim
* Editor Plugin/LSP Client name and version: v0.12.0

### Current behavior
neovim:
![image](https://user-images.githubusercontent.com/29750/205416269-307c9b89-ab98-4906-8d5b-334ae5c1da81.png)

vscode:
![image](https://user-images.githubusercontent.com/29750/205416411-0a7d2e8d-ef21-4123-ad25-6f5acdac3d30.png)

Example code:

```elixir
defmodule Mix1 do
 def hello do
    test "Smith
  end

  def test(name) do
    "name: #{name}"
  end

  def print() do
    "Tell me more!"
  end
end
```

### Expected behavior

Diagnostic line should be 4.

**Comment by NobbZ** [comment]
No.

The error is `name:`, before that there is just a string. Elixir itself will give you the same error.

**Comment by lukaszsamson** [comment]
@csokun If you believe this is an actual bug then please open an issue in [elixir-lang/elixir](https://github.com/elixir-lang/elixir)
