### ISSUE TITLE
line_length option is not taken into account

### ISSUE THREAD

**Issue by fchabouis** [elixir-lsp/elixir-ls#785]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.14.1 (compiled with Erlang/OTP 24)
* Elixir Language Server version: 
* Operating system: Ubuntu 20.04
* Editor or IDE name (e.g. Emacs/VSCode):  VSCode
* Editor Plugin/LSP Client name and version: ElixirLS: Elixir support and debugger v0.12.0

### Current behavior

When I format my code using ElixirLS extension, my code is formatted with a maximum length size of 100. But in my formatter.exs, I have set it to 120. If I use `mix format`, the line length of 120 is used. Is this setting supposed to used?

I have seen no associated logs

### Expected behavior

I would expect the `line_length` option in formatter.exs to be used by ElixirLS formatter.

**Comment by axelson** [comment]
Hi @fchabouis, I think it sounds like you're likely hitting https://github.com/elixir-lsp/elixir-ls/issues/526

Are you able to reproduce this error on a minimal elixir project?

**Comment by fchabouis** [comment]
Hi @axelson ,
You're right, on a smaller project, the line_length is taken into account.

**Comment by lukaszsamson** [comment]
Addressed in https://github.com/elixir-lsp/elixir-ls/pull/890
Requires elixir 1.15
