### ISSUE TITLE
Feature Request: Auto interpret files stepped into or out of.

### ISSUE THREAD

**Issue by CharlesIrvineKC** [elixir-lsp/elixir-ls#795]
I have a Phoenix project that times out at startup in multiple places unless I set "debugAutoInterpretAllModules" to false. 

If I set a breakpoint, my code will stop at the breakpoint as intended. It would be nice if step-into or step-out-of would auto interpret any necessary files so that those files could be stepped into.

Is this feasible?

**Comment by lukaszsamson** [comment]
That's currently not possible. We are limited to what OTP debugger supports (see https://www.erlang.org/doc/man/int.html + some not documented features). Please open a feature request in OTP repo.
