### ISSUE TITLE
Various false errors when updating files without bouncing the debugger.

### ISSUE THREAD

**Issue by CharlesIrvineKC** [elixir-lsp/elixir-ls#797]
I'm running phoenix 1.7 RC 1 with the ElixirLS debugger. I notice that when I update a file without bouncing the debugger, various false errors are reported. Is this expected behavior? If not, I'd be glad to gather more data for debugging purposes.  Thanks for the great plugin!

**Comment by lukaszsamson** [comment]
Are you using phoenix live reload under debugger? That’s not supported as live reloader is not aware of debugger and vice versa

**Comment by CharlesIrvineKC** [comment]
Being new to Phoenix, I actually don't know what "phoenix live reload" is. I'm using the automatic reload capability the comes with an app created with phx.new. Given that, do you think I'm using "phoenix live reload"?

**Comment by CharlesIrvineKC** [comment]
Doing a little research, it seems that a phoenix app does use "live reload". So, it seems that this issue should be closed. Agreed?

**Comment by lukaszsamson** [comment]
Yes. I've found an older issue https://github.com/elixir-lsp/elixir-ls/issues/798. Anyway since it's not the first time someone bumps into this I'm going to open an issue in phoenix repo
