### ISSUE TITLE
Add support for function components

### ISSUE THREAD

**Issue by tcoopman** [elixir-lsp/elixir-ls#804]
It would be great if function components in heex were detected and all the support like regular functions works for it.

**Comment by blakedietz** [comment]
This would be an awesome addition. Does anyone have pointers on where I could start to implement this myself?

**Comment by lukaszsamson** [comment]
Is this project the right place to implement support for library specific DSLs?

**Comment by tcoopman** [comment]
I get that this might not be the right place, but I also have no idea what the right place would be?

**Comment by lukaszsamson** [comment]
A dedicated phoenix language server? I know there are vscode extensions
