### ISSUE TITLE
Generated beam file paths exceed filesystem limits

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#832]
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 24 [erts-12.3.2.9] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.12.3 (compiled with Erlang/OTP 24)
```
* Elixir Language Server version: 0.13.0
* Operating system: Linux Mint
* Editor or IDE name (e.g. Emacs/VSCode): N/A
* Editor Plugin/LSP Client name and version: N/A

### Current behavior

Compilation fails on my machine due to file paths being too long with multiple errors:

> 11:56:42.241 [error] [label: {:erl_prim_loader, :file_error}, report: 'File operation error: enametoolong. Target: /home/jason/.asdf/installs/erlang/24.3.4.9/lib/asn1-5.0.18.1/ebin/Elixir.JasonVendored.Encoder.ElixirLS.LanguageServer.Experimental.Protocol.Types.TextDocument.ContentChangeEvent.TextDocumentContentChangeEvent1.beam. Function: get_file. Process: code_server.']

> ** (File.Error) could not write to file "/home/jason/elixir-ls/_build/shared/lib/language_server/ebin/Elixir.JasonVendored.Encoder.ElixirLS.LanguageServer.Experimental.Protocol.Types.TextDocument.ContentChangeEvent.TextDocumentContentChangeEvent.beam": file name too long
    (elixir 1.12.3) lib/file.ex:1054: File.write!/3
    (elixir 1.12.3) lib/kernel/parallel_compiler.ex:209: anonymous fn/3 in Kernel.ParallelCompiler.write_module_binaries/3
    (elixir 1.12.3) lib/enum.ex:1206: anonymous fn/3 in Enum.flat_map/2
    (stdlib 3.17.2.2) maps.erl:410: :maps.fold_1/3
    (elixir 1.12.3) lib/enum.ex:2397: Enum.flat_map/2
    (elixir 1.12.3) lib/kernel/parallel_compiler.ex:182: Kernel.ParallelCompiler.spawn_workers/3
    (mix 1.12.3) lib/mix/compilers/elixir.ex:89: Mix.Compilers.Elixir.compile/6
    (mix 1.12.3) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3

I'm using an ext4 with ecryptfs which I think is related to these errors. ext4 has a filename length limit of 255, but with ecryptfs (which I use to encrypt my home directory) that limit is brought down to 144 which then triggers errors on some of the `.beam` files being created, e.g. `Elixir.JasonVendored.Encoder.ElixirLS.LanguageServer.Experimental.Protocol.Types.TextDocument.ContentChangeEvent.TextDocumentContentChangeEvent.beam` is 149 characters, so 5 characters over the limit.

For reference I also get the errors from a simple `stat` call as well:
> stat 'Elixir.JasonVendored.Encoder.ElixirLS.LanguageServer.Experimental.Protocol.Types.TextDocument.ContentChangeEvent.TextDocumentContentChangeEvent.beam'
stat: cannot statx 'Elixir.JasonVendored.Encoder.ElixirLS.LanguageServer.Experimental.Protocol.Types.TextDocument.ContentChangeEvent.TextDocumentContentChangeEvent.beam': File name too long

I'm not sure I have any concrete recommendations, but if we could change these experimental protocol file names to be a bit shorter that would definitely fix the issue but I'm not sure what work would be involved with that since I haven't looked at that code in detail.

For now I'm building ElixirLS in a directory outside of my home directory as a workaround, and I've also moved my `~/.asdf` directory outside of my home directory (by using a symlink).

There's also the possibility that it's not worth fixing this, in that case we probably want to document this potential issue in the local development instructions of the README.

**Comment by lukaszsamson** [comment]
@axelson this is a really low limit though I remember hitting 255 limit on Windows with C# codebases. @scohen do you think it’s worth fixing? At some point we are going to ditch Experimental

**Comment by lukaszsamson** [comment]
I renamed the problematic modules and shaved of 49 characters. They are still long - max 100 but at least it's less than 144 and should fix this issue.
