### ISSUE TITLE
Invalid compile error on `scholar`

### ISSUE THREAD

**Issue by cigrainger** [elixir-lsp/elixir-ls#864]
### Environment

* Elixir & Erlang versions (elixir --version): `Elixir 1.14.3 (compiled with Erlang/OTP 25)`
* Elixir Language Server version: `v0.13.0
* Operating system: MacOS, Ubuntu
* Editor or IDE name (e.g. Emacs/VSCode): Neovim, VSCode
* Editor Plugin/LSP Client name and version: `elixir-tools.nvim`, `nvim-lspconfig`, `ElixirLS`

### Current behavior

Something strange is going on with `elixir-ls` with https://github.com/elixir-nx/scholar. It compiles fine in all `MIX_ENV`s but I get a strange diagnostic on https://github.com/elixir-nx/scholar/blob/d5f88914ad58f6e8359de3a323033340c213edd9/lib/scholar/interpolation/linear.ex#L99. Namely: the `CompileError` below. The output below is from a project that depends on `scholar`. As you can see, `elixir-ls` is effectively dead in the water. Let me emphasise that I can't repro this compile error down any regular compilation path.

```elixir
[Info] Started ElixirLS v0.13.0
[Info] ElixirLS built with elixir "1.14.3" on OTP "25"
[Info] Running on elixir "1.14.3 (compiled with Erlang/OTP 25)" on OTP "25"
[Info] Elixir sources not found (checking in /private/tmp/nix-build-elixir-1.14.3.drv-0/source). Code navigation to Elixir modules disabled.
[Info] DETS databases will be rebuilt
[Info] Loaded DETS databases in 11ms
[Info] Starting build with MIX_ENV: test MIX_TARGET: host
...
[Log] ==> scholar
[Log] Compiling 23 files (.ex)
[Log] 
== Compilation error in file lib/scholar/interpolation/linear.ex ==
** (CompileError) lib/scholar/interpolation/linear.ex:99: only variables, tuples, maps, and structs are allowed as patterns in defn, got: %Scholar.Interpolation.Linear{x: x, coefficients: coefficients}
    (nx 0.5.2) lib/nx/defn/compiler.ex:828: Nx.Defn.Compiler.compile_error!/3
    (elixir 1.14.3) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (nx 0.5.2) lib/nx/defn/compiler.ex:730: Nx.Defn.Compiler.normalize_arg/3
    (elixir 1.14.3) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (nx 0.5.2) lib/nx/defn/compiler.ex:696: Nx.Defn.Compiler.normalize_args/3
    (nx 0.5.2) lib/nx/defn/compiler.ex:365: Nx.Defn.Compiler.get_and_normalize_defn/2
    (nx 0.5.2) lib/nx/defn/compiler.ex:272: Nx.Defn.Compiler.compile_each_defn/2
    (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
[Warning] could not compile dependency :scholar, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile scholar", update it with "mix deps.update scholar" or clean it with "mix deps.clean scholar"
```

You can reproduce this pretty easily: `mix new example` and then add `{:scholar, "~> 0.1.0"}` to your dependencies. I've reproduced this on an x86-64 Ubuntu VM as well as my M1 Mac. @mhanberg was also able to reproduce on his machine.

### Expected behavior

The dependencies should compile! 🙏 

Thanks for any help you can provide. I'm also happy to take a punt at a PR if you can point me in the right direction. But right now this is breaking my development environment (and would do for anyone taking a `scholar` dependency, AFAICT).

**Comment by lukaszsamson** [comment]
This is a bug in `nx` that is triggered by compiling with `columns: true`

the AST being passed is
```
{:%, [line: 99, column: 16], [Scholar.Interpolation.Linear, {:%{}, [closing: [line: 99, column: 60], line: 99, column: 27], [x: {:x, [version: 1, line: 99, column: 31], nil}, coefficients: {:coefficients, [version: 2, line: 99, column: 48], nil}]}]}
```
meta differs and it cannot match
https://github.com/elixir-nx/nx/blob/6fe34d02ab2fcac3966bcbe6e6538206b98c9305/nx/lib/nx/defn/compiler.ex#L698

**Comment by cigrainger** [comment]
Thanks @lukaszsamson!
