### ISSUE TITLE
UndefinedFunctionError

### ISSUE THREAD

**Issue by matheuscamarques** [elixir-lsp/elixir-ls#868]
Starting ElixirLS release v0.14.3
Running in /home/sanonichan/projetos/yube/hive
** (UndefinedFunctionError) function Mix.install/1 is undefined or private
    Mix.install([elixir_ls: [github: "elixir-lsp/elixir-ls", tag: "v0.14.3"]])
    (elixir 1.11.3) lib/code.ex:931: Code.require_file/2
[Error - 21:19:26] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 21:19:26] Connection to server got closed. Server will restart.
true
[Error - 21:19:26] ElixirLS - hive client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Starting ElixirLS release v0.14.3
Running in /home/sanonichan/projetos/yube/hive
** (UndefinedFunctionError) function Mix.install/1 is undefined or private
    Mix.install([elixir_ls: [github: "elixir-lsp/elixir-ls", tag: "v0.14.3"]])
    (elixir 1.11.3) lib/code.ex:931: Code.require_file/2
[Error - 21:19:27] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 21:19:27] Connection to server got closed. Server will restart.
true
[Error - 21:19:27] ElixirLS - hive client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Starting ElixirLS release v0.14.3
Running in /home/sanonichan/projetos/yube/hive
** (UndefinedFunctionError) function Mix.install/1 is undefined or private
    Mix.install([elixir_ls: [github: "elixir-lsp/elixir-ls", tag: "v0.14.3"]])
    (elixir 1.11.3) lib/code.ex:931: Code.require_file/2
[Error - 21:19:27] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 21:19:27] Connection to server got closed. Server will restart.
true
[Error - 21:19:27] ElixirLS - hive client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 21:19:27] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Starting ElixirLS release v0.14.3
Running in /home/sanonichan/projetos/yube/hive
** (UndefinedFunctionError) function Mix.install/1 is undefined or private
    Mix.install([elixir_ls: [github: "elixir-lsp/elixir-ls", tag: "v0.14.3"]])
    (elixir 1.11.3) lib/code.ex:931: Code.require_file/2
[Error - 21:19:28] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 21:19:28] Connection to server got closed. Server will restart.
true
[Error - 21:19:28] ElixirLS - hive client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 21:19:28] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Starting ElixirLS release v0.14.3
Running in /home/sanonichan/projetos/yube/hive
** (UndefinedFunctionError) function Mix.install/1 is undefined or private
    Mix.install([elixir_ls: [github: "elixir-lsp/elixir-ls", tag: "v0.14.3"]])
    (elixir 1.11.3) lib/code.ex:931: Code.require_file/2
[Error - 21:19:28] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 21:19:28] The ElixirLS - hive server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 21:19:28] ElixirLS - hive client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 21:19:28] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097

**Comment by lukaszsamson** [comment]
Please make sure that your elixir install is correct. I've seen this error when my elixir source dir was different than my compiled dir.
Make sure you can run iex and Mix.start/Mix.install

**Comment by Betree** [comment]
I'm getting the same error with extension v0.14.5 / Elixir 1.11.4 (installed through `asdf`).

`iex` / `mix start` / `mix install` are working fine.

**Comment by lukaszsamson** [comment]
Elixir 1.11 is no longer supported since 0.13 release
