### ISSUE TITLE
Support asdf-vm installed from Arch User Repository?

### ISSUE THREAD

**Issue by Pistrie** [elixir-lsp/elixir-ls#870]
### Environment

* Elixir & Erlang versions (elixir --version): `Elixir 1.14.4 (compiled with Erlang/OTP 25)`
* Elixir Language Server version: `vscode-elixir-ls v0.14.3`
* Operating system: EndeavourOS
* Editor or IDE name (e.g. Emacs/VSCode): VSCodium
* Editor Plugin/LSP Client name and version: `vscode-elixir-ls`

### Current behavior

LSP crashes because it was unable to find the elixir executable. This is because the asdf.sh script is in `/opt/asdf-vm/` instead of `$HOME/.asdf/asdf.sh`.

Relevant VSCodium logs: `/home/sylvester/.vscode-oss/extensions/jakebecker.elixir-ls-0.14.3/elixir-ls-release/launch.sh: line 77: elixir: command not found`

Developer tools log: `Failed to run 'elixir' command. Current process's PATH: /usr/local/bin:/usr/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/sylvester/.local/share/JetBrains/Toolbox/scripts:/home/sylvester/.local/share/JetBrains/Toolbox/scripts`

Reproduction:
1. On an Arch machine install `asdf-vm` from the AUR.
1.5. Go through the installation steps on the [asdf website](https://asdf-vm.com/guide/getting-started.html#_3-install-asdf) to get it to work in the terminal
2. Install elixir through asdf
3. Run VSCode, install the elixir ls extension and open an elixir project
4. ElixirLS crashes because it didn't source the script in `/opt/asdf-vm/` and therefore can't find the elixir executable

### Expected behavior

The `launch.sh` script should also look for `asdf.sh` in `/opt/asdf-vm`

**Comment by lukaszsamson** [comment]
I'm reluctant to support every possible place where asdf-vm is getting installed. Please make sure you run the extension with correctly set environment. If your asdf is not under `$HOME/.asdf` please set [ASDF_DIR](https://asdf-vm.com/manage/configuration.html#asdf-dir) environment variable.
