### ISSUE TITLE
LS fails to start with Could not find an SCM for dependency :sourceror

### ISSUE THREAD

**Issue by burnstreet** [elixir-lsp/elixir-ls#875]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns] Elixir 1.14.4 (compiled with Erlang/OTP 25)
* Elixir Language Server version:  ElixirLS release v0.14.5
* Operating system: Windows 10 German
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name and version: ElixirLS: Elixir support and debugger v0.14.5

### Current behavior
ElixirLS does not start 5 times and is shut dwn

Logs:
Starting ElixirLS release v0.14.5
Running in c:/Daten/Code/elixir/servy
** (Mix.Error) Could not find an SCM for dependency :sourceror from ElixirLS.LanguageServer.Mixfile
    (mix 1.14.4) lib/mix.ex:513: Mix.raise/2
    (mix 1.14.4) lib/mix/dep/loader.ex:195: Mix.Dep.Loader.with_scm_and_app/4
    (mix 1.14.4) lib/mix/dep/loader.ex:141: Mix.Dep.Loader.to_dep/3
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (mix 1.14.4) lib/mix/dep/loader.ex:358: Mix.Dep.Loader.mix_children/2
    (mix 1.14.4) lib/mix/dep/loader.ex:316: anonymous fn/4 in Mix.Dep.Loader.mix_dep/2
    (mix 1.14.4) lib/mix/project.ex:397: Mix.Project.in_project/4
[Error - 10:39:19 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:39:19 AM] Connection to server got closed. Server will restart.
true

Repro
open VS with empty mix project
uninstalling / reinstalling VS Code plugin did not help

### Expected behavior
it starts

**Comment by lukaszsamson** [comment]
Please ensure if you have hex installed. If you do please try removing all files and dirs from `Mix.Utils.mix_cache()`

**Comment by burnstreet** [comment]
hex was installed, clearing the cache helped

**Comment by lukaszsamson** [comment]
I'm going to close this. If anybody has repro steps for the stacktrace please post it here or report to elixir bugtracker
