### ISSUE TITLE
The extension does not work in Ubuntu + VS-code

### ISSUE THREAD

**Issue by simbadmorehod** [elixir-lsp/elixir-ls#877]
`Starting ElixirLS release v0.14.5
Running in /home/dmitry/Elixir/w3
could not compile dependency :sourceror, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile sourceror", update it with "mix deps.update sourceror" or clean it with "mix deps.clean sourceror"
[Error - 17:46:49] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 17:46:49] Connection to server got closed. Server will restart.
true
[Error - 17:46:49] ElixirLS - w3 client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Starting ElixirLS release v0.14.5
Running in /home/dmitry/Elixir/w3
could not compile dependency :sourceror, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile sourceror", update it with "mix deps.update sourceror" or clean it with "mix deps.clean sourceror"
[Error - 17:46:52] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 17:46:52] Connection to server got closed. Server will restart.
true
[Error - 17:46:52] ElixirLS - w3 client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Starting ElixirLS release v0.14.5
Running in /home/dmitry/Elixir/w3
could not compile dependency :sourceror, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile sourceror", update it with "mix deps.update sourceror" or clean it with "mix deps.clean sourceror"
[Error - 17:46:56] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 17:46:56] Connection to server got closed. Server will restart.
true
[Error - 17:46:56] ElixirLS - w3 client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 17:46:56] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Starting ElixirLS release v0.14.5
Running in /home/dmitry/Elixir/w3
could not compile dependency :sourceror, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile sourceror", update it with "mix deps.update sourceror" or clean it with "mix deps.clean sourceror"
[Error - 17:46:59] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 17:46:59] Connection to server got closed. Server will restart.
true
[Error - 17:46:59] ElixirLS - w3 client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 17:46:59] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Starting ElixirLS release v0.14.5
Running in /home/dmitry/Elixir/w3
could not compile dependency :sourceror, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile sourceror", update it with "mix deps.update sourceror" or clean it with "mix deps.clean sourceror"
[Error - 17:47:02] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 17:47:02] The ElixirLS - w3 server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 17:47:02] ElixirLS - w3 client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 17:47:02] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 `
  
  
I am not a very experienced user, but I would like to find out what the problem is

**Comment by starcraft66** [comment]
Experiencing the same error.

```
Starting ElixirLS release v0.14.5
Running in /Users/tristan.gosselin-hane/src/lanparty-seating
could not compile dependency :elixir_ls, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile elixir_ls", update it with "mix deps.update elixir_ls" or clean it with "mix deps.clean elixir_ls"
[Error - 12:24:35 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 12:24:35 PM] Connection to server got closed. Server will restart.
true
[Error - 12:24:35 PM] ElixirLS - lanparty-seating client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Starting ElixirLS release v0.14.5
Running in /Users/tristan.gosselin-hane/src/lanparty-seating
could not compile dependency :elixir_ls, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile elixir_ls", update it with "mix deps.update elixir_ls" or clean it with "mix deps.clean elixir_ls"
[Error - 12:24:42 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 12:24:42 PM] Connection to server got closed. Server will restart.
true
[Error - 12:24:42 PM] ElixirLS - lanparty-seating client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by lukaszsamson** [comment]
How did you end up in this state? What kind of setup you use? 

Please try removing all files and dirs from `Mix.Utils.mix_cache()`

**Comment by simbadmorehod** [comment]
Actually I just installed VScode + elixir-ls and the first time I ran it I got errors, and other Ubuntu users also have this problem

**Comment by simbadmorehod** [comment]
I understand this function `Mix.Utils.mix_cache()` returns the path to the cache, below I give the content and path, should I remove this? Is this the cache?

`_build  deps  mix.lock
:~/.cache/mix/installs/elixir-1.14.0-erts-13.1.5/94e06b8c8e05a4c2d5458608f1bb0964$`

**Comment by lukaszsamson** [comment]
Yes, remove this cache. This is the place where `Mix.install` stores compiled artefacts

**Comment by simbadmorehod** [comment]
I uninstalled it but the error is still there, here's what the GPT says about it:

This message is an error message for the ElixirLS server, which is the Language Server Protocol (LSP) for the Elixir programming language. The message says that the server was unable to compile the "sourceror" dependency, and gives several options for fixing the problem. It is important to note that the error may cause the server not to start and you will not be able to use it to automatically terminate code and other LSP functions in your development environment.

**Comment by lukaszsamson** [comment]
OK. Can you open Help->Toggle Developer Tools and look for a log
```
ElixirLS: starting client for..
```
expand the `server options` -> `run` -> `command`
<img width="1105" alt="Screenshot 2023-05-06 at 20 08 10" src="https://user-images.githubusercontent.com/1078186/236640081-4a63b324-50fe-4824-91ce-633b40205da5.png">

and try to run the command in terminal from your project's directory. This is the command that starts the language server process
Please paste the output.

**Comment by starcraft66** [comment]
> Please try removing all files and dirs from `Mix.Utils.mix_cache()`

That did the trick for me, thank you.

**Comment by simbadmorehod** [comment]
ElixirLS: starting client for

> ХОРОШО. Можете ли вы открыть Help->Toggle Developer Tools и найти журнал
> 
> ```
> ElixirLS: starting client for..
> ```
> 
> развернуть `server options`-> `run`->`command` <img alt="Скриншот 06.05.2023 в 20 08 10" width="1105" src="https://user-images.githubusercontent.com/1078186/236640081-4a63b324-50fe-4824-91ce-633b40205da5.png">
> 
> и попробуйте запустить команду в терминале из каталога вашего проекта. Это команда, которая запускает процесс языкового сервера. Пожалуйста, вставьте вывод.

`Starting ElixirLS release v0.14.6
Running in /home/dmitry/Elixir/w3
could not compile dependency :sourceror, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile sourceror", update it with "mix deps.update sourceror" or clean it with "mix deps.clean sourceror"`

I tried clearing and compiling and loading a new sourceror but this does not help

**Comment by thgala** [comment]
I started experiencing the same issue few days ago (without switching the version of Elixir or Erlang).
I managed to fix it by manually compiling (and creating the release) https://github.com/elixir-lsp/elixir-ls and then replacing it with the one, used by the IDE (VSCode in my case. The path was:`.vscode/extensions/jakebecker.elixir-ls-0.14.5`).

Still not sure what is the root-cause of the issue.

**Comment by thgala** [comment]
@lukaszsamson thank you. Good to know 🤔
Unfortunately I cannot reproduce the issue anymore but cleaning the chache helped. I remember updating the `.exs` file though, which most-likely means that there was a problem with the installing script.

**Comment by languagelawyer** [comment]
@simbadmorehod do you have `erlang-dev` package installed?

**Comment by simbadmorehod** [comment]
I don't think so, but I will try to install

> @simbadmorehod do you have `erlang-dev` package installed?

**Comment by simbadmorehod** [comment]
> erlang-dev

Thanks everything works fine, I am not sure what caused it since I haven't run the development environment for a long time, but right after installing erlang-dev everything works fine

**Comment by languagelawyer** [comment]
When I tried to build `~/.cache/mix/installs/elixir-1.12.2-erts-12.2.1/.../deps/sourceror/` manually, it was complaining that `/usr/lib/erlang/lib/parsetools-2.3.2/include/yeccpre.hrl`, which is provided by `erlang-dev`, is missing

**Comment by emk** [comment]
The install instructions on the Elixir website recommend:

```sh
sudo add-apt-repository ppa:rabbitmq/rabbitmq-erlang
sudo apt update
sudo apt install elixir
```

To get ElixirLS running, you also need:

```sh
sudo apt install erlang-dev erlang-dialyzer
```
