### ISSUE TITLE
Failing documentation lookup on hover

### ISSUE THREAD

**Issue by froucoux** [elixir-lsp/elixir-ls#882]
### Precheck

Done

### Environment

* Elixir & Erlang versions (elixir --version): 
- Erlang/OTP 25.3.1 [erts-13.2.1]
- Elixir 1.14.4 (compiled with Erlang/OTP 25)
-installed with asdf version manager
* Elixir Language Server version: 
- ElixirLS v0.14.5
* Operating system: 
- Ubuntu 22.04
* Editor or IDE name (e.g. Emacs/VSCode): 
- VSCode 1.78.0
* Editor Plugin/LSP Client name and version:
Last released: 4/21/2023, 10:40:07
Last updated: 5/1/2023, 12:08:17
Identifier: jakebecker.elixir-ls

### Current behavior

No documentation displayed when hovering functions, modules ... 

ElixirLS logs :

[Error - 10:17:41 AM] Request textDocument/hover failed.
  Message: an exception was raised:
    ** (CaseClauseError) no case clause matching: %{actual_subject: ...  types: ""}, range: %{begin: {25, 7}, end: {25, 12}}}
        (language_server 0.14.5) lib/language_server/providers/hover.ex:24: ElixirLS.LanguageServer.Providers.Hover.hover/4
        (language_server 0.14.5) lib/language_server/server.ex:824: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
  Code: -32000

Hovering with mouse pointer the name of a function, module or other syntactic elements of Elixir code

### Expected behavior

Display of a small window containing the documentation related to the syntactic element. But here, nothing displayed and error raised in the log.

**Comment by lukaszsamson** [comment]
Fixed by pinning elixir_sense. Will be released in 0.14.6
