### ISSUE TITLE
Dialyzer error: Unable to build dialyzer PLT. Most likely there are problems with your OTP and elixir installation.

### ISSUE THREAD

**Issue by jameskentTX** [elixir-lsp/elixir-ls#887]
I have compiled version of erlang and elixir installed. Newest versions.

Debian 12
Vscode 1.78.2
ElixirLS: v0.14.7
Erlang: 25.3.2
Elixir: 1.14.0

**Comment by lukaszsamson** [comment]
Please include full error output.
Otherwise please use forum or slack for support. Also there has already been some solutions in https://github.com/elixir-lsp/elixir-ls/issues/540.

**Comment by lukaszsamson** [comment]
No idea. Please refer to your editor help

**Comment by jameskentTX** [comment]
No idea? I've checked elixir-ls source code. There is no additional info about error. 
`{:DOWN, ^ref, :process, ^pid, reason} ->
          JsonRpc.show_message(
            :error,
            "Unable to build dialyzer PLT. Most likely there are problems with your OTP and elixir installation."
          )
`
So I've presented full info output.

**Comment by lukaszsamson** [comment]
Besedes that message there are also logs being printed to output. You haven’t filled the issue template. I have no idea what editor you are using and how are you running elixirLS.
Can you provide a devcontainer that reproduces it? If not please reads the links provided and seek support on the forum or slack. Issue tracker is reserved for bugs

**Comment by jameskentTX** [comment]
I've mentioned vscode.
Anyway... I've installed `asdf`, installed once again erlang and elixir. Everything is working fine. Thank you for your time.

**Comment by jameskentTX** [comment]
I've solved my yesterday problem.
ElixirLS didn't work correctly because of bad permissions.
I've disabled `asdf`, reboot and after:
`sudo chown -R root:root /opt/elixir`
and
`sudo chmod -R 755 /opt/elixir`
and
update of .bashrc
`export PATH="/opt/erlang/bin:/opt/elixir/bin:$PATH"`
ElixirLS is working fine.
