### ISSUE TITLE
Server initialization failed

### ISSUE THREAD

**Issue by youroff** [elixir-lsp/elixir-ls#892]
Experiencing this behavior recently

### Environment
* Elixir & Erlang versions (elixir --version):
Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]
Elixir 1.14.5 (compiled with Erlang/OTP 25)
(global with asdf)

I had to downgrade from 1.14.5-otp-26 due to known issues with OTP 26, maybe some artifacts got stuck?
However, I was able to reproduce it on a different machine that never seen OTP 26, by deleting and reinstalling extension in VS Code.

* Elixir Language Server version:
0.14.6

* Operating system:
Mac OS 13.1 

* Editor or IDE name (e.g. Emacs/VSCode): 
VSCode

### Current behavior
```
Starting ElixirLS release v0.14.6
Running in /Users/youroff/Projects/state_machine
** (Mix.Error) Command "git --git-dir=.git checkout --quiet 896fa45817c6a1be8ec408577c88ab52c27f6851" failed with reason: fatal: reference is not a tree: 896fa45817c6a1be8ec408577c88ab52c27f6851

    (mix 1.14.5) lib/mix.ex:513: Mix.raise/2
    (mix 1.14.5) lib/mix/scm/git.ex:136: Mix.SCM.Git.checkout/2
    (elixir 1.14.5) lib/file.ex:1607: File.cd!/2
    (mix 1.14.5) lib/mix/dep/fetcher.ex:61: Mix.Dep.Fetcher.do_fetch/3
    (mix 1.14.5) lib/mix/dep/converger.ex:213: Mix.Dep.Converger.all/9
    (mix 1.14.5) lib/mix/dep/converger.ex:224: Mix.Dep.Converger.all/9
    (mix 1.14.5) lib/mix/dep/converger.ex:146: Mix.Dep.Converger.all/7
    (mix 1.14.5) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
[Error - 3:32:43 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 3:32:43 PM] Connection to server got closed. Server will restart.
true
[Error - 3:32:43 PM] ElixirLS - state_machine client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:32:43 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
```

**Comment by tetious** [comment]
Looks like the pinned commit for dialyxir has disappeared. 

```
  "dialyxir_vendored": {:git, "https://github.com/elixir-lsp/dialyxir.git", "896fa45817c6a1be8ec408577c88ab52c27f6851", [ref: "896fa45817c6a1be8ec408577c88ab52c27f6851"]},
```

That commit does not exist in the repo anymore.

**Comment by cshinaver** [comment]
also ran into this. can we just revert back to the branch like it was before?

**Comment by artimath** [comment]
I moved from brew installed erlang/elixir to ASDF-install today to get a speed-up on my mac m1 during compiles...

Then been chasing this problem down for the last few hours lol. 

Going to try and fix for myself, will comment back.

**Comment by lukaszsamson** [comment]
The commit disappeared because I force pushed to vendored branch by mistake. It should be fixed now. Sorry for inconvenience

**Comment by artimath** [comment]
Can confirm it is fixed. Thanks @lukaszsamson
