### ISSUE TITLE
Classify typespecs as TypeParameter workspace symbol

### ISSUE THREAD

**Issue by dvic** [elixir-lsp/elixir-ls#896]
Shouldn't we classify typespecs as a `TypeParameter` symbol instead of `Class`? 

https://github.com/elixir-lsp/elixir-ls/blame/10ffd298fa9e10232314908eb6b2a8fc40eac3e4/apps/language_server/lib/language_server/providers/workspace_symbols.ex#L51

In neovim telescope, I was a bit surprised to see `class` next to all the typespecs :)

**Comment by lukaszsamson** [comment]
I don't think so. IMO type parameter is for generic or higher order types, e.g. in C#
```
List<String>
```
`List` is a class, `String` is a type parameter, `List<String>` is a type.

Elixir/OTP types have a similar semantic
```
@type a :: list(String.t())
```
`String.t()` is a type parameter for type `list(t)` here but we don't have type to choose from. In https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#symbolKind Class is closest to what we need.

**Comment by dvic** [comment]
Clear, thanks for the explanation!
