### ISSUE TITLE
Can't disable auto closing of do/end block

### ISSUE THREAD

**Issue by thmzlt** [elixir-lsp/elixir-ls#905]
### Environment

  * Elixir & Erlang versions (elixir --version): Erlang/OTP 22 [erts-10.7] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [hipe]

Elixir 1.10.3 (compiled with Erlang/OTP 22)

  * VSCode ElixirLS version: 0.5.0
  * Operating System Version: linux 5.4.62
  

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

### Issue

When I type `do` to start a block and press Enter, VS Code automatically adds a matching `end` on the next line. It doesn't seem to be possible to disable that behavior.

**Comment by lukaszsamson** [comment]
@thmzlt I'm conviced you are mistaking autoclosing with snippet completions. You can disable do-end closing if you disable snippets with `editor.suggest.showSnippets`.
