### ISSUE TITLE
Everything after @doc is marked as comment when using special characters

### ISSUE THREAD

**Issue by LouisMT** [elixir-lsp/elixir-ls#911]
### Environment

* Elixir & Erlang versions (elixir --version): 1.15.0, 25.3.2.2
* Elixir Language Server version: 0.15.0
* Operating system: Ubuntu 22.04
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name and version:

### Current behavior

When using a special character in a docstring (in this example `-`), all code after the docstring is marked as a comment:

![image](https://github.com/elixir-lsp/elixir-ls/assets/1782761/4be25380-ead7-437b-be20-35281bcd7007)
![image](https://github.com/elixir-lsp/elixir-ls/assets/1782761/0258720b-4710-4568-b4c0-aa3730bc52e9)

### Expected behavior

The `def something` should be marked as code.

**Comment by LouisMT** [comment]
Related to elixir-lsp/vscode-elixir-ls#344

**Comment by saulbensach** [comment]
facing same issue, also happens with "*"

**Comment by bceskavich** [comment]
Encountering the same issue here as well

**Comment by lukaszsamson** [comment]
Wrong repo and duplicate
