### ISSUE TITLE
Server initialization fails due to rosetta error on Apple Silicon

### ISSUE THREAD

**Issue by rohfosho** [elixir-lsp/elixir-ls#914]
### Environment

* Elixir & Erlang versions (elixir --version): **Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]; Elixir 1.14.4 (compiled with Erlang/OTP 25)**
* Elixir Language Server version: **0.15.0, 0.14.7**
* Operating system: **MacOS Ventura 13.3.1**
* Editor or IDE name (e.g. Emacs/VSCode): **VSCode**
* Editor Plugin/LSP Client name and version: **ElixirLS 0.15.0**

### Current behavior

After updating to 0.15.0 on 6/21, my server began to fail initializing. I tried downgrading the VS Code extension back down to 0.14.7 but I am still getting the same error as below.

```
** (Mix.Error) Command "git -c core.hooksPath='' init --quiet" failed with reason: rosetta error: Attachment of code signature supplement failed: 1 
 /var/db/oah/a3528330a643997ee464fb4defbe1d103b81b21b75fd7c0aa3262f932715a028/fbe163bfc58bb9557a8af127ca7863122b18d906558a8845d42b26f622ea02f7/libxcrun.dylib.aot
    (mix 1.14.4) lib/mix.ex:513: Mix.raise/2
    (mix 1.14.4) lib/mix/scm/git.ex:109: anonymous fn/2 in Mix.SCM.Git.checkout/1
    (elixir 1.14.4) lib/file.ex:1607: File.cd!/2
    (mix 1.14.4) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
    (mix 1.14.4) lib/mix/dep/converger.ex:213: Mix.Dep.Converger.all/9
    (mix 1.14.4) lib/mix/dep/converger.ex:146: Mix.Dep.Converger.all/7
    (mix 1.14.4) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
    (mix 1.14.4) lib/mix/dep/converger.ex:74: Mix.Dep.Converger.converge/4
[Error - 7:32:54 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
  ```

**Comment by lukaszsamson** [comment]
This is not a problem with the extension. Please make sire you have working git. Why are you running git via rosetta emulation instead of native arm? Have you tried cleaning mix install cache dir step from troubleshooting?
