### ISSUE TITLE
Does not work on elixir 1.10

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir-ls#92]
- [x] elixir-sense version not compatible - bump to incorporate fixes from
https://github.com/elixir-lsp/elixir_sense/commit/59fe0512ce078750878ae4b4939b323f8560cc84
https://github.com/elixir-lsp/elixir_sense/commit/8b54a77cb97fa5d6d1558f60789d16dfcc5e91fd
https://github.com/elixir-lsp/elixir_sense/commit/fc8f3265443abed448fc1b5774f6175192f604e3
https://github.com/elixir-lsp/elixir_sense/commit/1e528d66127da872bdfa0bc8a02763375287a01c
https://github.com/elixir-lsp/elixir_sense/commit/5f259223d070336eeceab321642969aae97e034b
https://github.com/elixir-lsp/elixir_sense/commit/1aa09ab39f705110bb93e9624f85ae4c310c8ef9
https://github.com/elixir-lsp/elixir-ls/pull/87

- [x] https://github.com/elixir-lsp/elixir_sense/issues/76 needs fixing
- [x] https://github.com/elixir-lsp/elixir_sense/issues/75 needs fixing

- [x] dialyzer tests failing - asked for help on elixir-forum https://elixirforum.com/t/elixir-v1-10-0-rc-0-released/28086/42

- [x] clear_cache moved to Mix.State https://github.com/elixir-lsp/elixir-ls/pull/91

- [x] Code.load_file/1 is deprecated https://github.com/elixir-lsp/elixir-ls/pull/93

- [x] ~~tests crash mix~~ moved to https://github.com/elixir-lsp/elixir-ls/issues/100

**Comment by josevalim** [comment]
Things like Mix.State is also a private API, so please don't continue using private APIs. Open up an issue so we provide a public API for you to call.

About the dialyzer one, please provide a project that reproduces the error. I am assuming `mix dialyze` or similar reproduces it? It does look like an Elixir bug.

**Comment by axelson** [comment]
@lukaszsamson thanks for putting this list together and tracking down these issues!

@josevalim Posted on elixir-lang-core https://groups.google.com/forum/#!topic/elixir-lang-core/_LrWhl-kUZY (although re-reading your comment, perhaps I should have just raised an issue directly). Although in either case, this is just one of the private api usages, I'll try and do a sweep to look for the others.

**Comment by lukaszsamson** [comment]
@josevalim I looked deeper into dialyzer issue. It turns out that dialyzer is not required to trigger it at all and it might be a consequence of the fixtures used in this project.

I am able to reproduce from the root of this repo
```
$ iex -S mix
Interactive Elixir (1.10.0-rc.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> mixfile = "apps/language_server/test/fixtures/dialyzer/mix.exs"         
"apps/language_server/test/fixtures/dialyzer/mix.exs"
iex(2)> Kernel.ParallelCompiler.compile([mixfile])                              
{:ok, [ElixirLS.LanguageServer.Fixtures.Dialyzer.Mixfile], []}
iex(3)> Mix.Task.run("compile", ["--return-errors", "--ignore-module-conflict"])

19:44:23.319 [error] Task #PID<0.524.0> started from #PID<0.541.0> terminating
** (MatchError) no match of right hand side value: false
    (elixir 1.10.0-rc.0) src/elixir_erl_var.erl:14: :elixir_erl_var.translate/4
    (stdlib 3.11) lists.erl:1354: :lists.mapfoldl/3
    (elixir 1.10.0-rc.0) src/elixir_erl_clauses.erl:20: :elixir_erl_clauses.match/3
    (elixir 1.10.0-rc.0) src/elixir_erl_clauses.erl:28: :elixir_erl_clauses.clause/6
    (elixir 1.10.0-rc.0) src/elixir_erl.erl:230: :elixir_erl.translate_clause/3
    (elixir 1.10.0-rc.0) src/elixir_erl.erl:220: :elixir_erl."-translate_definition/4-lc$^0/1-0-"/2
    (elixir 1.10.0-rc.0) src/elixir_erl.erl:220: :elixir_erl.translate_definition/4
    (elixir 1.10.0-rc.0) src/elixir_erl.erl:183: :elixir_erl.split_definition/11
Function: #Function<9.64842280/0 in Mix.Tasks.Compile.Protocols.consolidate/6>
    Args: []
```

It seems that the protocol defined upper in directory hierarchy ends up in the fixture dir
<img width="471" alt="Screenshot 2020-01-11 at 20 05 45" src="https://user-images.githubusercontent.com/1078186/72209416-2a7cd780-34ae-11ea-969b-516ffbbca7d7.png">

**Comment by josevalim** [comment]
I am looking into this now. Thank you so much for isolating those, it makes my life much easier!

**Comment by josevalim** [comment]
@lukaszsamson so the command above compiled just fine for me. I am thinking you have some stale files somewhere. Try running `git clean -dfx` and removing `_build` and `deps`. Or try a separate checkout and see if you can reproduce it there.

**Comment by lukaszsamson** [comment]
@josevalim yes, it must have been some stale state. I remember doing `mix clean && mix deps.clean --all && rm -r .elixir_ls` though, it seems this was not enough. Anyway, thanks for your help.

**Comment by axelson** [comment]
@lukaszsamson regarding "tests crash mix" I'm actually seeing that same error locally on 1.9.1, it's just not failing the CI builds.

**Comment by lukaszsamson** [comment]
Yep, I can confirm it also on 1.9.4. I'm going to create a separate isse.
