### ISSUE TITLE
[Zed editor][erlang and elixir installed from asdf] Elixir-ls cannot be installed correctly with asdf.

### ISSUE THREAD

**Issue by Reoooh** [elixir-lsp/elixir-ls#929]
### Precheck

I did not find out any solution.😔

### Environment

* Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

* Elixir 1.15.2 (compiled with Erlang/OTP 26)

* Operating system: 💻 MacOS 11.7.7

* Editor or IDE name (e.g. Emacs/VSCode): Zed

### Current behavior

I'm trying to install elixir-ls via brew following the zed official tutorial: [zed setting up elixir-ls](https://docs.zed.dev/languages/elixir)
And I have already installed erlang and elixir form my asdf.

After I installed elixir-ls from brew, I wanna to check the version. So I typed ``elixir-ls -h``.When I run the compiled language server I get this until I press enter and it crashes:

```
running /opt/homebrew/Cellar/elixir-ls/0.15.1/libexec/launch.sh
Looking for ASDF install in /opt/homebrew/opt/asdf/libexec/asdf.sh
ASDF found, relaunching in bash shell
Looking for ASDF install in /opt/homebrew/opt/asdf/libexec/asdf.sh
Sourcing ASDF
Content-Length: 137

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Mix requires the Hex package manager to fetch dependencies","type":4}}Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn] y
Content-Length: 149

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"* creating .asdf/installs/elixir/1.15.2-otp-26/.mix/archives/hex-2.0.6","type":4}}Content-Length: 103

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Started ElixirLS v0.15.1","type":3}}Content-Length: 106

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Running in /Users/sunhaoran","type":3}}Content-Length: 130

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"ElixirLS built with elixir \"1.15.0\" on OTP \"25\"","type":3}}Content-Length: 151

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Running on elixir \"1.15.2 (compiled with Erlang/OTP 26)\" on OTP \"26\"","type":3}}Content-Length: 109

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Protocols are not consolidated","type":3}}Content-Length: 127

{"jsonrpc":"2.0","method":"window/showMessage","params":{"message":"OTP compiled without EEP48 documentation chunks","type":2}}Content-Length: 246

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"OTP compiled without EEP48 documentation chunks. Language features for erlang modules will run in limited mode. Please reinstall or rebuild OTP with appropriate flags.","type":2}}Content-Length: 194

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Elixir sources not found (checking in /home/runner/work/elixir/elixir). Code navigation to Elixir modules disabled.","type":3}}Content-Length: 111

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Experimental server is disabled.","type":3}}
Unable to read from device: :invalid_content_length
```

### Expected behavior

elixir-ls should be installed correctly, because
> It is generally recommended to install Elixir and Erlang via [ASDF](https://github.com/asdf-vm/asdf) so that you can have different projects using different versions of Elixir without having to change your system-installed version. ElixirLS can detect and use the version of Elixir and Erlang that you have configured in ASDF.

**Comment by lukaszsamson** [comment]
We do not support brew install nor zod tutorials. Please use those tools support channels. There’s no such command elixir-ls -h. Asdf is working in your log. You pass invalid LSP command when you enter.
