### ISSUE TITLE
Umbrella App cross References 

### ISSUE THREAD

**Issue by apoorv-2204** [elixir-lsp/elixir-ls#931]
### Environment

* Elixir & Erlang versions 1.14 and otp 25.2.2
* Elixir Language Server version: 
* Operating system:  kde 22.04 jammy
* Editor VSCode
### Current behavior
```
KCCore.Repo.all/1 defined in application :kc_core is used by the current application but the current application does not depend on :kc_core. To fix this, you must do one of:

  1. If :kc_core is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :kc_core is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :kc_core, you may optionally skip this warning by adding [xref: [exclude: [KCCore.Repo]]] to your "def project" in mix.exs
```
I have an Umbrella application, :admin app is using :kc_core app and its mentioned in mix.exs of admin that kc_core is umbrella dependency.   {:kc_core, in_umbrella: true} 

Dont want to use xref as 600 warnings.

Create an umbrella application and create multiple apps inside of it and know cross reference or cross use the apps  with menitoneing in deps that  in_umbrella: true  

### Expected behavior
Ls should detect if it is an umbrella application, and if there is cross referencing inside of umbrella apps , it should give warning to add only in deps as :app, in_umbrella: true

**Comment by lukaszsamson** [comment]
@apoorv-2204 Can you reproduce it in mix? Can you reproduce it on elixir 1.15?
Elixir 1.14 has some known bugs with app tracer https://github.com/elixir-lang/elixir/issues/12318

**Comment by lukaszsamson** [comment]
ping @apoorv-2204
