### ISSUE TITLE
Elixir-ls crashes 

### ISSUE THREAD

**Issue by roganjoshua** [elixir-lsp/elixir-ls#943]
Using Neovim but this happens from CLI using language_server.sh

### Environment

* > elixir --version
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns] 
Elixir 1.15.2 (compiled with Erlang/OTP 26) 
* Linux / Pop_OS! 
* Neovim 
* Elixir-ls

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Started ElixirLS v0.15.0","type":3}}Content-Length: 184                                                                                                                               {"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Running in /home/marty/.cache/nvim/elixir-tools.nvim/installs/elixir-lsp/elixir-ls/tags_v0.15.0/1.15.2-26","type":3}}Content-Length: 130                                               │
{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"ElixirLS built with elixir \"1.15.2\" on OTP \"26\"","type│
":3}}Content-Length: 151                                                                                                     │
{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Running on elixir \"1.15.2 (compiled with Erlang/OTP 26)\" on OTP \"26\"","type":3}}Content-Length: 109  
{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Protocols are not consolidated","type":3}}Content-Length: │
127                                                                                                                          │
                                                                                                                             │
{"jsonrpc":"2.0","method":"window/showMessage","params":{"message":"OTP compiled without EEP48 documentation chunks","type":2│
}}Content-Length: 246                                                                                                        │
                                                                                                                             │
{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"OTP compiled without EEP48 documentation chunks. Language │
features for erlang modules will run in limited mode. Please reinstall or rebuild OTP with appropriate flags.","type":2}}Cont│
ent-Length: 194                                                                                                              │
                                                                                                                         [](url)    │
{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Elixir sources not found (checking in /home/runner/work/elixir/elixir). Code navigation to Elixir modules disabled.","type":3}}
Runtime terminating during boot ({badarg,[{io,put_chars,[standard_error,[_]],[{_},{_},{_}]},{Elixir.Kernel.CLI,exec_fun,2,[{_},{_}]},{Elixir.Kernel.CLI,run,1,[{_},{_}]},{elixir,start_cli,0,[{_},{_}]},{init,start_em,1,[]},{init,do_boot,3,[]}]})                                                               
Crash dump is being written to: erl_crash.dump...done                                                                       
# tags_v0.15.0/1.15.2-26                                                                                                     │

### Current behavior

Elxir-ls crashes

### Expected behavior

Elixir-ls doesn't crash
[erl_crash.dump.tar.gz](https://github.com/elixir-lsp/elixir-ls/files/12030497/erl_crash.dump.tar.gz)

**Comment by lukaszsamson** [comment]
You are running an incompatible version. Please update to 0.15.1
