### ISSUE TITLE
Logger interception can fail

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir-ls#947]
```
an exception was raised:
    ** (RuntimeError) build without intercepted logger []
(language_server 0.15.1) lib/language_server/build.ex:109: ElixirLS.LanguageServer.Build.reload_project/0
```

Originally reported in https://elixirforum.com/t/error-in-mixproject-with-elixirls/57099

**Comment by ndrean** [comment]
It still happens on a regular basis. The detail is below. The current solution is to erase/reinstall.

```
an exception was raised:
    ** (RuntimeError) build without intercepted logger []
        (language_server 0.15.1) lib/language_server/build.ex:109: ElixirLS.LanguageServer.Build.reload_project/0
        (language_server 0.15.1) lib/language_server/build.ex:20: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3
        (stdlib 5.0.2) timer.erl:270: :timer.tc/2
        (language_server 0.15.1) lib/language_server/build.ex:14: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3
        (kernel 9.0.2) global.erl:477: :global.trans/4ElixirLS
```

**Comment by lukaszsamson** [comment]
@ndrean Please post a minimal repro

**Comment by ndrean** [comment]
Looks like your update did the trick.

**Comment by lukaszsamson** [comment]
> Looks like your update did the trick.

Good to hear that but I'd still want to know how the the language server ended up erroring in that place

**Comment by ndrean** [comment]
It didn't matter which repo I was working on, all had the same error, so a minimal repo didn't make sense. Now it's just gone. Must have been the Elixir version?
