### ISSUE TITLE
Need a way to disable loading from asdf for some projects

### ISSUE THREAD

**Issue by dantswain** [elixir-lsp/elixir-ls#960]
### Environment

* Elixir & Erlang versions (elixir --version):  `Elixir 1.14.5 (compiled with Erlang/OTP 25)`
* Elixir Language Server version:  `v0.15.3`
* Operating system: macOS Ventura 13.4.1
* Editor or IDE name (e.g. Emacs/VSCode): VS Code Insiders
* Editor Plugin/LSP Client name and version: ElixirLS Elixir support and debugger v0.15.3

### Current behavior

I have a project where the team I'm working with uses [nix](https://nixos.org/) to manage the development environment, including Elixir and erlang.  I also have other projects on my system where I use asdf to manage Elixir and erlang.

In the project that is using nix, ElixirLS fails to start:

```
Looking for ASDF install in /opt/homebrew/opt/asdf/libexec/asdf.sh
ASDF found, relaunching in bash shell
Looking for ASDF install in /opt/homebrew/opt/asdf/libexec/asdf.sh
Sourcing ASDF
No version is set for command elixir
Consider adding one of the following versions in your config file at /Users/dswain/.tool-versions
elixir 1.15.4-otp-26
[Error - 10:54:51 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:54:51 AM] Connection to server got closed. Server will restart.
```

### Expected behavior

I expect ElixirLS not to crash in the nix-managed directory even though I still have asdf installed on my system.  Elixir and Erlang are both in my PATH when i started VS Code and this worked fine before I installed asdf for other projects.  I think ideally ElixirLS should work fine as long as it has Elixir and Erlang available in the PATH, regardless of the existence of other tools like asdf?  If that's not feasible, an option to manually disable using asdf in that directory would be sufficient.

**Comment by lukaszsamson** [comment]
Please send a PR

**Comment by dantswain** [comment]
An update on this - I _think_ i was able to make it work by setting `asdf local elixir system` but I want to run it a bit longer to make sure it will work before saying the issue is resolved for me.

**Comment by lukaszsamson** [comment]
Closing this since there seems to be a solution

**Comment by axelson** [comment]
Another way to accomplish this is in your `~/.config/elixir_ls/setup.sh` file you can change the filename that asdf is looking for. I've added `export ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=".tool-versions-global"` to my `setup.sh` (actually `setup.fish`) and then I set the versions I want in `~/.tool-versions-global`.
