### ISSUE TITLE
rtx + fish shell fails to launch the language server

### ISSUE THREAD

**Issue by Defman21** [elixir-lsp/elixir-ls#967]
### Environment

* Elixir & Erlang versions (elixir --version):
```
 Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.15.4 (compiled with Erlang/OTP 26)
```

* Elixir Language Server version: 0.16.0
* Operating system: MacOS Ventura 13.5
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name and version: 0.16.0

### Current behavior

```
Running /Users/defman/.vscode/extensions/jakebecker.elixir-ls-0.16.0/elixir-ls-release/launch.sh
Preffered shell fish is not supported, continuing in POSIX shell
Looking for ASDF install
ASDF not found
Looking for rtx executable
rtx executable found in /Users/defman/bin/rtx, activating
/Users/defman/.vscode/extensions/jakebecker.elixir-ls-0.16.0/elixir-ls-release/launch.sh: line 50: set: -g: invalid option
set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
[Error - 16:38:48] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 16:38:48] The ElixirLS - api server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 16:38:48] ElixirLS - api client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 16:38:48] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

I assume it fails because [`rtx activate $preferred_shell`](https://github.com/elixir-lsp/elixir-ls/blob/master/scripts/launch.sh#L50) ( => `rtx activate fish`) outputs fish-style config, which is then `eval`'d by `sh`, thus failing.

**Comment by Defman21** [comment]
Current workaround: hardcode `preferred_shell=bash` at this line: https://github.com/elixir-lsp/elixir-ls/blob/master/scripts/launch.sh#L14

**Comment by lukaszsamson** [comment]
Fish is not supported and I think it never was. It shouldn’t be difficult to add support if anyone is willing to contribute.

**Comment by Defman21** [comment]
I assume the "support" in this context is "launch.sh" but in fish script? (e.g. if we detect that the preferred shell is fish, execute `launch.fish` instead). We can't simply relaunch the current script because it's not going to work in fish.

**Comment by lukaszsamson** [comment]
I'm not familiar with fish so it's hard to tell. Executing dedicated `launch.fish` would probably be a best option. The other is to force fallback to bash/zsh

**Comment by lukaszsamson** [comment]
A possible solution would be adding
```
    elif [ "$preferred_shell" = "fish" ]; then
      >&2 echo "Preferred shell is fish, relaunching"
      exec "$(which fish)" -c "$0 relaunch"
```
and
```
elif [ "$preferred_shell" = "fish" ]; then
  # in fish shell, convert ELS_ELIXIR_OPTS into a list and pass to elixir
  if [ -n "$ELS_ELIXIR_OPTS" ]
  then
    # Use fish to split ELS_ELIXIR_OPTS into a list and join them back into a space-separated string
    elixir_opts=$(fish -c "string join ' ' (string split ' ' \"$ELS_ELIXIR_OPTS\")")
  else
    elixir_opts=""
  fi
  exec elixir $elixir_opts --erl "$default_erl_opts $ELS_ERL_OPTS" "$SCRIPTPATH/launch.exs"
```

**Comment by Defman21** [comment]
I'll try the second option and if it doesn't work, I'll go with the first one.
