### ISSUE TITLE
Show Dialyzer Report?

### ISSUE THREAD

**Issue by Aduril** [elixir-lsp/elixir-ls#97]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.9.4 (compiled with Erlang/OTP 22)
* Operating system: MacOs
* Client (editor or IDE): Emacs (spacemacs)

hey folks,
probably I am the idiot here, but is there any way to pretty-print the findings of the dialyzer analysis in emacs or just via console?

I thought that the dialyzer manifest could be used for that, but currently I only see a blob there.

Flycheck (an emacs tool) only displays errors within file in the current buffer, but I would like to see the results for my whole project.
I am not afraid to do some scripting on my own, but currently I am rather benighted how to even read that file.
I would really appreciate if you gave me some pointers here. :)

With kind regards
Peter

**Comment by axelson** [comment]
Hi @Aduril, I don't believe that there is anything built-in to accomplish this. So for now you'll have to add https://github.com/jeremyjh/dialyxir/ to your project (I'd highly recommend the latest rc) version and then you can run `mix dialyxir` to get a report.
