### ISSUE TITLE
Why are builds only triggered after save? 

### ISSUE THREAD

**Issue by yxshv** [elixir-lsp/elixir-ls#973]
Why isn't it triggered while i am writing my code, why would i have to save to see my errors and warnings?

**Comment by lukaszsamson** [comment]
How would you like to run `mix compile` on code that exists only in memory and is not written to the disk? We could add running `Code.string_to_quoted` on in memory code, this would provide some syntax related diagnostics but full compile is IMO not possible.

**Comment by yxshv** [comment]
oh ok
