### ISSUE TITLE
~H sigils no longer formatted after updating to Elixir 1.15.5

### ISSUE THREAD

**Issue by balexand** [elixir-lsp/elixir-ls#975]
### Environment

* Elixir & Erlang versions (elixir --version):  Elixir 1.15.5, OTP 26.0.2
* Elixir Language Server version: 0.16.0
* Operating system: Mac OS (Intel, latest)
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name and version: jakebecker.elixir-ls 0.16.0

### Current behavior

After updating to Elixir 1.15.5 ~H sigils are no longer formatted by the VSCode ElixirLS plugin. To reproduce, generate a new Phoenix project with `mix phx.new example`. The generated `ExampleWeb.CoreComponents` module contains ~H sigils that can be used for testing and the generated `.formatter.exs` file includes `plugins: [Phoenix.LiveView.HTMLFormatter]`. Running `mix format` from the command line will result in the ~H sigils being formatted. But if the formatter is run by ElixirLS then the Elixir code is formatted but not the ~H sigils.

Downgrading to Elixir 1.15.4 fixes the problem.

### Expected behavior

I would expect ~H sigils to be formatted by ElixirLS as it was prior to Elixir version 1.15.5.

Thanks.

**Comment by lukaszsamson** [comment]
Thanks for the report. There were formatter plugin related changes in 1.15.5. I will investigate

**Comment by champeric** [comment]
I just want to chime in that I have the exact same problem with the same environment.

**Comment by stevencorona** [comment]
I've had the same issue but specifically within an umbrella project - @lukaszsamson @champeric are you both working in umbrella projects as well?

It also seems to work sporatically, almost like it's using the wrong .formatter.exs configuration for the wrong project app.

**Comment by lukaszsamson** [comment]
Thanks for reporting. This is a regression in elixir 1.15.5

**Comment by lukaszsamson** [comment]
Already fixed upstream and backported to 1.15 branch. 1.16 and 1.15.6 releases should not be affected by this bug

**Comment by balexand** [comment]
Thanks!
