### ISSUE TITLE
Jump-to-definition ignores arity for function in different file

### ISSUE THREAD

**Issue by giddie** [elixir-lsp/elixir-ls#984]
### Environment

* Elixir 1.15.0
* Erlang/OTP 26
* Elixir Language Server version: v0.15.1
* Operating system: ArchLinux
* Editor or IDE name (e.g. Emacs/VSCode): NeoVim
* Editor Plugin/LSP Client name and version: lspconfig

### Current behavior

In two separate files:
```elixir
defmodule Test do
  def demo do
    Second.example()
    Second.example(:one)
    Second.example(:one, :two)
  end
end
```

```elixir
defmodule Second do
  def example() do
    :ok
  end

  def example(:one) do
    :ok
  end

  def example(:one, :two) do
    :ok
  end
end
```

Using the "jump to definition" function on each function call in `Test.demo/0`, the cursor always jumps to `Second.example/0`, even for the functions calls where the arity does not match.

### Expected behavior

The cursor should jump to the function with the correct arity. Note that this works correctly if both modules are in the same file.

**Comment by lukaszsamson** [comment]
Addressed in https://github.com/elixir-lsp/elixir_sense/pull/247
and released in v0.16.0. Please update

Note that it is not currently working for erlang functions (https://github.com/elixir-lsp/elixir_sense/issues/186)
