### ISSUE TITLE
Add install instructions in README for Helix editor 

### ISSUE THREAD

**Issue by samusz** [elixir-lsp/elixir-ls#993]
I believe the following instructions should be available in the README's install section.

From : https://elixirforum.com/t/helix-editor-for-elixir-development/54964 

Put the following configuration in `.config/helix/languages.toml`, and happy coding!
```
[[language]]
name = "elixir"
scope = "source.elixir"
injection-regex = "elixir"
file-types = ["ex", "exs"]
roots = ["mix.exs"]
auto-format = true
diagnostic-severity = "Hint"
comment-token = "#"
indent = {tab-width = 2, unit = " "}
language-server = {command = "elixir-ls"}
```

**Comment by lukaszsamson** [comment]
Please open a PR

**Comment by lukaszsamson** [comment]
I'm not using helix. I'll be happy to accept a PR from someone who does though
