### ISSUE TITLE
Neovim elixirls autocompetion source failed for local module

### ISSUE THREAD

**Issue by huibosa** [elixir-lsp/elixir-ls#995]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace] Elixir 1.15.6 (compiled with Erlang/OTP 26)
* Elixir Language Server version: v0.16.0
* Operating system: macos
* Editor or IDE name (e.g. Emacs/VSCode): Neovim
* Editor Plugin/LSP Client name and version: lspconfig

#### A short description of the issue

Begin learning elixir recently, and I was setup the elixirls in neovim following this [guide](https://elixirforum.com/t/neovim-elixir-setup-configuration-from-scratch-guide/46310). I could get most of the lsp elixirls feature work, such as doc hover, snippet, autocompletion, and so on, but I found I just can’t get the autocompeletion work for local module in another file. I’ll describe my problem as follows:

I've got two files in same directory, `person.exs` and `main.exs`:

<img width="796" alt="Screenshot 2023-10-03 at 4 14 18 PM" src="https://github.com/elixir-lsp/elixir-ls/assets/78707242/31f57867-945b-4aea-a61b-7f8478ade406">

<img width="433" alt="Screenshot 2023-10-03 at 4 15 35 PM" src="https://github.com/elixir-lsp/elixir-ls/assets/78707242/ff4b8af7-0f23-4f9f-a0b9-18e0fa550457">

which can be seen from the pictures that the autocompeletion source for module `Person` failed in `main.exs`. However, when I move the statements to `person.exs`, I could get the expected autocompeletion:

<img width="788" alt="Screenshot 2023-10-03 at 4 16 36 PM" src="https://github.com/elixir-lsp/elixir-ls/assets/78707242/dc6613c8-f071-4c58-a106-10c68698e665">

At first I thought this would be a lack of implementation of something in elixirls, but when I switch to vscode, where I've installed the elixirls viscode extension, finding that the autocompeletion works as ecpected:

<img width="703" alt="Screenshot 2023-10-03 at 3 59 40 PM" src="https://github.com/elixir-lsp/elixir-ls/assets/78707242/05593be8-b2bf-4204-9fb0-c7ed19ad26ad">

#### ElixirLS logs

```
[START][2023-10-03 17:51:28] LSP logging initiated
[ERROR][2023-10-03 17:51:28] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/huibosa/.local/share/nvim/mason/packages/elixir-ls/language_server.sh"	"stderr"	"Running /Users/huibosa/.local/share/nvim/mason/packages/elixir-ls/launch.sh\nPreffered shell is zsh, relaunching\nLooking for ASDF install\nASDF not found\nLooking for rtx executable\nrtx not found\n"
[ERROR][2023-10-03 17:51:28] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/huibosa/.local/share/nvim/mason/packages/elixir-ls/language_server.sh"	"stderr"	"Installing ElixirLS release v0.16.0\n"
[ERROR][2023-10-03 17:51:28] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/huibosa/.local/share/nvim/mason/packages/elixir-ls/language_server.sh"	"stderr"	"Running in /Users/huibosa\n"
[ERROR][2023-10-03 17:51:29] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/huibosa/.local/share/nvim/mason/packages/elixir-ls/language_server.sh"	"stderr"	"Install complete\n"
[ERROR][2023-10-03 17:51:29] ...lsp/handlers.lua:535	"Cannot get client configuration: {:ok, [nil]}"
[WARN][2023-10-03 17:51:32] ...lsp/handlers.lua:537	"Did not receive workspace/didChangeConfiguration notification after 3 seconds. The server will use default config."
[WARN][2023-10-03 17:51:32] ...lsp/handlers.lua:537	'No mixfile found in project. To use a subdirectory, set `elixirLS.projectDir` in your settings. Looked for mixfile at "/Users/huibosa/mix.exs"'
```

**Comment by lukaszsamson** [comment]
> 'No mixfile found in project. To use a subdirectory, set `elixirLS.projectDir` in your settings. Looked for mixfile at "/Users/huibosa/mix.exs"'

This is rather expected. You are running the language server in an ordinary directory.  Person module is not compiled and hence the language server is unable to autosuggest. It works if the code is in the same file but without mix project it is not able to see the relationship between the files.

Try to run it in a mix project.

**Comment by huibosa** [comment]
> > 'No mixfile found in project. To use a subdirectory, set `elixirLS.projectDir` in your settings. Looked for mixfile at "/Users/huibosa/mix.exs"'
> 
> This is rather expected. You are running the language server in an ordinary directory. Person module is not compiled and hence the language server is unable to autosuggest. It works if the code is in the same file but without mix project it is not able to see the relationship between the files.
> 
> Try to run it in a mix project.

Thanks for your help, autocompletion works as expected after I run the module in a mix project
