### ISSUE TITLE
Accept Word does not work across lines

### ISSUE THREAD

**Issue by Mayanks0307** [elixir-lsp/elixir-ls#996]
Issue 
Currently, my top pain point with using Accept Word in inline suggestions is that it does not go across lines. Once I get to the end of the line I can not trigger it anymore to start accepting words from the second line.

The same happens in the accept line suggestion disappears due to line change.

Version: 1.82

This issue(https://github.com/microsoft/vscode/issues/172162) was fixed in 1.78.2

In this pull request https://github.com/microsoft/vscode/pull/179988

Which has reappeared again.

**Comment by lukaszsamson** [comment]
Is it the right repo? Please share screenshots/videos that illustrate the issue.

**Comment by Mayanks0307** [comment]
Sorry by mistake closing the issue
